### ISSUE TITLE
How to crreate boolean field?

### ISSUE THREAD

**Issue by sagarjogi** [financialforcedev/apex-mdapi#100]
I am not able to createboolean field by using createfield method. It is giving me error like 'BOOLEAN' is not a valid value for the enum 'FieldType'

**Comment by afawcett** [comment]
Take a look at my Q&A [blog](http://andyinthecloud.com/2014/11/22/apex-metadata-api-qa/) point 6 for how to resolve this type of error message. But in answer to your question (and as also recommended in the Q&A blog), reference the [Salesforce Metadata API document](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_field_types.htm) shows that you need to use the value 'Checkbox'. Hope this helps! :+1:
