### ISSUE TITLE
MetadataServiceTest.cls References MetadataCreateJobTest.cls which doesn't seem to exist in the repo

### ISSUE THREAD

**Issue by mccallumjack** [financialforcedev/apex-mdapi#101]
Hello, I am trying to write some tests for this API and saw that in the MetadataServiceTest file it references a file MetadataCreateJobTest that I cannot seem to locate in the repo. Is this an outdated comment or am I looking in the wrong place?

"You should follow the usual practices to cover your other code, as shown in the MetadataCreateJobTest.cls"

"Dummy Metadata API web service mock class (see MetadataCreateJobTest.cls for a better example)"

If it is outdated, is there another good test example file?

Thanks,
Jack

**Comment by afawcett** [comment]
It is indeed an outdated comment, the class was removed, as the Metadata API's CRUD methods are now sync and not async, infact the async variants are now gone so it was not possible to keep the Apex wrapper current and retain the MetadataCreateJob. If you want some good examples of tests take a look at the [DLRS tool source code](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupControllerTest.cls). 

I'll leave this open to remind me to remove the comment.

**Comment by mccallumjack** [comment]
Got it, thank you.

**Comment by afawcett** [comment]
I've removed this reference now.
