### ISSUE TITLE
Report/Dashboard Folder name is not updating through Metadata API

### ISSUE THREAD

**Issue by sharanut** [financialforcedev/apex-mdapi#102]
Using metadata api able to get Report/Dashboard Folder using full name.
But updating the Report/Dashboard Folder name is not working.
In MetadataService.SaveResult object returning success flag as True and no errors.
Please help in resolving this.

**Comment by afawcett** [comment]
Can you share your code please?

**Comment by sharanut** [comment]
In Code Below please replace folder unique name.Tire with V33. Similar code for ReportFolder.

MetadataService.MetadataPort metaDataServiceHandle = new MetadataService.MetadataPort();
metaDataServiceHandle.SessionHeader = new MetadataService.SessionHeader_element();
metaDataServiceHandle.SessionHeader.sessionId = UserInfo.getSessionId();
MetadataService.DashboardFolder folder = (MetadataService.DashboardFolder) metaDataServiceHandle.readMetadata('DashboardFolder', 
					new String[] { <Folder Unique Name> }).getRecords()[0];

folder.name = 'Dashboard Reports';
MetadataService.SaveResult[] results = metaDataServiceHandle.updateMetaData( new List<MetadataService.DashboardFolder> {folder});
System.debug('results-->' + results);

Please help me for any missing

**Comment by afawcett** [comment]
Ah i see, this maybe a bug in the SF Metadata API, have you tried the renameMetadata method perhaps?

**Comment by sharanut** [comment]
I have not Tried renameMetadata method.
I will try and update you.

**Comment by afawcett** [comment]
@sharanut did you try renameMetadata? Any luck?

Let me know if you want to continue this discussion and we can surely re-open. :+1:
