### ISSUE TITLE
an exceeded limit working with metadata api

### ISSUE THREAD

**Issue by maryembourhi** [financialforcedev/apex-mdapi#105]
Hi andrew,

first of all thanks a lot for your posts and help, my issue is that i keep getting an exception when i try to get a list of objects the exception is: 

<b>Web service callout failed: WebService returned a SOAP Fault: EXCEEDED_ID_LIMIT: record limit reached. cannot submit more than 10 records in this operation 
</b>
I have tried getting the objects in a zip file like you have shown in one of your articles, but the issue is i need to access informations of objects without having to parse the files in the zip .

i would appreciate it if you could help or guide me to a potential solution or workaround.

Thank you

**Comment by afawcett** [comment]
If you simply want to list objects, you can use native Apex API's for this and avoid the callout this wrapper is making. Take a look for https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_dynamic_global_describe.htm. Does this help?

**Comment by afawcett** [comment]
Let me know if you need more help on this?
