### ISSUE TITLE
Get Ids of all fields of SObject - can this be done and how?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [financialforcedev/apex-mdapi#107]
Field Ids are needed to inject values into Standard layouts. As described here (http://andyinthecloud.com/2014/01/05/querying-custom-object-and-field-ids-via-tooling-api/) Field ids cannot be queried using the Apex Describe methods. This article show how the Tooling API can be used for that. BUT this will only work for Admin users with "View All Data" permissions. (see https://github.com/afawcett/apex-toolingapi/issues/19)

Is there a way to do the same using this Metadata API wrapper that requires fewer permissions?

**Comment by afawcett** [comment]
Maybe the listMetadata API will do this? Though the problem with this and Custom Field lists is it doesn't scale very well, as it returns all Custom Fields (including managed) in the org. :-1: 

However it does seem some of the Tooling API objects are appearing in Apex, so this now works....

    SELECT Id, QualifiedApiName, RelationshipName, ReferenceTo, ReferenceTargetField FROM FieldDefinition WHERE EntityDefinition.QualifiedApiName = 'Dog__c'

BTW, the field ID and value injection hack does not appear to work anymore in Lighting Experience from what i've been reading.
