### ISSUE TITLE
Reading ConnectedApp Seems to not work

### ISSUE THREAD

**Issue by tmowbrey** [financialforcedev/apex-mdapi#108]
When given the following:

    MetadataService.MetadataPort service = new MetadataService.MetadataPort();
    service.SessionHeader = new MetadataService.SessionHeader_element();
    service.SessionHeader.sessionId = UserInfo.getSessionId();
    MetadataService.ConnectedApp connectedApp =
            (MetadataService.ConnectedApp)service.readMetadata('ConnectedApp', new String[] {     'Workbench' }).getRecords()[0];
    system.debug('connectedApp = ' + connectedApp);

I receive null. It does not seem to matter what Connected App name I use or whether I use the full name or api name, I always receive null.

Any thoughts?

Thanks!

**Comment by afawcett** [comment]
Can you see them via Workbench?

**Comment by tmowbrey** [comment]
Hi Andrew,

Yes I can.

Tyler



Please Excuse Typos - Sent via Mobile Device On Sun, Oct 18, 2015 at 1:26 AM, Andrew Fawcett < notifications@github.com [notifications@github.com] > wrote:
Can you see them via Workbench?

—
Reply to this email directly or view it on GitHub
[https://github.com/financialforcedev/apex-mdapi/issues/108#issuecomment-148990733] .[https://github.com/notifications/beacon/AC5CYu3aXkuLxi-NoZcNyr7NwgH5EJpPks5o809PgaJpZM4GQzZx.gif]

**Comment by afawcett** [comment]
Ok will take a look later this week

**Comment by afawcett** [comment]
I've given this a quick look and concluded its only connected apps created in the org that appear. I see Workbench in my test org as a Connected App, but using Workbench itself to list COnnected App's i only see the one created in the org. [This is the sample code i used](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataServiceExamples.cls#L1514). Finally i had a quick look in the [docs](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_connectedapp.htm), but no specific mention of handling only in-org created connected apps. Hope this helps somewhat, and sorry for the delay in responding.
