### ISSUE TITLE
"LicenseDefinition" Feature!

### ISSUE THREAD

**Issue by SaraELA** [financialforcedev/apex-mdapi#109]
Hi Andrew, 

I would like to know how can we use "LicenseDefinition" Metadata API feature. I tried to use the method "listMetadata" that exists in MetadataService class, but it didn't work.

Please I need your help.

Thanks Andrew.

**Comment by SaraELA** [comment]
this is the error that I get, using "listMetadata" : 

Web service callout failed: WebService returned a SOAP Fault: INVALID_TYPE: Cannot use: LicenseDefinition in this organization faultcode=sf:INVALID_TYPE faultactor=

**Comment by afawcett** [comment]
I asked about this on twitter, no [definitive](https://twitter.com/andyinthecloud/status/583630348174630913) answer, i assume its a future thing.
