### ISSUE TITLE
Create a Package Using Metadata API!

### ISSUE THREAD

**Issue by SaraELA** [financialforcedev/apex-mdapi#110]
Hi Andrew,

I would like to create a package programmatically using Metadata API, in order to detect field dependencies.

Thank you Andrew.

**Comment by afawcett** [comment]
Sorry creating a Package (as in what is under Setup > Create > Packages) is not possible. You can certainly populate and update one via Metadata API , but you cannot through the Salesforce Metadata API reproduce the action of going to the Setup > Create > Packages page and clicking New. Sorry for the bad news.
