### ISSUE TITLE
Cannot delete custom field after creating it through the Metadata API

### ISSUE THREAD

**Issue by cnaccio** [financialforcedev/apex-mdapi#112]
I'm running into a strange issue when attempting to use the mdapi to create, and delete custom lookup fields on a custom object. Basically the app I'm working on allows you to create, and remove custom lookup fields on a specific custom object. After creating, and deleting the same lookup field twice I start getting a cryptic internal server error upon trying to delete the lookup fields either through the mdapi or the standard Salesforce UI. The steps to reproduce my issue are:

1. Create lookup field using mdapi
2. Delete the above created lookup field using the mdapi
3. Create another lookup field using the mdapi
4. Attempt to delete the above created second lookup field using the mdapi; this is where the error starts.

My initial reaction when trying to delete the 2nd lookup field was to go into the setup UI, and try deleting it from there. However I was getting the same error below. Note that I would get this error when trying to delete the 1 field in the deleted field recycle bin, if you will, or the second field that hadn't been deleted yet. 

##### *An internal server error has occurred*
*An error has occurred while processing your request. The salesforce.com support team has been notified of the problem. If you believe you have additional information that may be of help in reproducing or correcting the error, please contact Salesforce Support. Please indicate the URL of the page you were requesting, any error id shown on this page as well as any other related information. We apologize for the inconvenience.* 

*Thank you again for your patience and assistance. And thanks for using salesforce.com!*

*Error ID: 310618243-119730 (1977830510)*

After banding my head against the wall trying to figure out how to get rid of these lookup fields I tried changing the child relationship name, saving the field, and then trying to delete the field; this worked. In order to delete the first field that was in the deleted field recycle bin I had to undelete it, change the child relationship name, and then delete it again.

Even though I now have a workaround I still need to figure out why this is happening, and how to fix/avoid it. My gut tells me it may have something to do with how I'm creating/deleting the fields... Like maybe I'm forgetting to populate some important field properties? 

Here's my code to create the lookup field:

	/*******************************************************************************************************
	* @description Create a lookup field on any object to any object
	* @param Name of the object this lookup field is to be created on
	* @param Name of the other object this lookup field will relate to
	* @param The lookup field's label
	* @param The lookup field's name
	* @param The lookup field's description
	* @param The lookup field's help text
	* @param The label for the relationship that will be created between the source and lookup object
	* @param The name for the relationship that will be created between the source and lookup object
    * @return Created lookup field name
	* @example
	* configMetaUtils.createLookupField(
	* 	'Payment__c',
	*	'Opportunity',
	*	'Payment Opportunity',
	*	'Payment_Opportunity',
	*	'The opportunity related to this payment.',
	*	'Select the opportunity this payment was created from.',
	*	'Payments',
	*	'Payments'
	* );
	*/
	public String createLookupField(
		String relatedFrom,
		String relatedTo,
		String fieldLabel,
		String fieldName,
		String fieldDescription,
		String fieldHelpText,
		String childRelationshipLabel,
		String childRelationshipName
	) {
        
        // Validate from and to objects
        SObjectType relatedTosObjectType = Schema.getGlobalDescribe().get(relatedTo);
        SObjectType relatedFromsObjectType = Schema.getGlobalDescribe().get(relatedFrom);
		if(relatedTosObjectType == null) {
			throw new Configuration.ApplicationException(
				'"' + relatedTo + '" is not a valid object to relate to. Please try again.'
			);
		}
		if(relatedFromsObjectType == null) {
			throw new Configuration.ApplicationException(
				'"' + relatedFrom + '" is not a valid object to lookup to. Please try again.'
			);
		}

		// Create custom field
		configuration_MetadataService.CustomField customField = new configuration_MetadataService.CustomField();
        customField.referenceTo = relatedTo;
        customField.label = fieldLabel;
        customField.fullName = relatedFrom + '.' + fieldName;
        customField.description = fieldDescription;
        customField.inlineHelpText = fieldHelpText;
        customField.relationshipLabel = childRelationshipLabel;
        customField.relationshipName = childRelationshipName;
        customField.type_x = 'Lookup';
        List<configuration_MetadataService.SaveResult> results;
        results = this.service.createMetadata(new configuration_MetadataService.Metadata[] { customField });
        this.handleSaveResults(results[0]);

        // If no exceptions have been thrown thus far go ahead, and return the lookup field's name
        return fieldName;
	}

Here's my code to delete the lookup field:

	/*******************************************************************************************************
	* @description Delete an existing lookup field
	* @param Name of the object the lookup field will be deleted from
	* @param Name of the lookup field
	* @example
	* configMetaUtils.deleteLookupField('Payment__c', 'Opportunity__c');
	*/
	public void deleteLookupField(String fieldObjectName, String fieldName) {
        List<configuration_MetadataService.DeleteResult> results =
            this.service.deleteMetadata(
                'CustomField', new String[] { fieldObjectName + '.' + fieldName });
        this.handleDeleteResults(results[0]);
	}

Any help, advice, or insight would be much appreciated. This code is part of my apps setup wizard which is so close to being finished. Thanks in advance!

**Comment by afawcett** [comment]
Your app sounds most exciting! 

Yes i think your getting stuck with your deletes only being soft deletes. There is a facility with the deploy operation to do a forced delete which bypasses the field / custom object recycle bin, however i'm not aware of any on the CRUD metadata options (though worth double checking headers and such like). Other thought would be can you try a second delete operation on the fields deleted name which i think becomes something like Fred_del__c? 

Finally, [GACK's](https://developer.salesforce.com/blogs/engineering/2015/02/gack.html) are worth passing to Salesforce as if they can give you the underlying messages these can sometimes be quite helpful, so might be worth doing a repo in CURL and sending that over to SF via a Support Case.
