### ISSUE TITLE
Permissions issue when adding related list to page layout

### ISSUE THREAD

**Issue by cnaccio** [financialforcedev/apex-mdapi#113]
I'm running into an issue when trying to add a related list to a page layout. If I don't have field visibility on the lookup/relationship field that the related list is based on I get a FIELD_INTEGRITY_EXCEPTION when attempting to update the page layout using the mdapi. For example in my app I have a Payment object with a lookup field to the Opportunity object; Payment__c.Opportunity__c. If I give myself permission to this field before attempting the page layout update all is fine. The strange thing however is that I'm able to manually, through the page layout editor, add the payments related list to the opportunity page layout even if I don't have field visibility permission. In my app the lookup field is created by the same code that updates the page layout; the field is created right before attempting to add the related list.

My temporary workaround has been to update an assigned permission set between creating the lookup field, and attempting to add the related list to a page layout. I can ultimately create this workflow in my app if I have too, but I'd like to avoid doing so if possible. I'm thinking since I can add the related list manually, using the salesforce UI, without permission then there must be a way to do it via the metadata api as well right? Any help is much appreciated; thanks!

**Comment by afawcett** [comment]
Wow this does sound like its inconsistent, and possibly an indication Salesforce's Layout Editor may not be using the Metadata API internally or if it is, in some elevated fashion. The only thing i could suggest is to use an oAuth token (instead of the users Session ID) stored in protected way and previously obtained (via oAuth Web Flow) for a user that does have the permissions. So that you can do your own elevate within the tool on the users behalf.

**Comment by afawcett** [comment]
It might also be worth raising a SF Support case as well btw. If you do, be sure to reproduce it via something like curl, as this will avoid unneccessary distraction of the Apex wrapper.

**Comment by Sheing** [comment]
Having the similar issue here. Error:  FIELD_INTEGRITY_EXCEPTION when I am trying to update or upsert related list. If there's an existing field in that related list that doesn't have any FLS configured, it would throw this error.  Looking for workaround and suggestions.
