### ISSUE TITLE
Library fails to deploy to an org that doesn't have Communities enabled

### ISSUE THREAD

**Issue by grekker** [financialforcedev/apex-mdapi#115]
I tried to deploy apex-mdapi to a Developer Edition org for testing today and got the following error. This was using the little "Deploy to Salesforce" button / tool on the main repository page.

> Deployment Started
Status: Queued
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: Completed
Deployment Complete
Failures:
classes/MetadataDataController.cls(40,4):Dependent class is invalid and needs recompilation:
MetadataServiceExamples: line 1457, column 17: Variable does not exist: Account.IsPartner
classes/MetadataServiceExamples.cls(1457,17):Variable does not exist: Account.IsPartner
pages/metadatadata.page(metadatadata):Apex class 'MetadataDataController' does not exist

Recognizing the error as something I've seen before with Communities, I checked to see if Communities had been enabled on this org (it had not). After enabling Communities on the org, I was able to deploy again successfully.

The root problem here is the dependence on the existence of Account.IsPartner, which doesn't exist before Communities are enabled.

**Comment by afawcett** [comment]
Thanks, i've removed this reference so others should not get this problem in the future.
