### ISSUE TITLE
Getting IO exception while creating field level security for a new field

### ISSUE THREAD

**Issue by Sainath710** [financialforcedev/apex-mdapi#117]
IO Exception: Read timed out

 at Class.MetadataService.MetadataPort.updateMetadata: line 10070, column 1

**Comment by afawcett** [comment]
This Apex API is actually wrapping an underlying HTTP callout to the Salesforce Metadata API which is a SOAP based Web Service. In Apex when you make a HTTP callout the platform [puts limits on how long it will wait for a response](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_callouts_timeouts.htm). This is the limit you have hit. As per the docs you can change the default timeout from 10 seconds upto a maximum of 120 seconds. Take a look at this https://github.com/financialforcedev/apex-mdapi/issues/77 for more information on how to do that.
