### ISSUE TITLE
Remove the controlling field on a managed picklist

### ISSUE THREAD

**Issue by jce4347** [financialforcedev/apex-mdapi#120]
I am not able to remove the controlling field on a managed picklist.

Error : CANNOT_MODIFY_MANAGED_OBJECT

I am concerned because as an admin I am able to break the dependency manually by remove the field dependencies, so I assume it must be possible through code as well.  Thoughts?

public static PageReference breakDependency()
{
    MetadataService.MetadataPort service = createService();
    MetadataService.CustomField customField = (MetadataService.CustomField) service.readMetadata(
        'CustomField', new String[] { 'Account.County__c' }
    ).getRecords()[0];

    metadataservice.Picklist pt = new metadataservice.Picklist();
    pt.sorted= false;
    //pt.controllingField = '';  no define = no controlling field.
    metadataservice.PicklistValue two = new metadataservice.PicklistValue();
    two.fullName= 'Non NY Stuffs';
    two.default_x=false;
    pt.picklistValues = new list<metadataservice.PicklistValue>{two};
    customField.picklist = pt ;

    List<MetadataService.SaveResult> results = service.updateMetadata(new MetadataService.Metadata[] { customField });
    handleSaveResults(results[0]);
    return null;  
}

**Comment by afawcett** [comment]
This error message is correct, you cannot edit this attribute of a packaged installed custom field. You should be able to do this through the Setup UI either.
