### ISSUE TITLE
MetadataService.FlowRecordCreate variable doesn't exist: name

### ISSUE THREAD

**Issue by emoran** [financialforcedev/apex-mdapi#121]
Hi, I'm trying to create a flow with the Metadata Service but when I want to save my file, it says the variable name doesn't exist. Do I forgot something?

![image](https://cloud.githubusercontent.com/assets/1028534/13239683/2094fcf6-d9aa-11e5-993c-8b64bf39df8a.png)

**Comment by afawcett** [comment]
I cannot see anything obvious here, though your screenshot is clipped, is MavensMate showing a line number?

**Comment by emoran** [comment]
Hi @afawcett I stop use the FlowRecordCreate, and I change it for an ActionCall in my code, so this is not a problem anymore. I could create my ProcessBuilder flow in apex. Here what I was trying yo do. [my question in stackexchange](http://salesforce.stackexchange.com/questions/111429/create-flow-with-metadata-api-process-builder-flow-from-apex). Thanks for the followup

**Comment by afawcett** [comment]
This is great, i've just tweeted your answer on SE as it happens, great stuff! :+1:
