### ISSUE TITLE
Support for Geolocation field related attribute (displayLocationInDecimal)

### ISSUE THREAD

**Issue by sureshkumar31** [financialforcedev/apex-mdapi#122]
Hello @afawcett 

Recently we came across a requirement to create Geolocation field. It was quite straight forward to create the Geolocation field just like other fields by setting the appropriate values. However, we were not able to set one of the specific option for this field which tells the format to be displayed (Degrees vs Decimal). By default, it gets set to Degrees and I wanted to have that as Decimal. 

After some research we found that there is an attribute called "displayLocationInDecimal" available for CustomField type. Surprisingly, I didn't see that in the Metadata WSDL too. However, I went ahead and hand edited the MetadataService class to include this new attribute in the CustomField inner class. I am now able to set value for that field as true and have the setting as Decimal. Thought that this little addition could be useful for some one else too.

**Comment by afawcett** [comment]
Yeah this is odd, thought actually it seems a step was missed when i refreshed the MetadataServices.cls file in Summer or subsequently, if you check the README file there are notes to remind whoever does this (usually me!) to do it. So apologies, it appears i forgot last time i refreshed the class (ideally i should edit the WSDL first would be a better way actually). Anyway for now i'll log this as a bug and get this sorted in the repo copy, glad in the meantime your sorted! :+1:

**Comment by sureshkumar31** [comment]
Great! Thanks for taking a note of this. Do you have any idea on why this attribute is not available in the Metadata WSDL?

Finally, I would like to thank you very much for providing this wonderful Apex wrapper for Metadata API. We have been using this in quite a few projects :)

**Comment by afawcett** [comment]
Your very welcome, though i do hope it becomes Salesforce supported in the native platform very soon. Please do share some of your project ideas if you can, i do like to highlight them in the readme file, even better if you have screenshots. Otherwise no pressure, please continue to enjoy! 

Oh and no, no idea why its missing, the original finder of this (in another issue) and i pondered over it as well. Its probably a bug, and should be raised as a case to Salesforce tbh.

**Comment by afawcett** [comment]
Ooops re-opening, forgot i've yet to officially fix it. :+1:

**Comment by sureshkumar31** [comment]
Are you asking me about the scenarios where I am using this class? I have used this in about 2 to 3 places. I use the CustomField creation method only. If you can elaborate little bit on what you would like to see, I will be happy to share.

**Comment by afawcett** [comment]
No worries i don't need anything from you at this moment, thank you.

**Comment by afawcett** [comment]
This has now been in the API for a while now, closing this issue out.
