### ISSUE TITLE
Can I create a report with apex-mdapi ?

### ISSUE THREAD

**Issue by AltiusRupert** [financialforcedev/apex-mdapi#123]
Hi Andy,
Will apex-mdapi (and the underlying Metadata API) let me create a new report in Salesforce ?

Rupert

**Comment by afawcett** [comment]
Yes it will, there is no example for create, but one for read. Take a look at the [Q&A](http://andyinthecloud.com/2014/11/22/apex-metadata-api-qa/) and Salesforce docs for this Metadata Type [here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_report.htm), there is an example (in XML) at the bottom. Also check the Q&A for tips on writing code against the API based on a Report you've manually created and pulled down as XML as a guide. Hope this helps, sorry i don't have time at present to write a sample for you.

**Comment by AltiusRupert** [comment]
Andrew, thanks for your anwser which is great support : I will look into this method.
Keep your precious time for your customers.

Thanks,
Rupert

**Comment by KGFTW** [comment]
@AltiusRupert Did you manage to create reports using the metadata api ? 
A sample would be appreciated :)

**Comment by AltiusRupert** [comment]
@KGFTW No I didn't, sorry to disappoint you :(

**Comment by afawcett** [comment]
@KGFTW  was kind enough to share his example on another issue. I have since given him a shout out on Twitter and on the main page [here](https://github.com/financialforcedev/apex-mdapi#community-examples). Thanks @KGFTW
