### ISSUE TITLE
handleSaveResults

### ISSUE THREAD

**Issue by md6759** [financialforcedev/apex-mdapi#124]
Nice work but I have error message when I save:
**Method does not exist or incorrect signature: handleSaveResults(MetadataService.SaveResult)**
And here the class:

_**public class MyTestingUpdatePicklist {
	 public static void updatePicklistField()
    {
        MetadataService.MetadataPort service = MetadataServiceExamples.createService();
        MetadataService.CustomField customField = new MetadataService.CustomField();
        customField.fullName = 'Opportunity.test__c';
        customField.label = 'test';
        customField.type_x = 'Picklist';
        metadataservice.Picklist pt = new metadataservice.Picklist();
        pt.sorted= false;
        metadataservice.PicklistValue eyecare = new metadataservice.PicklistValue();
        eyecare.fullName= 'eye';
        eyecare.default_x=false ;
        metadataservice.PicklistValue eyeone = new metadataservice.PicklistValue();
        eyeone.fullName= 'hand';
        eyeone.default_x=false ;
        pt.picklistValues = new list<metadataservice.PicklistValue>{eyecare,eyeone};
        customField.picklist = pt ;
        List<MetadataService.SaveResult> results = service.updateMetadata( 
            new MetadataService.Metadata[] { customField });
        handleSaveResults(results[0]);
       // handleSaveResults( service.updateMetadata(
     //   new MetadataService.Metadata[] { customField })[0]);
	//	SaveResult[]  results = metadataConnection.updateMetadata(Metadata[] customField);
    }
}**_

Help needed please.

**Comment by frup42** [comment]
I'm guessing you've based the provided code on the examples in MetadataServiceExamples? The handleSaveResults method is defined in that class. Your code fails to compile because no such method 'handleSaveResults(MetadataService.SaveResult)' defined in your class.

**Comment by md6759** [comment]
Thank you frup42, I was able to fix the issue but still the picklist values have not been added to the custom field. Any help?

**Comment by frup42** [comment]
Looks like there's a few more problems in the code you provided.

`pt.picklistValues = new list{eyecare,eyeone};`
should be: `pt.picklistValues = new List<MetadataService.PicklistValue>{eyecare,eyeone};`

`List results = service.updateMetadata(`
should be: `List<MetadataService.SaveResult> results = service.updateMetadata(`

And you're calling updateMetadata - from the OP I got the impression you were trying to CREATE, not UPDATE a picklist field. Do you get the required result when you call createMetadata instead?

**Comment by md6759** [comment]
Thank you David. The picklist field exists already as a custom field. I'm trying to add values to the picklist.

**Comment by md6759** [comment]
In fact, here is the bigger picture of what I'm trying to accomplish. I have a custom object A and I want every time a record X is added to the custom object A, X get added as a value of the picklist field b of the custom object C. 
Thank you again.

**Comment by frup42** [comment]
With the slight modifications to the List declarations, I'm able to add and update the Opportunity.Incumbent__c picklist field with your code. So I'm not too sure where you're going wrong.

Are you getting any error messages? Are you able to update other field types or other metadata types?

Also, your use case says you want to add a picklist value for every new CustomObjectA record. The field definition you apply using the metadata API will overwrite the allowed values, so you should probably read in the existing picklist values first so they aren't lost every time a new CustomObjectA record is created. You should also consider duplicate values, and (if your use case requires it) removing picklist values when CustomObjectA records are deleted.

**Comment by md6759** [comment]
Hello David,

Can we connect by email? Here is my email salesforcemd@gmail.com. 

Thank you.

**Comment by frup42** [comment]
Hi, I'd prefer to keep discussions relating to these repos in public. That way, other wise people can weigh in with advice, and the discussion remains as a resource for other people who have similar problems.

Using the Metadata API seems a good fit for your use case, so I'd start by making sure the examples in MetadataServiceExamples all work for you. This will rule out any issues about whether or you've deployed the code successfully, whether you have the right permissions in your org and whether you've set up remote site settings correctly.

**Comment by md6759** [comment]
You are right David. This discussion may help people having the same kind of issue. Here is my code

**_public class MyTestingUpdatePicklist {
    public class MetadataServiceExamplesException extends Exception { }

    public static MetadataService.MetadataPort createService()
    {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        return service;
    }

    public static void handleSaveResults(MetadataService.SaveResult saveResult)
    {
        // Nothing to see?
        if(saveResult==null || saveResult.success)
            return;
        // Construct error message and throw an exception
        if(saveResult.errors!=null)
        {
            List<String> messages = new List<String>();
            messages.add(
                (saveResult.errors.size()==1 ? 'Error ' : 'Errors ') +
                    'occured processing component ' + saveResult.fullName + '.');
            for(MetadataService.Error error : saveResult.errors)
                messages.add(
                    error.message + ' (' + error.statusCode + ').' +
                    ( error.fields!=null && error.fields.size()>0 ?
                        ' Fields ' + String.join(error.fields, ',') + '.' : '' ) );
            if(messages.size()>0)
                throw new MetadataServiceExamplesException(String.join(messages, ' '));
        }
        if(!saveResult.success)
            throw new MetadataServiceExamplesException('Request failed with no specified error.');
    }
    
	 public static void updatePicklistField()
    {
        MetadataService.MetadataPort service = MetadataServiceExamples.createService();
        MetadataService.CustomField cs = new MetadataService.CustomField();
        cs.fullName = 'Opportunity.test__c';
        cs.label = 'test';
        cs.type_x = 'Picklist';
        metadataservice.Picklist pt = new metadataservice.Picklist();
        pt.sorted= false;
        metadataservice.PicklistValue abc = new metadataservice.PicklistValue();
        abc.fullName= 'abc';
        abc.default_x=false ;
        metadataservice.PicklistValue xyz = new metadataservice.PicklistValue();
        xyz.fullName= 'xyz';
        eyeone.default_x=false ;
        pt.picklistValues = new list<metadataservice.PicklistValue>{abc,xyz};
        cs.picklist = pt ;
      List<MetadataService.SaveResult> results = service.updateMetadata( new MetadataService.Metadata[] { cs });
      handleSaveResults(results[0]);
      // handleSaveResults( service.updateMetadata(
     //   new MetadataService.Metadata[] { customField })[0]);
	//SaveResult[]  results = metadataConnection.updateMetadata(Metadata[] customField);
  //  SaveResult[] results = metadataConnection.updateMetadata(newMetadata[] {cs});
    }
_**}

Thank you for your help.

**Comment by frup42** [comment]
Hi again,
The code looks fine, apart from that stray reference to ```eyeone.default_x=false ;``` - I changed eyeone to xyz and updated the field successfully in my org through Execute Anonymous.

You'll need to give me a bit more to go on. What's actually going wrong when you run the code?

Are you getting ```System.CalloutException: IO Exception: Unauthorized endpoint, please check Setup->Security->Remote site settings. endpoint = https://eu6.salesforce.com/services/Soap/m/35.0```?
If so, then you need to add the remote site setting.

Are you getting ```Error occured processing component Opportunity.test__c. In field: fullName - no CustomField named Opportunity.test__c found (INVALID_CROSS_REFERENCE_KEY).```?
If so, then the field you're trying to update doesn't exist. You may need to qualify the field or object with namespace prefix if appropriate. Perhaps it is case sensitive - try matching the field name exactly.

Are you getting something else entirely? If so, what is the behaviour?

**Comment by md6759** [comment]
Thank you David.

I don't get any error but the values have not been added to the picklist.

Can you share the part of the code you are executing in Execute Anonymous? Or did you create a trigger that run the class? If that's the case, can you share your trigger?

Again, thank you so much for your time and help.

**Comment by frup42** [comment]
Sure. My class looks like this:
    
    public class MyClass
    {
        public static void doStuff()
        {
            MetadataService.MetadataPort service = MetadataServiceExamples.createService();

            MetadataService.CustomField cs = new MetadataService.CustomField();
            cs.fullName = 'Opportunity.test__c';
            cs.label = 'test';
            cs.type_x = 'Picklist';

            Metadataservice.Picklist pt = new Metadataservice.Picklist();
            pt.sorted= false;

            Metadataservice.PicklistValue abc = new Metadataservice.PicklistValue();
            abc.fullName= 'abc';
            abc.default_x=false ;

            Metadataservice.PicklistValue xyz = new Metadataservice.PicklistValue();
            xyz.fullName= 'xyz';
            xyz.default_x=false ;

            pt.picklistValues = new list<Metadataservice.PicklistValue>{abc,xyz};
            cs.picklist = pt ;
            
            //For brevity, don't bother checking results
            service.updateMetadata( new MetadataService.Metadata[] { cs });
        }
    }
    
And I call ```MyClass.doStuff()``` in execute anonymous.

**Comment by md6759** [comment]
Thank you David for your support. You can close the case.

**Comment by md6759** [comment]
Sorry guys to post again when it's already closed but I have an urgent question.

I was able to add values but they overwrite the existing values of the picklist. I just noticed that David was referencing this in a previous comment: " Also, your use case says you want to add a picklist value for every new CustomObjectA record. The field definition you apply using the metadata API will overwrite the allowed values, so you should probably read in the existing picklist values first so they aren't lost every time a new CustomObjectA record is created. You should also consider duplicate values, and (if your use case requires it) removing picklist values when CustomObjectA records are deleted.".

David, can you please provide a piece of code to read the existing values and avoid their deletion when a new value is added?

Thank you again for the good work.

**Comment by md6759** [comment]
I finally fixed the issue and I decided to share the solutions for people to see how to add values to picklist field. Thank you David and Andy for the work.
`
public class MyNewTestClass {
    public static MetadataService.MetadataPort createService()
    {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        return service;
    }
    public class MetadataServiceExamplesException extends Exception { }
    public static void handleSaveResults(MetadataService.SaveResult saveResult)
    {
        // Nothing to see?
        if(saveResult==null || saveResult.success)
            return;
        // Construct error message and throw an exception
        if(saveResult.errors!=null)
        {
            List<String> messages = new List<String>();
            messages.add(
                (saveResult.errors.size()==1 ? 'Error ' : 'Errors ') +
                    'occured processing component ' + saveResult.fullName + '.');
            for(MetadataService.Error error : saveResult.errors)
                messages.add(
                    error.message + ' (' + error.statusCode + ').' +
                    ( error.fields!=null && error.fields.size()>0 ?
                        ' Fields ' + String.join(error.fields, ',') + '.' : '' ) );
            if(messages.size()>0)
                throw new MetadataServiceExamplesException(String.join(messages, ' '));
        }
        if(!saveResult.success)
            throw new MetadataServiceExamplesException('Request failed with no specified error.');
    }
    
     public static void updatePicklist()
    {
        MetadataService.MetadataPort service = createService();

        // Read Custom Field
        MetadataService.CustomField customField =
            (MetadataService.CustomField) service.readMetadata('CustomField',
                new String[] { 'Opportunity.test__c' }).getRecords()[0];

        // Add pick list values
        metadataservice.PicklistValue two = new metadataservice.PicklistValue();
        two.fullName= 'second';
        two.default_x=false;
        metadataservice.PicklistValue three = new metadataservice.PicklistValue();
        three.fullName= 'third';
        three.default_x=false;
        customField.picklist.picklistValues.add(two);
        customField.picklist.picklistValues.add(three);

        // Update Custom Field
        handleSaveResults(
            service.updateMetadata(
                new MetadataService.Metadata[] { customField })[0]);
    }
}
`

**Comment by afawcett** [comment]
Thanks for this contribution, are we ok to close this issue now?

**Comment by md6759** [comment]
Sorry the trigger is not working b cause the an error. I will put the code later.
Thank you.

**Comment by md6759** [comment]
Any help on this issue?

**Comment by afawcett** [comment]
What context are you running the UpdateTestPicklist method in? Are you in Batch / Async Apex? Lighting Experience? Or some other?

**Comment by md6759** [comment]
I'm in standard salesforce environment Async Apex. Not Lightning.

**Comment by afawcett** [comment]
In Async Apex, UserInfo.getSessionId(); returns null, you need to call this from the calling code and pass it in as an argument to your method.

**Comment by md6759** [comment]
Thank you Andrew for your help. I will try it and let you know.

Thanks again.

**Comment by md6759** [comment]
Hello Andrew and David. Thank you for your help. 

Finally I abandoned this solution and create a custom object with custom lookup fields to the opportunity. After that, I run a report to the opportunity and the custom fields. From there, I used Vlookup to match the custom fields to their corresponding picklist records in the opportunity. The next step was to use Dataloader to update the opportunities with the new custom lookup fields IDs. Now I used Eclipse the Force IDE to search and replace the old picklist name with the new lookup fields names. I applied that in the reports and workflows. The last step was to update manually the validation rules and replace the old picklist fields by the new lookup fields in the opportunity page layouts.

THANK YOU SO MUCH FOR YOUR HELP.

**Comment by afawcett** [comment]
@md6759 thanks for the follow up, the key thing is you found a solution and thats the main thing! 👍

**Comment by dfruddffdc** [comment]
Hi @harshad22dani, please can you raise this as a new issue rather than a comment on a closed issue?

**Comment by dfruddffdc** [comment]
As a quick note, the following code compiles for me (although obviously results in a Null Pointer Exception).
```java
MetadataService.MetadataPort service = null;
MetadataService.CustomObject customObject = new MetadataService.CustomObject();
service.createMetadata(new MetadataService.Metadata[] { customObject });
```

**Comment by himanshunimje1** [comment]
Hello David/Andrew 


I am trying to create new Picklist field value with the same code above but it's not updating.

I tried with new value, valueSet , ValueDefination process as we are using latest 42 API version where Picklist is deprecated.


public class MetadataServiceDemoPicklist {
    
    public static String SOAP_M_URI = 'http://soap.sforce.com/2006/04/metadata';
    
    public static MetadataService.MetadataPort createService()
    {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        return service;
    }
    
    public static void createPicklistField()
    {
        
        MetadataService.MetadataPort service = createService();
        MetadataService.CustomField customField = new MetadataService.CustomField();
        List<MetadataService.CustomField> customfields = new List<MetadataService.CustomField>();
        
        //newly added 
        customField = new MetadataService.CustomField();
        customField.fullName = 'Account.Test_Picklist__c';
        customField.label = 'Segment';
        customField.type_x = 'Picklist';
        customField.description = '';
        
        
        //Create the valueSet for picklist type
        MetadataService.ValueSet picklistValueSet = new MetadataService.ValueSet();  //ValueSet
        
        //For each ValueSet, we have either ValueSetValuesDefinition or ValueSettings and some other 
        attributes
        MetadataService.ValueSetValuesDefinition valueDefinition = new 
        MetadataService.ValueSetValuesDefinition();  //ValueSetDefination
        
        List<MetadataService.CustomValue> values = new List<MetadataService.CustomValue>();
        
        //Value 1 
        MetadataService.CustomValue customValue1 = new MetadataService.CustomValue();
        customValue1.fullName = 'Testing Metadata value 1'; //API name of picklist value
        // customValue1.default = false;
        customValue1.description = '';
        customValue1.isActive = true;
        customValue1.label = 'Testing Metadata value 1';
        system.debug('customValue1' + customValue1);
        values.add(customValue1);
        //Value 2
        MetadataService.CustomValue customValue2 = new MetadataService.CustomValue();
        customValue2.fullName = 'Testing Metadata value 2'; //API name of picklist value
        // customValue1.default = false;
        customValue2.description = '';
        customValue2.isActive = true;
        customValue2.label = 'Testing Metadata value 2';
        system.debug('customValue2' + customValue2);
        values.add(customValue2);
        
        system.debug('values' + values);
        
        //It will be list of CustomValue
        valueDefinition.value = values;
        valueDefinition.sorted = true;
        
        //set the valueSetDefinition
        picklistValueSet.valueSetDefinition = valueDefinition;
        
        //Set the valueSet for picklist type
        customField.valueSet = picklistValueSet;
        system.debug('customField' + customField);
        customFields.add(customField);
        
        List<MetadataService.SaveResult> results =
            service.createMetadata( new MetadataService.Metadata[] { customField });
        System.debug('results' + results);
        handleSaveResults(results[0]);
        
        
    }

        public MetadataService.SaveResult[] createMetadata(MetadataService.Metadata[] metadata) {
            MetadataService.createMetadata_element request_x = new 
            MetadataService.createMetadata_element();
            request_x.metadata = metadata;
            MetadataService.createMetadataResponse_element response_x;
            Map<String, MetadataService.createMetadataResponse_element> response_map_x = new 
            Map<String, MetadataService.createMetadataResponse_element>();
            response_map_x.put('response_x', response_x);
            system.debug('response_map_x' + response_map_x);
            WebServiceCallout.invoke(
                this,
                request_x,
                response_map_x,
                new String[]{endpoint_x,
                    '',
                    SOAP_M_URI,
                    'createMetadata',
                    SOAP_M_URI,
                    'createMetadataResponse',
                    'MetadataService.createMetadataResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            system.debug('Create MetaData Service Response response_x' + response_x);
            return response_x.result;
        }
    

       //Exceptions
    public class MetadataServiceExamplesException extends Exception { }
    
    public static void handleSaveResults(MetadataService.SaveResult saveResult)
    {
        // Nothing to see?
        if(saveResult==null || saveResult.success)
            return;
        // Construct error message and throw an exception
        if(saveResult.errors!=null)
        {
            List<String> messages = new List<String>();
            messages.add(
                (saveResult.errors.size()==1 ? 'Error ' : 'Errors ') +
                'occured processing component ' + saveResult.fullName + '.');
            for(MetadataService.Error error : saveResult.errors)
                messages.add(
                    error.message + ' (' + error.statusCode + ').' +
                    ( error.fields!=null && error.fields.size()>0 ?
                     ' Fields ' + String.join(error.fields, ',') + '.' : '' ) );
            if(messages.size()>0)
                throw new MetadataServiceExamplesException(String.join(messages, ' '));
        }
        if(!saveResult.success)
            throw new MetadataServiceExamplesException('Request failed with no specified error.');
    }
    
}

below is my code can anyone help me where I am wrong or what I am doing wrong ??

**Comment by Soniatanwar2023** [comment]
I am having the same issue. I need to add new values to picklist field in apex. I am getting issues like variable doesn't exist: Service and Method does not exist or incorrect signature: handleSaveResults(MetadataService.SaveResult). Can anyone help me regarding this? I am even not getting the updated MetadataService.cls somewhere.
