### ISSUE TITLE
Private and public report

### ISSUE THREAD

**Issue by ajeem** [financialforcedev/apex-mdapi#125]
How to read private and public report, these report are not included under any folder.

**Comment by afawcett** [comment]
Please upvote this [idea](https://success.salesforce.com/ideaview?id=08730000000BqhrAAC) to add support for reading reports not in any folder. Depending on your requirements you may find the native [Apex Analytics API better for reading](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_analytics_report_metadata.htm), it depends if you want to update afterwards, then its better to read using the Apex Metadata API.
