### ISSUE TITLE
Error deploying to sandbox org

### ISSUE THREAD

**Issue by cdanhowell** [financialforcedev/apex-mdapi#126]
Greetings!

I very much appreciate the work you do. I am running into an issue deploying this tool using the deploy button on the GitHub page.

Thanks in advance for any insight you can provide!

Deployment Complete
Failures:
classes/MetadataDataController.cls(42,5):Dependent class is invalid and needs recompilation:
MetadataService: line 10026, column 13: Method does not exist or incorrect signature: WebServiceCallout.invoke(MetadataService.MetadataPort, MetadataService.deleteMetadata_element, Map, List)
classes/MetadataRetrieveController.cls(42,9):Dependent class is invalid and needs recompilation:
MetadataService: line 10026, column 13: Method does not exist or incorrect signature: WebServiceCallout.invoke(MetadataService.MetadataPort, MetadataService.deleteMetadata_element, Map, List)
classes/MetadataService.cls(10026,13):Method does not exist or incorrect signature: WebServiceCallout.invoke(MetadataService.MetadataPort, MetadataService.deleteMetadata_element, Map, List)
classes/MetadataServiceExamples.cls(37,9):Dependent class is invalid and needs recompilation:
MetadataService: line 10026, column 13: Method does not exist or incorrect signature: WebServiceCallout.invoke(MetadataService.MetadataPort, MetadataService.deleteMetadata_element, Map, List)
classes/MetadataServiceTest.cls(44,36):Dependent class is invalid and needs recompilation:
MetadataService: line 10026, column 13: Method does not exist or incorrect signature: WebServiceCallout.invoke(MetadataService.MetadataPort, MetadataService.deleteMetadata_element, Map, List)
classes/RemoteSiteHelperController.cls(48,47):Dependent class is invalid and needs recompilation:
MetadataService: line 10026, column 13: Method does not exist or incorrect signature: WebServiceCallout.invoke(MetadataService.MetadataPort, MetadataService.deleteMetadata_element, Map, List)
classes/RemoteSiteHelperTest.cls(10,47):Dependent class is invalid and needs recompilation:
Class.RemoteSiteHelperController.checkMetadataAPIConnection: line 48, column 47
MetadataService: line 10026, column 13: Method does not exist or incorrect signature: WebServiceCallout.invoke(MetadataService.MetadataPort, MetadataService.deleteMetadata_element, Map, List)
components/remotesitehelper.component(remotesitehelper):Apex class 'RemoteSiteHelperController' does not exist
pages/metadatadata.page(metadatadata):Apex class 'MetadataDataController' does not exist
pages/metadatadeploy.page(metadatadeploy):Apex class 'MetadataDeployController' does not exist
pages/metadataretrieve.page(metadataretrieve):Apex class 'MetadataRetrieveController' does not exist
pages/remotesitepage.page(remotesitepage):Apex class 'RemoteSiteHelperController' does not exist
classes/MetadataDeployController.cls(31,9):Dependent class is invalid and needs recompilation:
MetadataService: line 10026, column 13: Method does not exist or incorrect signature: WebServiceCallout.invoke(MetadataService.MetadataPort, MetadataService.deleteMetadata_element, Map, List)

**Comment by jdrishe** [comment]
Hello Andy,
As we spoke about on your personal website, also having some trouble with the deploy button to push apex wrapper code to my dev org.

Steps to reproduce:
I do get the prompt to select production - developer / sandbox as well as the Owner and Repository upon pressing the deploy button.
I leave it as Production - Developer and keep the Owner at financialforcedev and Repo at apex-mdapi.
I then login to my org, it processes, and then gives Oath error.

I do have mydomain turned on, if that matters.

Thanks!
-Joseph

**Comment by afawcett** [comment]
Thanks @jdrishe, i am wondering if this is the same as this issue https://github.com/afawcett/githubsfdeploy/issues/21?

**Comment by jdrishe** [comment]
@afawcett sorry, missed that issue on the specific deploy page!  I have moved the comment over to the issue.

**Comment by afawcett** [comment]
Thanks!

**Comment by afawcett** [comment]
@cdanhowell I didn't have a sandbox handy, but i did try with my DE test org and it deploys fine. I do wonder if your having an issue called "Shadowing". These means that if you had a class in your sandbox called WebServiceCallout this will override the System provided one. Can you check for this? Happy to re-open the issue to discuss further btw. 👍

**Comment by cdanhowell** [comment]
100% correct, I missed the WebServiceCallout bit. Good catch, and thanks again!
