### ISSUE TITLE
upgrade to version 36

### ISSUE THREAD

**Issue by mgaunard** [financialforcedev/apex-mdapi#127]
It would be nice to upgrade the provided MetadataService class to API version 36.

**Comment by afawcett** [comment]
Yes indeed, i'll get to it soon. What feature are you most looking forward to!?! :+1:

**Comment by mgaunard** [comment]
I'd like to experiment with certificates, though I'm not sure the metadata API covers my use case yet.

**Comment by afawcett** [comment]
Yes this is covered in the WSDL, is [this](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_certificate.htm) the one?

<img width="490" alt="mdapi-certificate" src="https://cloud.githubusercontent.com/assets/1167760/14511692/46587194-01d1-11e6-8e1b-ae47733a3264.png">

**Comment by mgaunard** [comment]
Yes.

**Comment by afawcett** [comment]
Done! It would be create if you could submit a small example of creating a certificate! 👍
