### ISSUE TITLE
NameSpace issue when trying to access VF Page : metadataretrieve

### ISSUE THREAD

**Issue by BharathV09** [financialforcedev/apex-mdapi#128]
I am trying to access VF Page : metadataretrieve and its throwing Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=
Error is in expression '{!init}' in component <apex:page> in page bharathv409:metadataretrieve: Class.bharathv409.MetadataService.MetadataPort.describeMetadata: line 10091, column 1
Class.bharathv409.MetadataRetrieveController.init: line 50, column 1
My observation is the org is having namespace and it seems to be the problem bcz i was able to get it worked in another dev org which don't have name space.

**Comment by frup42** [comment]
This is something we discovered using the Metadata API for Andy's declarative roll-up summary tool. There are a number of native security options which can cause callouts to fail when attempting to use the current user's session ID, e.g.
- Lock sessions to the IP from which they originated
- Restrict login IP ranges

These are known to cause problems for some applications and mobile devices.

Can you check if one of these settings is the key difference between your namespaced and non-namespaced org that would explain the behaviour?

**Comment by BharathV09** [comment]
Verified both settings and the settings are same in both orgs. 

Lock sessions to the IP from which they originated : Unchecked
Restrict login IP ranges : No restrictions.

However, Unable to debug the code due GACK when trying to open Class  :)

**Comment by frup42** [comment]
How odd, that is the exact same error logging we were seeing.
The Login IP Ranges setting is configured on a per-profile basis.

Is Login IP Ranges set to _"No login IP ranges specified. Users from any IP address are allowed to log in."_ for the profile of the user attempting to use the problem VF page?

And can you also confirm your org setting for "Require security tokens for API logins from callouts"?

I guess the next stages would be to look at your code or login to the org and have a poke around...

**Comment by afawcett** [comment]
@BharathV09 I'm closing this issue out. Ping us back if you want to continue to work this issue.
