### ISSUE TITLE
Fetch Metadata from another Org

### ISSUE THREAD

**Issue by ChiWuSage** [financialforcedev/apex-mdapi#129]
Just wondering if it's possible to fetch metadata from another org to main org.

**Comment by afawcett** [comment]
Yes, you just need an oAuth token for that other org.

**Comment by ChiWuSage** [comment]
Is there an example of how to achieve this?

**Comment by afawcett** [comment]
No sorry there is not. However i did find by googling 'oauth between salesforce orgs', this StackExchange [post](http://salesforce.stackexchange.com/questions/25021/how-can-i-integrate-one-sfdc-org-to-another-sfdc-using-rest-api).
