### ISSUE TITLE
Unable to Add field to layout

### ISSUE THREAD

**Issue by ChiWuSage** [financialforcedev/apex-mdapi#131]
When trying to perform addFieldToLayout getting the following error on the web service callout.

Web service callout failed: WebService returned a SOAP Fault: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1758062860-437106 (-1692580906) faultcode=sf:UNKNOWN_EXCEPTION faultactor=

Any idea would be helpful.

Thanks

**Comment by afawcett** [comment]
This is an unknown exception and needs to be reviewed by Salesforce support, more information [here](https://developer.salesforce.com/blogs/engineering/2015/02/gack.html). Meanwhile if you post your code snippet i can try and spot if there is anything obvious that might cause this. Though your best option is to raise a support case typically.

**Comment by ChiWuSage** [comment]
Got it figure it out. It more of a Salesforce server side problem then my code.
Thanks for the help anyway.
