### ISSUE TITLE
FATAL_ERROR|navpeIIll.MetadataServiceExamples.MetadataServiceExamplesException: Error occured processing component navpeIIll__Fund__c-navpeIIll__Fund Layout. Invalid field:navpeIIll__Legal_Name__c in related list:navpeIIll__Fundraising__c.navpeIIll__Fund_Name__c (FIELD_INTEGRITY_EXCEPTION).

### ISSUE THREAD

**Issue by LalitSingh** [financialforcedev/apex-mdapi#134]
With the help of below code I am trying to update layout like remove related list. After using NameSpace in my ORG, I am facing this problem, earlier I were not using NameSpace in my ORG than code was running perfectly. 

I have a Fund__c object as a Parent and Fundraising__c as a child object. In my related list Fundraising__c I added custom field Legal_Name__c as a column. If I remove this custom field, code run perfectly.

Please find the code below.

MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        
        MetadataService.Layout layout = (MetadataService.Layout)service.readMetadata('Layout',new String[] {'navpeIIll__Fund__c-navpeIIll__Fund Layout'}).getRecords()[0];
        system.debug('layout==========='+layout);                     
        List<MetadataService.RelatedListItem> lstMD= layout.relatedLists;
        system.debug('lstMD==========='+lstMD);
         
        for(integer i=0;i<lstMD.size();i++){
            MetadataService.RelatedListItem mdsR= lstMD[i];
            system.debug('lstMD==========='+mdsR);
            if(mdsR.relatedList== 'navpeIIll__Fundraising__c.navpeIIll__Fund__c'){
                layout.relatedLists.remove(i);  
                system.debug('layout====50======='+layout);
            }            
        }        
        MetadataServiceExamples.handleSaveResults(service.updateMetadata(new MetadataService.Metadata[] { layout })[0]);

**Comment by LalitSingh** [comment]
HI Andrew,

Waiting for your response.

After adding namespace in salesforce field API name has been changed with namespace. After add name space I am getting Invalid Field Name error: FIELD_INTEGRITY_EXCEPTION.

Waiting for your solution.

Thanks
Lalit

**Comment by afawcett** [comment]
As i am only wrapping the Salesforce API, sometimes problems like this are in Salesforce's hands, this feels like one of them. Are you able to grab the XML request being sent to Salesforce from the DEBUG log? Sometimes its easier to see the cause of the problem in plain XML. This can also help if you have to raise a support case, as they can reproduce the issue without having the distraction of going through this library. Let me know if you get the XML from the debug log here and i'll take a look see if anything looks odd...

**Comment by LalitSingh** [comment]
Hi Andrew,

Thanks for reply.

I also locked a case with Salesforce and waiting for their Call. Also add XML file. In After Change xml file, I removed one related list "relatedList=navpeIIll__Partnership__c.navpeII" .

**Please find the Attached XML file Before changes :**

[Layout_XML_Before_Changes_In_Layout.txt](https://github.com/financialforcedev/apex-mdapi/files/290551/Layout_XML_Before_Changes_In_Layout.txt)

**Please find the Attached XML file after changes :**

[Layout_XML_After_Changes_In_Layout.txt](https://github.com/financialforcedev/apex-mdapi/files/290546/Layout_XML_After_Changes_In_Layout.txt)

Waiting for your response.

Thanks 
Lalit

**Comment by LalitSingh** [comment]
Hi Andrew,

Did you find out any solution from my attached XML file?

Waiting for your response.

Thanks 
Lalit

**Comment by afawcett** [comment]
These are not the XML request and responses, this is not XML. You should see actual XML in your debug log? If not try running your code from Annonymous Apex window in Developer Console and checking the log output then.

**Comment by LalitSingh** [comment]
Hi Andrew,

Thanks for reply.

I think you are requiring below attached XML.
Please find the attachment and provide your feedback.

I will be highly thank full to you.

[CALLOUT_REQUEST_XML.txt](https://github.com/financialforcedev/apex-mdapi/files/294984/CALLOUT_REQUEST_XML.txt)

[CALLOUT_REQUEST2_XML.txt](https://github.com/financialforcedev/apex-mdapi/files/294985/CALLOUT_REQUEST2_XML.txt)

[CALLOUT_RESPONSE_XML.txt](https://github.com/financialforcedev/apex-mdapi/files/294986/CALLOUT_RESPONSE_XML.txt)

**Comment by afawcett** [comment]
Thanks, the CALLOUT_REQUEST2_XML.txt is still not XML. Having reviewed CALLOUT_REQUEST_XML.txt i cannot see anything odd looking. I ran it through http://www.freeformatter.com/xml-formatter.html (stripping the soap:envelope and a few other bits to get it working, it seems the XML you included was slightly corrupted formatting wise?). 

~~~~
<?xml version="1.0" encoding="UTF-8"?>
<updateMetadata>
   <metadata>
      <fullName>navpeIIll__Fund__c-navpeIIll__FundLayout</fullName>
      <customButtons>navpeIIll__Create_Drawdown</customButtons>
      <customButtons>navpeIIll__Create_Distribution</customButtons>
      <excludeButtons>Submit</excludeButtons>
      <layoutSections>
         <customLabel>true</customLabel>
         <detailHeading>true</detailHeading>
         <editHeading>true</editHeading>
         <label>FundInformation</label>
         <layoutColumns>
            <layoutItems>
               <behavior>Required</behavior>
               <field>Name</field>
            </layoutItems>
            <layoutItems>
               <behavior>Required</behavior>
               <field>navpeIIll__Fund_Type__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Required</behavior>
               <field>navpeIIll__Investment_Category__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__Vintage_Year__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>navpeIIll__Total_Capital_Called__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>navpeIIll__Total_Commitments__c</field>
            </layoutItems>
         </layoutColumns>
         <layoutColumns>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__Target_Commitments_USD_mn__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>navpeIIll__Total_Commitments_USD_mn__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>navpeIIll__Remaining_Commitments_USD_mn__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>navpeIIll__Total_Capital_Called_mn__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>navpeIIll__Total_Recallable_Capital_mn__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>navpeIIll__Total_Recallable_Capital__c</field>
            </layoutItems>
         </layoutColumns>
         <style>TwoColumnsLeftToRight</style>
      </layoutSections>
      <layoutSections>
         <customLabel>true</customLabel>
         <detailHeading>true</detailHeading>
         <editHeading>true</editHeading>
         <label>ClosingDates</label>
         <layoutColumns>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__X1st_Closing_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__X2nd_Closing_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__X3rd_Closing_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__X4th_Closing_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__X5th_Closing_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__X6th_Closing_Date__c</field>
            </layoutItems>
         </layoutColumns>
         <layoutColumns>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__Final_Closing_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__Termination_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__Dissolution_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__Step_Down_Date__c</field>
            </layoutItems>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>navpeIIll__Investment_Period_End_Date__c</field>
            </layoutItems>
         </layoutColumns>
         <style>TwoColumnsTopToBottom</style>
      </layoutSections>
      <layoutSections>
         <customLabel>true</customLabel>
         <detailHeading>true</detailHeading>
         <editHeading>false</editHeading>
         <label>Workspace</label>
         <layoutColumns>
            <layoutItems>
               <height>1140</height>
               <page>navpeIIll__PE_Fund_NothingEnabled</page>
               <showLabel>false</showLabel>
               <showScrollbars>false</showScrollbars>
               <width>100%</width>
            </layoutItems>
         </layoutColumns>
         <style>OneColumn</style>
      </layoutSections>
      <layoutSections>
         <customLabel>false</customLabel>
         <detailHeading>true</detailHeading>
         <editHeading>true</editHeading>
         <label>SystemInformation</label>
         <layoutColumns>
            <layoutItems>
               <behavior>Edit</behavior>
               <field>OwnerId</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>CreatedById</field>
            </layoutItems>
            <layoutItems>
               <behavior>Readonly</behavior>
               <field>LastModifiedById</field>
            </layoutItems>
         </layoutColumns>
         <layoutColumns />
         <style>TwoColumnsTopToBottom</style>
      </layoutSections>
      <layoutSections>
         <customLabel>false</customLabel>
         <detailHeading>true</detailHeading>
         <editHeading>false</editHeading>
         <label>CustomLinks</label>
         <layoutColumns />
         <layoutColumns />
         <layoutColumns />
         <style>CustomLinks</style>
      </layoutSections>
      <miniLayout>
         <fields>Name</fields>
         <fields>navpeIIll__Fund_Type__c</fields>
         <fields>navpeIIll__Investment_Category__c</fields>
         <fields>navpeIIll__Vintage_Year__c</fields>
         <fields>navpeIIll__Target_Commitments_USD_mn__c</fields>
         <fields>navpeIIll__Total_Commitments_USD_mn__c</fields>
         <fields>navpeIIll__Total_Capital_Called_mn__c</fields>
         <fields>navpeIIll__Total_Recallable_Capital_mn__c</fields>
      </miniLayout>
      <relatedLists>
         <customButtons>navpeIIll__Quick_Create_Fundraisings</customButtons>
         <customButtons>navpeIIll__Email_Fundraising_Contacts</customButtons>
         <fields>NAME</fields>
         <fields>navpeIIll__Legal_Name__c</fields>
         <fields>navpeIIll__Next_Step__c</fields>
         <fields>navpeIIll__Portfolio_Company__c</fields>
         <fields>navpeIIll__Probability__c</fields>
         <relatedList>navpeIIll__Fundraising__c.navpeIIll__Fund_Name__c</relatedList>
      </relatedLists>
      <relatedLists>
         <fields>NAME</fields>
         <fields>navpeIIll__Investment_Date__c</fields>
         <fields>navpeIIll__Investment_Amount__c</fields>
         <fields>navpeIIll__Portfolio_Company__c</fields>
         <relatedList>navpeIIll__Fund_Investment__c.navpeIIll__Fund_Name__c</relatedList>
      </relatedLists>
      <relatedLists>
         <fields>NAME</fields>
         <fields>navpeIIll__Capital_Amount_Formula__c</fields>
         <fields>navpeIIll__Call_Amount__c</fields>
         <fields>navpeIIll__Capital_Amount__c</fields>
         <fields>navpeIIll__Due_Date__c</fields>
         <relatedList>navpeIIll__Fund_Drawdown__c.navpeIIll__Fund_Name__c</relatedList>
      </relatedLists>
      <relatedLists>
         <fields>NAME</fields>
         <fields>navpeIIll__Distribution_Date__c</fields>
         <fields>CREATED_DATE</fields>
         <fields>navpeIIll__Other_Proceeds__c</fields>
         <relatedList>navpeIIll__Fund_Distribution__c.navpeIIll__Fund_Name__c</relatedList>
      </relatedLists>
      <showEmailCheckbox>false</showEmailCheckbox>
      <showHighlightsPanel>false</showHighlightsPanel>
      <showInteractionLogPanel>false</showInteractionLogPanel>
      <showRunAssignmentRulesCheckbox>false</showRunAssignmentRulesCheckbox>
      <showSubmitAndAttachButton>false</showSubmitAndAttachButton>
      <summaryLayout>
         <masterLabel>00h36000001jd1N</masterLabel>
         <sizeX>4</sizeX>
         <sizeY>0</sizeY>
         <summaryLayoutStyle>Default</summaryLayoutStyle>
      </summaryLayout>
   </metadata>
</updateMetadata>
~~~~

I've been reviewing this and searching the internet a bit for this error, i found your cross post [here](http://salesforce.stackexchange.com/questions/123872/getting-error-while-updating-related-list-page-layout-using-metadata-service-api) and another possibly related comment in this post [here](http://salesforce.stackexchange.com/questions/25139/change-page-layout-of-objects-using-meta-data-api-in-apex). 

Some thoughts...
- Does it work if you don't modify the layout at all, just do a read of it, then immediately update it? 
- Also regarding your case. I do recommend that you generalise your request to Salesforce support by using the curl command and passing them directly the XML you extracted from the debug logs. This way they will not become distracted by the Apex Wrapper around this API.
- Also another way to reproduce the issue is with an IDE, MavensMate or Force.com IDE. Since you have the XML for the layout above, you could download the layout into your IDE as XML. Paste the above or just make your edit manually and attempt to save it. This in fact might be an even easier way to reproduce the problem for Salesforce.

Sorry i cannot be of more direct help, i suspect this might be a bug in the Salesforce end tbh. Hopefully the above will help move you and Salesforce further down the road to finding the root cause.

**Comment by afawcett** [comment]
@LalitSingh let me know if the above helped and/or if you need more discussion. I'll close out this issue for now, but your still more than welcome to post back on it any time and we can re-open. Thanks!

**Comment by LalitSingh** [comment]
Hi Andrew,

I found a solution or work around. I thought i should share my this workaround.
As discussed with Salesforce, the issue is from their end. Salesforce will resolve this issue in new release.

So till the time i found on work around for this problem.


**Earlier code:** 

	MetadataService.Layout layout = (MetadataService.Layout)service.readMetadata('Layout',new String[] {'navpeIIll__Fund__c-navpeIIll__Fund Layout'}).getRecords()[0];
                        
    List<MetadataService.RelatedListItem> lstMD= layout.relatedLists;
     

    for(integer i=0;i<lstMD.size();i++){
        MetadataService.RelatedListItem mdsR= lstMD[i];
         
        if(mdsR.relatedList== 'navpeIIll__Fundraising__c.navpeIIll__Fund__c'){
            layout.relatedLists.remove(i);               
        }            
    }        
    MetadataServiceExamples.handleSaveResults(service.updateMetadata(new MetadataService.Metadata[] { layout })[0]);  


**Code After Work Around:** As we know that we are facing a problem when namespace is attached with field name in request.
						In the workaround we are removing name space before submitting request to server.

	MetadataService.Layout layout = (MetadataService.Layout)service.readMetadata('Layout',new String[] {'navpeIIll__Fund__c-navpeIIll__Fund Layout'}).getRecords()[0];
    List<MetadataService.RelatedListItem> lstMD= layout.relatedLists; 
    for(integer i=0;i<lstMD.size();i++){
        MetadataService.RelatedListItem mdsR= lstMD[i]; 
	
		**/***Work around start****/**
		List<String> strlist = new List<String>();
		for(String str :lstMD[i].fields){
			strlist.add(str.replace(strNameSpace,''));
		}
		lstMD[i].fields =  strlist;      
		**/***Work around end****/**
		
        if(mdsR.relatedList== 'navpeIIll__Fundraising__c.navpeIIll__Fund__c'){
            layout.relatedLists.remove(i);  
        }            
    }        
    MetadataServiceExamples.handleSaveResults(service.updateMetadata(new MetadataService.Metadata[] { layout })[0]);

**Comment by afawcett** [comment]
Thanks for sharing @LalitSingh very much appreciated. Can you ask Salesforce for a bug reference number or ideally a link to the known issue, either of these will help us track and support the fixing of the issue. Meanwhile thanks again for sharing the workaround!

**Comment by Blackbaud-VincentLee** [comment]
This is affecting us too - a Salesforce bug ID would be helpful to us as well
