### ISSUE TITLE
change object Permission

### ISSUE THREAD

**Issue by dwlkumar** [financialforcedev/apex-mdapi#135]
I want to change custom object Permission.
 
This is my code but not working even not giving any error.

> MetadataService.MetadataPort service = createService();
> MetadataService.Profile admin = new MetadataService.Profile();
> admin.fullName = ‘My Standard User’;
> admin.custom = true;
> MetadataService.ProfileObjectPermissions objPerm = new MetadataService.ProfileObjectPermissions();
> objPerm.object_x=’Test__c’;
> objPerm.modifyAllRecords = false;
> objPerm.allowDelete = false;
> admin.objectPermissions = new MetadataService.ProfileObjectPermissions[] {objPerm} ;
> List results = service.updateMetadata(new MetadataService.Metadata[] { admin });
> MetadataService.handleSaveResults(results[0]);

can you help me.

**Comment by dwlkumar** [comment]
I have found the solution:

```
MetadataService.MetadataPort service = createService();
        MetadataService.Profile admin = new MetadataService.Profile();
        admin.fullName = 'My Standard User';
        admin.custom = true;
        MetadataService.ProfileObjectPermissions objPerm = new MetadataService.ProfileObjectPermissions();
        objPerm.object_x='Test__c';
        objPerm.allowCreate = false;
        objPerm.allowDelete = false;
        objPerm.allowEdit = false;
        objPerm.allowRead = false;
        objPerm.modifyAllRecords = false;
        objPerm.viewAllRecords = false;
        admin.objectPermissions = new MetadataService.ProfileObjectPermissions[] {objPerm} ;
            
        //System.assert(false,admin);
        List<MetadataService.SaveResult> results = 
            service.updateMetadata(
                new MetadataService.Metadata[] { admin });
        handleSaveResults(results[0]);
```
Thanks

**Comment by afawcett** [comment]
Excellent thanks for sharing! 👍
