### ISSUE TITLE
Got this error after installing the package from github (yesterday) and then refreshing a sandbox

### ISSUE THREAD

**Issue by guylgardner** [financialforcedev/apex-mdapi#136]
Two issues that are probably related:

1. In the sandbox if I create code:
-----
MetadataService.MetadataPort service = createService();
-----
I get this error: Method does not exist or incorrect signature: createService() at line ...

2. I went to look at MetadataService class in the sandbox by going to Develop->Apex Classes I find the MetadataService class (The one without a namespace prefix) and click on it to view it and I get this error:
------
An internal server error has occurred
An error has occurred while processing your request. The salesforce.com support team has been notified of the problem. If you believe you have additional information that may be of help in reproducing or correcting the error, please contact Salesforce Support. Please indicate the URL of the page you were requesting, any error id shown on this page as well as any other related information. We apologize for the inconvenience. 

Thank you again for your patience and assistance. And thanks for using salesforce.com! 

Error ID: 1437043031-103055 (-149558205)
-----

So maybe the package got corrupted when installed? Or there is a problem with the package:?

**Comment by afawcett** [comment]
RE: 1, thats because you don't have the 'createService' defined most likely. Copy a version of it from the MetadataServiceExamples class.

RE: 2, yeah i've seen this, i think the classic UI way of viewing Apex code doesn't tolerate classes this large. Use either the Developer Console or an IDE, like MavensMate, Force.com IDE or Cloud9.

**Comment by guylgardner** [comment]
1. I loaded up the MetadataServiceExamples class in the developer console and don't see createService defined in it. I see createService being referenced as though it local the method is not there. Seems very wierd.

2. I am able to open MetadataService class in developer console. So that part works. It looks complete.

So issue #1 is still open. Ideas?

BTW. This again is a great resource. I tend to build things and usually have to roll my open APIs to get to internal things I need from the system. This looks like it will make this much easier for me to do.

**Comment by afawcett** [comment]
Excellent! Glad your sorted. The method is defined [here](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataServiceExamples.cls#L1525).
