### ISSUE TITLE
Assignment Rule Creation

### ISSUE THREAD

**Issue by rpandey83** [financialforcedev/apex-mdapi#139]
Hello,

Using MetaData API, I am trying to create Lead Assignment Rule. Using DataLoader i uploaded my rules in a custom object and on click of button from record detail page. I am invoking Apex Batch which is creating meta-data for **MetadataService.AssignmentRule** and assigning all the rules and in **FINISH** method I am saving my record.

//Creating Assignment Rule
_List<MetadataService.SaveResult> results 
                                         = service.createMetadata(new MetadataService.Metadata[] { assignmentRule });_

But when I have more than 10 records i am getting **Read Timeout** exception from API.
I already set timeout to max 120000.

Please help me how i can resolve this issue.  Any help will be appreciated.

**Comment by afawcett** [comment]
This is a platform restriction i am afraid. My suggest would be either use the deploy operation (you will need to rearchitect to use VF page to build the zip) or reduce the chunk size in your batch apex job (see parameter on the executeBatch method).

**Comment by afawcett** [comment]
BTW, sorry for not getting back sooner.

**Comment by afawcett** [comment]
@rpandey83 please comment further if you are still having issues here.
