### ISSUE TITLE
Adding related list into page layout getting callout exception

### ISSUE THREAD

**Issue by Lanceshi2** [financialforcedev/apex-mdapi#140]
This is most probably not an issue but requesting more information. I wrote the below code pretty much following the sample code in MetadataServiceExamples.cls. However, it doesn't have samples about related list adding so I am not very sure whether what I have done is correct or not. Below is my code: 

```
    public static void addRelatedList()
    {
        MetadataService.MetadataPort service = createService();

        MetadataService.Layout layout =
            (MetadataService.Layout) service.readMetadata('Layout',
                new String[] { 'Contact-Contact Layout' }).getRecords()[0];

        if(layout.relatedLists == null) {
            layout.relatedLists = new List<MetadataService.RelatedListItem>();
        }

        MetadataService.RelatedListItem new_related_list = new MetadataService.RelatedListItem();
        new_related_list.relatedList = 'Contact_List_Junction__c';
        new_related_list.customButtons = new List<String> {'Add_To_List'};
        new_related_list.fields = new List<String> {'Name', 'List__c'};
        layout.relatedLists.add(new_related_list);

        handleSaveResults(
            service.updateMetadata(
                new MetadataService.Metadata[] { layout })[0]);
    }
```

handleSaveResults() and createService are the same ones copied from MetadataServiceExamples.cls. And I am getting the below exception: 

> Line: 10822, Column: 1
> System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this 
> ErrorId if you contact support: 1076527423-317733 (-258760784) faultcode=sf:UNKNOWN_EXCEPTION faultactor=

This exception really tells me nothing about what is wrong. Is there some more clarification on what should I put into each attribute of MetadataService.RelatedListItem?

**Comment by Lanceshi2** [comment]
Update: 
I debugged into this code and for the result of layout, relatedlists=null. And for Contact - Contact layout, it definitely has some related lists. So I guess here the code is wrong?

**Comment by Lanceshi2** [comment]
And below are the soap requests sent: 

Retrieving: 
```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <env:Header>
        <SessionHeader xmlns="http://soap.sforce.com/2006/04/metadata">
            <sessionId>00D28000001OSKz!AQ4AQOWyaF1WUNz2AZPtMY.APYbLhNRZiksgSv3FAIwfRC6cmN16s9wPiPTMU3orJ9hMtbqCcc_qmmu2tY7JCBdCb8RqDmWN</sessionId>
        </SessionHeader>
    </env:Header>
    <env:Body>
        <readMetadata xmlns="http://soap.sforce.com/2006/04/metadata">
            <type>Layout</type>
            <fullNames>Contact-Contact Layout</fullNames>
        </readMetadata>
    </env:Body>
</env:Envelope>
```

The one which gets the error: 
```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <env:Header>
        <SessionHeader xmlns="http://soap.sforce.com/2006/04/metadata">
            <sessionId>00D28000001OSKz!AQ4AQOWyaF1WUNz2AZPtMY.APYbLhNRZiksgSv3FAIwfRC6cmN16s9wPiPTMU3orJ9hMtbqCcc_qmmu2tY7JCBdCb8RqDmWN</sessionId>
        </SessionHeader>
    </env:Header>
    <env:Body>
        <updateMetadata xmlns="http://soap.sforce.com/2006/04/metadata">
            <metadata xsi:type="Layout">
                <relatedLists>
                    <customButtons>Add_To_List</customButtons>
                    <fields>Name</fields>
                    <fields>List__c</fields>
                    <relatedList>Contact_List_Junction__c.Contact__c</relatedList>
                </relatedLists>
            </metadata>
        </updateMetadata>
    </env:Body>
</env:Envelope>
```

**Comment by Lanceshi2** [comment]
With below code, the response will be nil in the content: 
```
MetadataService.MetadataPort service = Util.createService();

MetadataService.Layout layout =
    (MetadataService.Layout) service.readMetadata('Layout',
                                                  new String[] { 'Contact-Contact Layout' }).getRecords()[0];

System.debug(layout);
```

Util.createService(): 
```
    public static MetadataService.MetadataPort createService()
    {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        return service;
    }
```

Please note I did not deploy the whole project into Salesforce. Instead, I only copied MetadataService.cls and MetadataServiceTest.cls code. Is there any issue with that?

**Comment by Lanceshi2** [comment]
A little bit more info. The code works for my newly created salesforce org but doesn't work for my current dev org which is developing a managed package. So pretty much everything is under a name prefix. Is there any prefix I need to add here?

**Comment by afawcett** [comment]
Firstly sorry for the delay, i have been moving home. Also this is a great post, lots of detail, example of the XML request/response, nice. So yes, i think your are almost there with your assertion it is namespace related. My best advice is to make the change manually in your namespace or then retrieve the layout and see where Salesforce has qualified things.

**Comment by Lanceshi2** [comment]
Thank you for the reply, Andrew. I have figured out already and it was caused by namespace issue. I will close the issue now.
