### ISSUE TITLE
Differentiate missing readResults 

### ISSUE THREAD

**Issue by NicholasAStuart** [financialforcedev/apex-mdapi#142]
If i do a readMetadata() with a fullname that doesn't exist in my organization, I get back an "empty" object instead of an empty records list. This makes verification of objects difficult.

**Comment by atulrajguru9** [comment]
I am not sure if should classify it as bug.

**Comment by NicholasAStuart** [comment]
@atulrajguru9 You might be right. I thought this would be okay to write in, but I'm assuming this project tries to be as hands-off with the XML parsing?

**Comment by afawcett** [comment]
@atulrajguru9  and @NicholasAStuart you are both correct, it is not stictkly a  bug in the wrapper, just the fact that the readMetadata API from what i assume is designed a bit like a SOQL query, if your criteria (you can list more full names than just one) does not match the query returns an empty list, but no error. You can wrap your response handling utility functions (like the ones in the sample cls file).
