### ISSUE TITLE
Update a Custom Permission in Profile

### ISSUE THREAD

**Issue by jmam6392** [financialforcedev/apex-mdapi#143]
I am trying to enable a Custom Permission in a Profile but I am not getting any response. I get no error but the Custom Permission is not enabled in the Profile.

```
public void assignPermissionSetToProfile(String pCustomPermission, String pProfile){

    MetadataService.Profile profile = (MetadataService.Profile) service.readMetadata('Profile', new String[] { pProfile }).getRecords()[0];

        MetadataService.ProfileCustomPermissions permission = new MetadataService.ProfileCustomPermissions();
        permission.enabled = true;
        permission.name = pCustomPermission;
        MetadataService.ProfileCustomPermissions[] permissions = new MetadataService.ProfileCustomPermissions[]{permission};
        profile.customPermissions = permissions;
        profile.custom = true;
        service.upsertMetadata(new MetadataService.Metadata[] { profile });

}
```

I am calling the function as engine.assignPermissionSetToProfile('Permission_2', 'quepasa');

The Custom Permission is already created inside the ORG, I just want to enable it for that profile.

![profile](https://cloud.githubusercontent.com/assets/22202488/18525932/e94b24c6-7abe-11e6-8469-46acfbacd843.png)

Thanks in advance.

**Comment by afawcett** [comment]
You need to handle errors in your code, the wrapper will not parse the response and throw exceptions for you. Take a look at the MetadataServiceExamples.cls at the bottom there is some utility methods to handle responses from the CRUD methods like the one your using. You can also run your code from execute annonymous and see in the debug log the XML request and responses used for more information on what is being returned.

**Comment by afawcett** [comment]
@jmam6392 please comment further if you are still having issues here.
