### ISSUE TITLE
TEST CLASS FOR METADATARETRIEVE CONTROLLER

### ISSUE THREAD

**Issue by anveshch** [financialforcedev/apex-mdapi#145]
METADATARETRIEVE controller doesn't had test class, which is crucial for us now.
Please upload the test class for METADATARETRIEVE CONTROLLER.

**Comment by afawcett** [comment]
Only the MetadataService class has coverage, other classes like MetadataRetrieveController and MetadataServiceExamples are included only for reference. If you want to use these in produciton you must provide your own test coverage. If you are looking for an example of testing a controller like this look [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupControllerTest.cls#L271). You should also study the A[pex Developers Guide on testing HTTP callouts](https://www.google.com/#q=Testing+HTTP+Callouts+in+Apex).

**Comment by afawcett** [comment]
BTW, sorry for the delay in responding, i have been moving home and community time has been impacted.
