### ISSUE TITLE
Error with createCustomSite() example

### ISSUE THREAD

**Issue by pbergner** [financialforcedev/apex-mdapi#146]
Receiving the following error running `MetadatServiceExamples.createCustomSite()` in a dev sbx running Winter 16:

`11:07:25:549 FATAL_ERROR System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: '' is not valid for type xsd:boolean, should be '0', '1', 'true' or 'false' faultcode=soapenv:Client faultactor=`

`11:07:25:000 FATAL_ERROR Class.MetadataService.MetadataPort.createMetadata: line 10992, column 1`

**Comment by afawcett** [comment]
Ok i debugged this, though i encountered a further error around not having the correct admin user, i did reproduce your error above and fix it, see latest MetadataServiceExamples class in the repo.

For the record this is what i did...
1. Ran the sample in Developer Console Execute Annonymous
2. Reviewed the debug log for the XML request and response
3. Copied the XML request to xmlprettyprint.com to get a better look (see below)
4. Noticed that one of the boolean elements in the request had no content, see requireHttps below.
5. Noticed that the Apex member related to that element was not set (null)
6. Set it to a value and fixed the issue customSite.requireHttps = true;

~~~
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<env:Header>
    <SessionHeader xmlns="http://soap.sforce.com/2006/04/metadata">
    <sessionId>00DG0000000BxVh!ARgAQPCMOvtTYy9mwNNZ9vtCOzxIFwOKSe8jqwglTp18iVAUYaHLjV9pR5WOZ27QJ5EXRFDy.cuznKt7vboZy8Ox5ZMa7BOP</sessionId>
</SessionHeader>
</env:Header>
<env:Body>
    <createMetadata xmlns="http://soap.sforce.com/2006/04/metadata">
    <metadata xsi:type="CustomSite">
        <fullName>MyCustomSite</fullName>
        <active>true</active>
        <allowHomePage>true</allowHomePage>
        <allowStandardIdeasPages>true</allowStandardIdeasPages>
        <allowStandardLookups>true</allowStandardLookups>
        <allowStandardSearch>true</allowStandardSearch>
        <authorizationRequiredPage>Unauthorized</authorizationRequiredPage>
        <bandwidthExceededPage>BandwidthExceeded</bandwidthExceededPage>
        <changePasswordPage>ChangePassword</changePasswordPage>
        <clickjackProtectionLevel>AllowAllFraming</clickjackProtectionLevel>
        <fileNotFoundPage>FileNotFound</fileNotFoundPage>
        <genericErrorPage>Exception</genericErrorPage>
        <inMaintenancePage>InMaintenance</inMaintenancePage>
        <indexPage>UnderConstruction</indexPage>
        <masterLabel>customSite</masterLabel>
        <requireHttps/>
        <requireInsecurePortalAccess>false</requireInsecurePortalAccess>
        <siteAdmin>admin@mysiteorg.com</siteAdmin>
        <siteTemplate>SiteTemplate</siteTemplate>
        <siteType>Visualforce</siteType>
    </metadata>
</createMetadata>
</env:Body>
</env:Envelope>

~~~

**Comment by petethurston** [comment]
@afawcett I'm having the same issue while upserting certain CustomObjects in certain orgs (not all). Can you give me a couple pointers on how to inspect the XML that's going out on the upsertMetadata call? I'm sure I'm just missing something basic.

**Comment by afawcett** [comment]
@petethurston sure, just check my comment above for steps on seeing the XML. 👍

**Comment by petethurston** [comment]
@afawcett haha - thanks, I should've come back and closed the loop afterward. It took one of my coworkers pointing out that all of that is automatically logged - I was trying to figure out how to system.debug it, then doing my usual "debug only checkbox" dance and not seeing it. Thanks again for all your work on this library - it's super helpful!

**Comment by afawcett** [comment]
Thanks @petethurston , most welcome! 👍
