### ISSUE TITLE
How To get Picklist Value according to record type for Lead/Opportunity/Case?

### ISSUE THREAD

**Issue by rajendrarathore** [financialforcedev/apex-mdapi#149]
That code is working fine for custom object and standard object except  : Lead, Opportunity and case object.
MetadataService.RecordType recordType = (MetadataService.RecordType) service.readMetadata(
   'RecordType', new String[] { 'Account.Record_Type_A' }
).getRecords()[0];

for ( MetadataService.RecordTypePicklistValue rpk : recordType.picklistValues ) {
    if ( 'YourPicklistFieldName__c' == rpk.picklist ) {
        for ( MetadataService.PicklistValue pk : rpk.values ) {
            System.debug( pk.fullName ); // value
        }
    }
}
Because in case of Lead and Opportunity object Lead Status and Opportunity Stage picklist values are controller by Sales Process.
And in case of Case status value are controlled using Support Process.
So when i am using the above code for lead status then Record Type result not return in Lead Status field in response for picklist values.

So is there any way to get picklist values according to Sales Process or Support process?

Thanks,
Rajendra

**Comment by afawcett** [comment]
Yeah done a bit of looking on this for you, seems like Sales and Support processes are not supported in the Metadata API, see [here](https://developer.salesforce.com/forums/?id=906F00000008mKzIAI) and [here](http://salesforce.stackexchange.com/questions/120515/get-opportunity-stages-for-specific-sales-process) for others that also appear to be asking. The link to the Idea Exchange seems broken, if you want to raise an idea, happy to support for you. 👍
