### ISSUE TITLE
Metadata Browser is empty/blank

### ISSUE THREAD

**Issue by jayeshw** [financialforcedev/apex-mdapi#150]
Hi Andrew,

First of all thank you for such an amazing post. I am implementing this in my Dev org, everything seems to be working but when I open the "Metadata Browser" tab the container is blank, attaching the screenshot for reference.

Please let me know the possible causes for the same.
![image](https://cloud.githubusercontent.com/assets/10256100/20233270/5cf59700-a82b-11e6-995a-1eb374ad4fa3.png)

**Comment by afawcett** [comment]
I think this is usually caused by not having the Remote Site setting setup, can you check that? Also anything in your debug logs?

**Comment by afawcett** [comment]
BTW, sorry for the delay, i have been moving house.

**Comment by jayeshw** [comment]
Thank you for the response, really helpful post.

I don't know but it automatically started working the next time I logged in
to the org.

Thank you.
Jayesh

**Comment by afawcett** [comment]
np
