### ISSUE TITLE
System.CalloutException

### ISSUE THREAD

**Issue by Lavakusareddy** [financialforcedev/apex-mdapi#151]
Hi Andy,
We are getting the following exception while querying the report folder permissions.

**System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: null: type and fullNames must be specified for items to read faultcode=sf:UNKNOWN_EXCEPTION faultactor=**

**Comment by afawcett** [comment]
Can you share a small peace of sample code?

**Comment by afawcett** [comment]
@Lavakusareddy please comment further if you are still having issues here.
