### ISSUE TITLE
Show/Hide section based on MutiSelect Picklist Selection

### ISSUE THREAD

**Issue by yuvrajdeveloper** [financialforcedev/apex-mdapi#154]
Hi Andrew,
I need to show display the pageblocksection based on multiselect picklist chosen.
Say for the example, I have the multipicklist field in contact object, where the values are one, two, three.
Whenever i choose "One" Option corresponding page block must be showned.

```
<apex:page standardController="Contact" showHeader="false">
    <apex:pageBlock >
        <apex:pageBlockSection >
            <apex:inputField value="{!contact.Choose_Number__c}">
                <apex:actionSupport event="onchange" reRender="ppc" />
            </apex:inputField>
        </apex:pageBlockSection>
        <apex:pageBlockSection title="PPC Test" id="ppc" rendered="{!contact.Choose_Number__c == 'PPC'}">
        </apex:pageBlockSection>
    </apex:pageBlock>
    </apex:form>
</apex:page>
```
Could you help me to achieve this?

**Comment by afawcett** [comment]
Hi @yuvrajdeveloper this is place to discussed Apex Metadata API issues, not general Visualforce questions. At first glance however your code looks good. I wonder if its a Visualforce bug? What behaviour are you seeing?

**Comment by yuvrajdeveloper** [comment]
Hi Andrew,
Sorry for posting this question in this section. Whenever I move the picklist value from Available to Chosen.   Relevant page block section is not shown here. I want to show them in VF Page.

**Comment by afawcett** [comment]
Try re-rendering the outer block, the one on line 2.

**Comment by yuvrajdeveloper** [comment]
Thanks, Andrew. It's worked now perfectly,
