### ISSUE TITLE
Using the MetadataServiceExamples.updateFieldLevelSecurity

### ISSUE THREAD

**Issue by dspencerr** [financialforcedev/apex-mdapi#156]
Hi, trying to get FieldLevelSecurity updated via apex.  Stumbled across a couple post with you in them, and came back to your repository.  Basically tried to use the out of the box MetadataServiceExamples.updateFieldLevelSecurity.   I got this exception immediately. 

Error on line 10822, column 1: System.CalloutException: IO Exception: Unauthorized endpoint, please check Setup->Security->Remote site settings. endpoint = https://na30.salesforce.com/services/Soap/m/37.0

Been getting into Apex recently so comfort level is still growing.  Looked through your code on 10822 and realize you are making a call using WebServiceCallout.invoke to actually update the metadata object.  This was a little weird to me. Is there no direct "save" or "update" to metadata via apex?  Thanks in advance.

**Comment by afawcett** [comment]
Correct, @dspencerr there is "currently" no direct Apex API for this, so this is actually a native Apex "wrapper" around the SOAP API variant of it. Hence the need for the Remote Site. Salesforce's PM for this area recently shared "safe harbour" that native Apex support is under development, but no news as yet on when it will be released. Anyway its a start to a more direct approach you thought this was.
