### ISSUE TITLE
Advice on inserting SOAP Token/Client ID into soap header.

### ISSUE THREAD

**Issue by PankhuriAstrea** [financialforcedev/apex-mdapi#158]
Hi All,

I am using this class for one of my apps on appexchange. But the app is not working in Professional edition but rather in all editions as professional does not support API token. I did generated a case in support and they have given me a SOAP Token/Client Id to use. This token if appended in SOAP header will allow the users to access the app in Professional org as well. Token is: '**Abc/Dtest/**' and this is the support link: http://wiki.developerforce.com/page/How_to_use_clientid 

But can someone tell me how to append this Client Id in the present MetadataService class in SOAP header and not the java or C# code like given in support link?

**Comment by BoonPlus** [comment]
@PankhuriAstrea, Have you found a resolution? If the answer is Yes, could you share it with the rest of us?

**Comment by afawcett** [comment]
I suspect you populate the [CallOptions member](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataService.cls#L11305).
