### ISSUE TITLE
Could not create more than 100 custom fields.

### ISSUE THREAD

**Issue by avinash7891** [financialforcedev/apex-mdapi#159]
Hello
I have started a project to create custom fields in bulk(200) in one go. Also I need to update the visibility of these fields to All profiles or only to Admin, I try to keep the configurations of the custom fields like Label, Api name, datatype, etc in object then using for loop i create the fields but when i update the fields visibility the api timeout exception is thrown. My question is Is there any way to make the newly created field visible to all profiles (Like visible=true something) if there is any attribute that would help to make the field visible to all profiles it would be great. Also i want to add the fields to page layouts but I cannot get layout names of any object(Help here). Please provide help in apex coding only.

Thanks.

**Comment by afawcett** [comment]
My advice. Do not use Profiles, create Permission Sets and assign them. You do not need to use Apex MD API to create Permission Sets you can use native DML for this. Take a look at the [docs](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_permissionset.htm) for this object (scroll to the bottom for an ERD diagram).

**Comment by avinash7891** [comment]
Thanks @afawcett for suggestion!
