### ISSUE TITLE
Could not read metadata for the Goal Object

### ISSUE THREAD

**Issue by BourhiMaryem** [financialforcedev/apex-mdapi#160]
Hello,

I'm trying to read the workflow rules of a specific object but I keep getting an unknown exception, this only happens for the goal object.

do you have any idea, why is this happening?

thanks

**Comment by afawcett** [comment]
Please share the exception. Also run your code in Developer Console's Execute Annonymous window. This way the XML response from the MD SOAP API (this library wraps) will be shown. Please also share this.

**Comment by afawcett** [comment]
@BourhiMaryem please comment further if you are still having issues here.
