### ISSUE TITLE
Inactive Flows cause callout exception

### ISSUE THREAD

**Issue by c4tch** [financialforcedev/apex-mdapi#161]
Hi!
I'm getting a list of flows from the org, then fetching the meta for each flow so that I can update them.

If the flows in the readMetadata request are all Active then it works. If one or all in the list are Inactive then an exception is thrown. This is obviously a problem as I can't tell which flow is active or not in the first query retrieving my list of flows (not shown here as that is working).

Result When Active (inactive is underneath, note the metadata fullname changes with a version number in the inactive example):
15:17:43.737 (853960529)|USER_DEBUG|[9325]|DEBUG|readMetadata_element:[apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), field_order_type_info=(type_x, fullNames), fullNames=(Sample_loc), fullNames_type_info=(fullNames, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), type_x=Flow, type_x_type_info=(type, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false)] - {response_x=null} - https://maevan-dev-ed.my.salesforce.com/services/Soap/m/32.0 - Flow

15:17:43.737 (940309286)|USER_DEBUG|[33]|DEBUG|Flows: (Flow:[Metadata.apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), Metadata.field_order_type_info=(fullName), Metadata.fullName=null, Metadata.fullName_type_info=(fullName, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), actionCalls=null, actionCalls_type_info=(actionCalls, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), apexPluginCalls=null, apexPluginCalls_type_info=(ap.... My Flow Data :) ... )])

Result when Inactive:
15:20:28.505 (805712202)|USER_DEBUG|[9325]|DEBUG|readMetadata_element:[apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), field_order_type_info=(type_x, fullNames), fullNames=(Sample_loc-1), fullNames_type_info=(fullNames, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), type_x=Flow, type_x_type_info=(type, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false)] - {response_x=null} - https://maevan-dev-ed.my.salesforce.com/services/Soap/m/32.0 - Flow

15:20:28.505 (898978816)|EXCEPTION_THROWN|[9326]|System.CalloutException: Web service callout failed: Unable to parse callout response. Apex type not found for element name

**Comment by c4tch** [comment]
I've been working on this one a little more, it seems if I request using the version number (the full name appended by the version number) the callout fails. But if I remove the version, the API will return to me the current active version by default.

Now this is actually OK, I think I can code around this, but is it possible to get an inactive flow or one of a specific version?

**Comment by c4tch** [comment]
Example, with four versions in SF I have these four full names returned from the ListMetadataQuery:

`MetadataService.ListMetadataQuery query = new MetadataService.ListMetadataQuery();
			query.type_x = flowType;
			queries.add(query);
			MetadataService.FileProperties[] fileProperties = metadataConnection.listMetadata(queries, asOfVersion);`

Returns: 
> Sampleflow-1
> Sampleflow-2
> Sampleflow-3
> Sampleflow-4

If I request one of the above (lets assume I guess the active flow correctly) I follow the documentation using the **full name** to request the flow, ex. 
`MetadataService.Flow[] f = (MetadataService.Flow[]) metadataConnection.readMetadata('Flow',new String[]{'**Sampleflow-4**'}; ).getRecords();`

I will get 
15:20:28.505 (898978816)|EXCEPTION_THROWN|[9326]|System.CalloutException: Web service callout failed: Unable to parse callout response. Apex type not found for element name

However if I strip the "-4" from the full name, the system automatically identified the current active flow and returns me the meta data successfully. ex. 
`MetadataService.Flow[] f = (MetadataService.Flow[]) metadataConnection.readMetadata('Flow',new String[]{'**Sampleflow**'}; ).getRecords();`

(note I've put **s around the name strings for emphasis, it's not a syntax error)

I now get my flow data:
_Flow:[Metadata.apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), Metadata.field_order_type_info=(fullName), Metadata.fullName=null, Metadata.fullName_type_info=(fullName, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false),..._

So..
1) Am I correct that I **should** query using the true "full name" (If I'm supposed to only use the truncated name, I can strip the -X extension from the full name but this feels to be a hack (well, it is), so what should I use to get the current active version without manipulating the returned values?)
2) Is it possible to be able to query for a specific version, inactive or not?

**Comment by afawcett** [comment]
When you get "Web service callout failed: Unable to parse callout response. Apex type not found for element name", can you run your code in Developer Console execute annonymous? 

Then the debug log will include the actual XML response (as apposed to the debug output your getting, which is hard to see the actual response). It would be useful to see this, then it might be easier to see why the XML to Apex un-marshalling might be mismatching (which is what this error means). So this error might not relate to the full name you used, but more to the content of that specific Flow version. So if you can provide actual XML responses from the API that would help trouble shoot this issue better for sure (tip: copy paste XML from the log and use an site to make the XML pretty to paste in to this issue). 

Regarding the strangeness around the Flow names, it seems the [docs](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_visual_workflow.htm) do not indicate that the version suffix can be removed. So it sounds like you have come across an undocumented feature to get the active one. Anyway as i said above, if you can provide XML output for your original tests in your first comment i think that might help us see things more clearly.

**Comment by afawcett** [comment]
@c4tch please comment further if you are still having issues here.
