### ISSUE TITLE
Flows readMetadata returns empty objects

### ISSUE THREAD

**Issue by c4tch** [financialforcedev/apex-mdapi#162]
When I call a read operation of a flow I get an empty object.

Calling code (assume **createService** returns a correctly connected metadata connection:
```
MetadataService.MetadataPort service = c4_localiseFlow.createService();
String[] flowFullNames = new String []{'Sample_loc'};
MetadataService.Flow[] flows = (MetadataService.Flow[]) service.readMetadata('Flow', new List<String>(flowFullNames)).getRecords();
System.debug(flows[0]);
```

Returns (from sys debug) - note that basically all values of meaning are null for example fullname, and screens are null
> 14:33:00.494 (573074704)|USER_DEBUG|[4]|DEBUG|Flow:[Metadata.apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), Metadata.field_order_type_info=(fullName), Metadata.fullName=null, Metadata.fullName_type_info=(fullName, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), actionCalls=null, actionCalls_type_info=(actionCalls, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), apexPluginCalls=null, apexPluginCalls_type_info=(apexPluginCalls, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), assignments=null, assignments_type_info=(assignments, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), choices=null, choices_type_info=(choices, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), constants=null, constants_type_info=(constants, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), decisions=null, decisions_type_info=(decisions, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), description=null, description_type_info=(description, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), dynamicChoiceSets=null, dynamicChoiceSets_type_info=(dynamicChoiceSets, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), field_order_type_info=(fullName, actionCalls, apexPluginCalls, assignments, choices, constants, decisions, description, dynamicChoiceSets, formulas, ...), formulas=null, formulas_type_info=(formulas, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), fullName=null, fullName_type_info=(fullName, http://www.w3.org/2001/XMLSchema, string, 0, 1, false), label=null, label_type_info=(label, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false), loops=null, loops_type_info=(loops, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), processMetadataValues=null, processMetadataValues_type_info=(processMetadataValues, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), processType=null, processType_type_info=(processType, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), recordCreates=null, recordCreates_type_info=(recordCreates, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), recordDeletes=null, recordDeletes_type_info=(recordDeletes, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), recordLookups=null, recordLookups_type_info=(recordLookups, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), recordUpdates=null, recordUpdates_type_info=(recordUpdates, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), screens=null, screens_type_info=(screens, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), startElementReference=null, startElementReference_type_info=(startElementReference, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), steps=null, steps_type_info=(steps, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), subflows=null, subflows_type_info=(subflows, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), textTemplates=null, textTemplates_type_info=(textTemplates, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), type=Flow, type_att_info=(xsi:type), variables=null, variables_type_info=(variables, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), waits=null, waits_type_info=(waits, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false)]

The metadata of the object in the org being called is:

 ```
<?xml version="1.0" encoding="UTF-8"?>
<Flow xmlns="http://soap.sforce.com/2006/04/metadata">
    <interviewLabel>Sample_lov {!$Flow.CurrentDateTime}</interviewLabel>
    <label>Sample_loc</label>
    <processType>Flow</processType>
    <screens>
        <name>Something</name>
        <label>Something</label>
        <locationX>127</locationX>
        <locationY>97</locationY>
        <allowBack>true</allowBack>
        <allowFinish>true</allowFinish>
        <allowPause>true</allowPause>
    </screens>
    <startElementReference>Something</startElementReference>
</Flow>
```

Note that the org has no other flows present, so it's strange I get an uninitialised object from the flow request.

**Comment by afawcett** [comment]
Take a look at tip 4 in this [blog](https://andyinthecloud.com/2014/11/22/apex-metadata-api-qa/). Or try a listMetadata API call and see what fullname you get back. It maybe that you need the Flow version number in the name.

**Comment by afawcett** [comment]
Ok so, reading your other issue, i see you have moved on in your thinking, i'll close this one.

**Comment by codewerk** [comment]
Hi Andy, can you consider why I get **nulls** for all properties **reading** any object or element.
Even the simple snippet below returns all nulls. **Creating** is **PERFECT** and error free!

``
MetadataService.CustomField customField =
  (MetadataService.CustomField) service.readMetadata('CustomField',
     new String[] { 'Lead.picklist__c' }).getRecords()[0];
``

**Comment by afawcett** [comment]
Its usually a sign you got the full name wrong, for some reason if you don't give the correct name you don't get an exception, just an empty row, i'm not sure why tbh. Use something like Salesforce Workbench to review your metadata types and names to check your giving the correct one.

**Comment by gopalshakti** [comment]
Dear Andrew,
I can see this null pointer exception issue occurring at the time of retrieving customField is still occurring and has not been resolved in any thread. You have suggested different solutions in different threads, seems nothing is working out.

I ensured and I am using correct object/custom field api names still below returns null.
(MetadataService.CustomField) service.readMetadata('CustomField', new String[] { 'Lead.picklist__c' }).getRecords()[0];
  
Same error is mentioned in below post, where you have suggested that we will have to retrieve parent CustomObject, I couldn't get this solution as we are just making a retrieve call for customField. 
https://github.com/financialforcedev/apex-mdapi/issues/183

May be I am missing something here, Could you please elaborate customObject related solution or suggest me how can I resolve this issue?

Thanks in Advance

Cheers
Shakti

**Comment by codewerk** [comment]
Shakti
I appreciate you staying with this API usage.
I would still like to automate picklist changes to allow internal users to
add/modify/remove dependent values without Setup perm.
