### ISSUE TITLE
Cannot add a field to a layout

### ISSUE THREAD

**Issue by raphym** [financialforcedev/apex-mdapi#167]
**_Your code :_** 
// Read the Layout
MetadataService.Layout layout =
    (MetadataService.Layout) service.readMetadata('Layout',
        new String[] { 'Test__c-Test Layout' }).getRecords()[0];

**_I got this error :_**

Line: 11364, Column: 1
System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 385671458-421778 (1377497918) faultcode=sf:UNKNOWN_EXCEPTION faultactor=

**_And when i print the layout property with system.debug('test Layout = ' + layout);       
all is null so i don't receive the good layout

I received that:_**

18:46:18:346 USER_DEBUG [183]|DEBUG|test Layout = Layout:[Metadata.fullName=null, apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), customButtons=null, customButtons_type_info=(customButtons, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), customConsoleComponents=null, customConsoleComponents_type_info=(customConsoleComponents, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), emailDefault=null, emailDefault_type_info=(emailDefault, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), excludeButtons=null, excludeButtons_type_info=(excludeButtons, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), feedLayout=null, feedLayout_type_info=(feedLayout, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), field_order_type_info=(fullName, customButtons, customConsoleComponents, emailDefault, excludeButtons, feedLayout, headers, layoutSections, miniLayout, multilineLayoutFields, ...), fullName=null, fullName_type_info=(fullName, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), headers=null, headers_type_info=(headers, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), layoutSections=null, layoutSections_type_info=(layoutSections, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), miniLayout=null, miniLayout_type_info=(miniLayout, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), multilineLayoutFields=null, multilineLayoutFields_type_info=(multilineLayoutFields, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), platformActionList=null, platformActionList_type_info=(platformActionList, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), quickActionList=null, quickActionList_type_info=(quickActionList, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), relatedContent=null, relatedContent_type_info=(relatedContent, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), relatedLists=null, relatedLists_type_info=(relatedLists, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), relatedObjects=null, relatedObjects_type_info=(relatedObjects, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), runAssignmentRulesDefault=null, runAssignmentRulesDefault_type_info=(runAssignmentRulesDefault, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), showEmailCheckbox=null, showEmailCheckbox_type_info=(showEmailCheckbox, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), showHighlightsPanel=null, showHighlightsPanel_type_info=(showHighlightsPanel, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), showInteractionLogPanel=null, showInteractionLogPanel_type_info=(showInteractionLogPanel, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), showKnowledgeComponent=null, showKnowledgeComponent_type_info=(showKnowledgeComponent, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), showRunAssignmentRulesCheckbox=null, showRunAssignmentRulesCheckbox_type_info=(showRunAssignmentRulesCheckbox, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), showSolutionSection=null, showSolutionSection_type_info=(showSolutionSection, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), showSubmitAndAttachButton=null, showSubmitAndAttachButton_type_info=(showSubmitAndAttachButton, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), summaryLayout=null, summaryLayout_type_info=(summaryLayout, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), type=Layout, type_att_info=(xsi:type)]

**_Thank you for your reply
Raphael Mazouz_**
@afawcett

**Comment by raphym** [comment]
@wes1278 @grekker @mintotsai @roc-wilcox

**Comment by mintotsai** [comment]
The error message doesn't give us much to go on. Just a shot in the dark, but do you have a layout in your org called 'Test__c-Test Layout'?

**Comment by raphym** [comment]
Thank you,  I resolved the probleme.
The solution was:
For standard field:
<Object Name>-<namespace>__<Layout Name>

For custom field
<namespace>__<Object Name>-<namespace>__<Layout Name>

Thank you
Raphael

**Comment by raphym** [comment]
Thank you, I resolved the probleme.
![img_20170216_214329](https://cloud.githubusercontent.com/assets/17546494/23038007/1abf98f6-f491-11e6-865b-dcc681fc3f8a.jpg)

Thank You
Raphael

**Comment by afawcett** [comment]
Yeah this is a gotcha and yeah the error messages from the underlying API this library wraps could be better at times. For future reference i covered in this [blog](https://andyinthecloud.com/2014/11/22/apex-metadata-api-qa/) some thoughts on the layout and namespace thing. Glad in the meantime the community helped you out @raphym! 👍
