### ISSUE TITLE
Test class for the use of MetadataServiceExamples in my class.

### ISSUE THREAD

**Issue by avinash7891** [financialforcedev/apex-mdapi#170]
Hello @afawcett ,
I am using MetadataServiceExamples to create few custom fields but i am not able to write test classes for them at all. I researched on it but could not get a proper explanation for it. Could you please provide some help in this matter. My application is almost complete but stuck in the test class.

Thanks in advance.
Avinash

**Comment by afawcett** [comment]
Ok well firstly make sure you delete the methods you do not need. The examples class is really designed for you to learn not to be embedded in your own code. You can see some examples of how to test HTTP callouts in the MetadataServiceTest class and also review the [Apex Developers Guide for testing HTTP callouts](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_restful_http_testing_httpcalloutmock.htm).

**Comment by afawcett** [comment]
You can also see some [real test code here](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupControllerTest.cls#L30) for an Apex Controller using the Apex MD API. Good luck! 👍

**Comment by avinash7891** [comment]
Thanks a lot @afawcett :)
