### ISSUE TITLE
LockerService breaking Session ID workaround

### ISSUE THREAD

**Issue by auctifera-josed** [financialforcedev/apex-mdapi#171]
Hi, on the Issue #118  I comment how I implemented a workaround to get a valid session ID in lightning and use the MetadataService asynchronously, but with LockerService critical update auto-activating in 98 days I'm a bit worry on how I can accomplish this because my workaround won't work with this update.

Does any one know another option to get a valid session ID to work in an asynchronous context?

**Comment by afawcett** [comment]
HI @auctifera-josed thanks for raising, can you elaborate as to why your workaround (VF page and PageReference?) will not work after the locker service is enabled?

**Comment by auctifera-josed** [comment]
Hi @afawcett, I just did some more testing and is working with the locker service active. I can swear it stopped working last week when I activated it. Sorry for wasting your time.

**Comment by afawcett** [comment]
No worries, important for these things to surface asap sometimes, glad it was a false alarm this time. 👍
