### ISSUE TITLE
Want to use it in Post install script

### ISSUE THREAD

**Issue by himanshugsmartdata** [financialforcedev/apex-mdapi#172]
Can not get session Id in post install script, So how can I use metadata service in post-install class?

**Comment by BoonPlus** [comment]
Your can run post-install class through a configuration VF page.

![image](https://cloud.githubusercontent.com/assets/5788897/23751892/1caa4a6a-0488-11e7-9cea-b3941fe1d479.png)

**Comment by afawcett** [comment]
Yes, post install scripts are very limited due to the user type / session used. @BoonPlus makes an excellent suggestion! Thanks for sharing btw! 👍

**Comment by himanshugsmartdata** [comment]
@BoonPlus Thanks for the suggestion, But my package takes more time to install so would it going to work for me, as I am always getting the message will get an email after installation complete.

**Comment by BoonPlus** [comment]
@himanshugsmartdata  see the screenshot below for the configuration VF page after our package is installed.

![image](https://cloud.githubusercontent.com/assets/5788897/24094464/0ba42a92-0d16-11e7-8e44-bcbdbacee1f0.png)

![image](https://cloud.githubusercontent.com/assets/5788897/24094503/3129b052-0d16-11e7-9e2f-3717d615497f.png)

**Comment by afawcett** [comment]
Thanks @BoonPlus for sharing! 👍
