### ISSUE TITLE
CustomValue isActive is null even if set on add

### ISSUE THREAD

**Issue by progknife** [financialforcedev/apex-mdapi#173]
When I add a new CustomValue and set the `isActive=true` and fetch the CustomValue again via MetadataAPI, it is `null`. If I fetch the CustomValue again and set `isActive`, it will stick and all is well.

**Create**
```apex
MetadataService.MetadataPort service = createService();

MetadataService.CustomValue one = new MetadataService.CustomValue();
one.color = '#FF6600';
one.default_x = false;
one.description = '';
one.isActive = true;
one.fullName = 'First Value';

MetadataService.ValueSetValuesDefinition vsvd = new MetadataService.ValueSetValuesDefinition();
vsvd.sorted = true;
vsvd.value = new list<MetadataService.CustomValue> { one };

MetadataService.ValueSet vs = new MetadataService.ValueSet();
vs.restricted = true;
vs.valueSetDefinition = vsvd;

MetadataService.CustomField customField = new MetadataService.CustomField();
customField.fullName = 'Opportunity.Mapi_Test__c';
customField.label = 'Mapi Test';
customField.type_x = 'Picklist';
customField.valueSet = vs;

handleSaveResults(
    service.createMetadata(
        new MetadataService.Metadata[] { customField }
    )[0]
);
```
This goes through, I have a new CustomField (Picklist) with one value in it and it is active when viewed from Salesforce.

Then I read this CustomField via the MetadataAPI:

**Read**
```apex
MetadataService.CustomField customField = (MetadataService.CustomField) service.readMetadata(
    'CustomField', new String[] { 'Opportunity.Mapi_Test__c' }
).getRecords()[0];

system.debug('customField: ' + customField);
```

**Output**
```
...
fullName_type_info=(fullName, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), isActive=null, isActive_type_info=(isActive, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false)]
...
```

However when I use the native way to read the field:

**Read**
```apex
Schema.DescribeFieldResult fieldDescription = Opportunity.Mapi_Test__c.getDescribe();
list<Schema.PicklistEntry> picklistValues = fieldDescription.getPicklistValues();

system.debug('picklistValues: ' + picklistValues);
```

**Output**
```
{First Value=Schema.PicklistEntry[getLabel=First Value;getValue=First Value;isActive=true;isDefaultValue=false;]}
```

It is set to true.

**Comment by afawcett** [comment]
Are you reading it using native way in the same execution as your creating it? If so, this will not work, as the current execution context will not have yet "seen" the changes. 

Also when viewing the output in the debug log, run via exec anonymous and you will see the actual XML returned from the MD API. For some reason outputting the response via system.debug in a regular way only shows the static variable values of the types, not the data itself.

**Comment by afawcett** [comment]
@progknife please comment further if you are still having issues here.

**Comment by rsoesemann** [comment]
I am having the same problem again, described here: https://salesforce.stackexchange.com/questions/268593
