### ISSUE TITLE
CustomValue color dynamically assigned

### ISSUE THREAD

**Issue by progknife** [financialforcedev/apex-mdapi#174]
I get this error when saving metadata if I assign null or '' (empty string) to the color property of CustomValue

> Error occured processing component Opportunity.Mapi_Test__c. Invalid color format '' in Color (FIELD_INTEGRITY_EXCEPTION).

This is what I receive from read metadata, color are null and in Salesforce they are "dynamically assigned"
> 14:25:56:669 USER_DEBUG [41]|DEBUG|CustomValues (CustomValue:[Metadata.fullName=null, apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), **color=null**...

The [CustomValue documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_customvalue.htm) says if it is not specified, it will be assigned dynamically but I get the above error instead.

**Comment by afawcett** [comment]
When you assign null to CustomValue the XML element for CustomValue should not be sent by the Apex to XML marshalling framework. Can you run your code in Execute Anonymous and capture the XML sent to confirm? If its not being sent and your getting this error message still, it looks like either the docs are wrong or its a bug in the underlying Salesforce Metadata API.

**Comment by afawcett** [comment]
@progknife please comment further if you are still having issues here.
