### ISSUE TITLE
ListView readmetadata with namespace

### ISSUE THREAD

**Issue by felipelvira** [financialforcedev/apex-mdapi#175]
Hi Andrew,
I'm using your api to retrieve the columns from a list view, in our developer ORG (with a managed package) this can't be achieve. 
I'm doing this:
_Initialize metadaservice api_
`MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();`
_Get metadata from List view_
` MetadataService.ListView readListView = (MetadataService.ListView)service.readMetadata('ListView', new String[] {'ObjectApiName__c.ListViewDevName'
}).getRecords()[0];`

This return an object like:
`ListView:[Metadata.fullName=null, apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), booleanFilter=null, booleanFilter_type_info=(booleanFilter, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), columns=null, columns_type_info=(columns, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), division=null, division_type_info=(division, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), field_order_type_info=(fullName, booleanFilter, columns, division, filterScope, filters, label, language, queue, sharedTo), filterScope=null, filterScope_type_info=(filterScope, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false), filters=null, filters_type_info=(filters, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), fullName=null, fullName_type_info=(fullName, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), label=null, label_type_info=(label, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false), language=null, language_type_info=(language, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), queue=null, queue_type_info=(queue, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), sharedTo=null, sharedTo_type_info=(sharedTo, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), type=ListView, type_att_info=(xsi:type)]`
Any ideas why is this happening?

NOTE:
- Tried like this : `(MetadataService.ListView)service.readMetadata('ListView', new String[] {'NameSpace__.ObjectApiName__c.ListViewDevName'
}).getRecords()[0];`  
as suggested by this [post](http://salesforce.stackexchange.com/questions/156716/metadata-api-error-need-to-specify-full-name-yet-fullname-field-is-populated-i) :

> ListViews are associated with objects and as such, the metadata's fullname has to be the ObjectApiName.ListViewApiName. If using namespaces, then Namespace__.ObjectApiName.ListViewApiName

- And like this:  `(MetadataService.ListView)service.readMetadata('ListView', new String[] {'NameSpace__ObjectApiName__c.ListViewDevName'
}).getRecords()[0];`  

- In this [post](http://salesforce.stackexchange.com/questions/68491/failing-to-get-useful-info-out-of-metadata-api-about-lead-views/68517#68517)  **user8246** is facing the same problem and it's fixed with a new DE, is that the only solution?

Thanks,

**Comment by afawcett** [comment]
Can you run your example code in Anonymous Apex and then review the debug log. When running like this the actual XML request is dumped out to the debug log. The above debug output is only showing the values of the static variables and is not the full picture. Having an XML request and response from the debug log often helps a lot with these issues. Its also a good repo to send to Salesforce via a case, as you can repo via curl. Meanwhile lets look at the XML request and response here see if we can spot anything.... 👍

**Comment by MayTheSForceBeWithYou** [comment]
I ran into a similar problem with Page Layouts on a namespaced developer org... the issue was resolved when I pulled "Lead-namespace__Lead Layout", even though "Lead-Lead Layout" was returned from listMetadata.

**Comment by afawcett** [comment]
Thanks for sharing @MayTheSForceBeWithYou good tip, this is my hunch as well! I also have some info like this on my FAQ for Apex MD API, https://andyinthecloud.com/2014/11/22/apex-metadata-api-qa/. Finally @felipelvira you may want to review the SF ListView API https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_listviews.htm as well. Good luck, please feel free to drop back if you have more questions or are still struggling with this! 👍
