### ISSUE TITLE
How to update RecordType Picklist value only?

### ISSUE THREAD

**Issue by progknife** [financialforcedev/apex-mdapi#176]
I keep getting this error 

> FATAL_ERROR System.CalloutException: IO Exception: Read timed out

whenever I add a PicklistValue to the [CustomObject].[RecordType].picklistValues.values and update.

There are 20 RecordTypes in this object containing ~40 picklist. I need to add a PicklistValue on about 10 of the RecordType's Picklist. I figured this exhausted the 120 seconds max limit. Doing it on future calls does not help either.

Is there a way or how do I update that particular picklist only (without getting the other picklist that I don't need) and sending it back to Metadata API?

Thanks

**Comment by afawcett** [comment]
Sure, take a look at the [known issues for how to solve this](https://github.com/financialforcedev/apex-mdapi#known-issues-and-resolutions).
