### ISSUE TITLE
How to get LastModified and Created Date for Field by meta data in apex.

### ISSUE THREAD

**Issue by sharmanik** [financialforcedev/apex-mdapi#177]
Hi,

I want to get all fields of contact object with their last modified and created date. so that when anyone create, edit and delete any field i can send a request to my external application and update the same field on my application.

Also when user edit/delete/update any field i can perform some operation on my custom object also.
Please help and thanx in advance.

Regards
Nikhil Sharma

**Comment by afawcett** [comment]
Try doing a SOQL over the [EntityDefinition](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_entitydefinition.htm) and [FieldDefinition](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_fielddefinition.htm) objects. These are documented as part of the REST Tooling API, however.. you can query them via SOQL natively in Apex (at least some of the fields anyway). Let me know how you get on! 👍

**Comment by afawcett** [comment]
@sharmanik please comment further if you are still having issues here.

**Comment by SteveFouracre** [comment]
Yes I tried 

String TOOLING_API = '/services/data/v40.0/tooling';

Http h = new Http();
        HttpRequest queryReq = new HttpRequest();
        queryReq.setEndpoint('callout:XXXX' + TOOLING_API + '/query/?q=' + EncodingUtil.urlEncode('SELECT Metadata FROM FieldDefinition WHERE EntityDefinition.QualifiedApiName=\'Account\' AND QualifiedApiName = \'yyyyy__c\'', 'UTF-8'));
String sessionId = UserInfo.getSessionId();
queryReq.setHeader('Authorization', 'OAuth ' + '{!$Credential.OAuthToken}');
queryReq.setMethod('GET');
HttpResponse queryRes= h.send(queryReq);
		system.debug('## MetaDataItems ' + queryRes.getBody());

And this doesnt give the info. Tried various possibilities in the query but nothing works. It is frustrating. Any thoughts Andy?

**Comment by afawcett** [comment]
@SteveFouracre your code does not appear to be related to this question tbh, but try this... https://github.com/afawcett/apex-toolingapi/blob/apex-toolingapi-rest/src/classes/ToolingAPIDemo.cls#L75.

**Comment by dongzhi-yang** [comment]
@afawcett in code line 103 it queries the last modified date from the CustomField object, however, I am looking at the official tooling API documentation, there is no such field under the CustomField object. https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_customfield.htm

**Comment by dongzhi-yang** [comment]
I just figured out why, because these fields are consolidated in this link instead:https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_system_fields.htm
