### ISSUE TITLE
Errors on retrieving certain metadata types

### ISSUE THREAD

**Issue by jaspersardonicus** [financialforcedev/apex-mdapi#179]
I am trying to retrieve the following metadata types and I get errors:

- CompanySettings: Unknown type:CompanySettings
- SamlSsoConfig: Cannot use: SamlSsoConfig in this organization

Can anyone explain why?

**Comment by afawcett** [comment]
Can you share your Apex code fragment making the request?

**Comment by gtsontzos** [comment]
Same issue for me I try to query AddressSettings, when running the following snippet I get the following error:  System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INVALID_TYPE: Unknown type:AddressSettings faultcode=sf:INVALID_TYPE faultactor=


public static MetadataService.MetadataPort createService()
    {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        return service;
    }

MetadataService.MetadataPort service = createService();
List<MetadataService.ListMetadataQuery> queries = new List<MetadataService.ListMetadataQuery>();
MetadataService.ListMetadataQuery querySettings = new MetadataService.ListMetadataQuery();
querySettings.type_x = 'AddressSettings';
queries.add(querySettings);
MetadataService.FileProperties[] fileProperties = service.listMetadata(queries, 38);

**Comment by afawcett** [comment]
That looks ok to me, and it is a documented top level type, https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_addresssettings.htm?search_text=AddressSettings. Can you try using Developer Workbench tool to list the metadata types in your org? Maybe the feature is not enabled? Also check the MetadataService.cls is the latest, i know your giving 38 in the call, but sometimes the end point used has a bearing.

**Comment by afawcett** [comment]
Ah ok, so... take a look at this... https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_settings.htm. You need to use 'Settings' not 'AddressSettings' by the looks of it. Try this...

~~~
querySettings.type_x = 'Settings';
~~~

**Comment by afawcett** [comment]
@jaspersardonicus please comment further if you are still having issues here.
