### ISSUE TITLE
How to add custom fields to existing layout.

### ISSUE THREAD

**Issue by avinash7891** [financialforcedev/apex-mdapi#180]
Hello there,
I have seen the 'Addfieldstolayout' method which updates page layout adding a new custom field in a new section. However, my requirement is to add custom fields to existing layout sections rather than creating a new layout section everytime and adding custom-fields in them. Is this possible?

**Comment by afawcett** [comment]
Yes this is possible, you should be able to adapt the code to search for the layout you want and add to that. 👍
