### ISSUE TITLE
Invalid Session ID found in SessionHeader

### ISSUE THREAD

**Issue by angellocamacho** [financialforcedev/apex-mdapi#181]
I am getting this error when I try to call the describeMetadata method, my salesforce instance has a custom domain.

**Comment by afawcett** [comment]
How are you setting the session ID? From what context? Trigger, Visualforce, Lightning?

**Comment by angellocamacho** [comment]
when I call the init method of the class MetadataRetrieveController

**Comment by afawcett** [comment]
Ok have you taken a look at the trouble shooting section in the README file?

**Comment by angellocamacho** [comment]
yes, I couldn't found nothing related to the issue

**Comment by afawcett** [comment]
Ok these are known issues that effect Session Id. https://github.com/financialforcedev/apex-mdapi#known-issues-and-resolutions . Are you running in a Lightning Component or Visualforce page? What settings under Session configuration under Setup have you got. Can you also confirm that you are assigning the Session ID member.

**Comment by afawcett** [comment]
@angellocamacho please comment further if you are still having issues here.
