### ISSUE TITLE
Updating inlineHelpText

### ISSUE THREAD

**Issue by dk-dev** [financialforcedev/apex-mdapi#184]
public static void updateField()
    {
        MetadataService.MetadataPort service = createService();
        MetadataService.CustomField customField = new MetadataService.CustomField();
        customField.fullName = 'mynamespace__myobject__c.mynamespace__myfield__c';
        customField.inlineHelpText = 'Test Update Metadata';
        List<MetadataService.SaveResult> results =
            service.updateMetadata(new MetadataService.Metadata[] { customField });
        handleSaveResults(results[0]);
    }

This seems like it should work, but it wants field type (type_x), label and (in the case of a text fields) length no matter what. Looking at the metadata docs, it seems like the only required field should be fullName.

Why can't I just update the help text? Is there some way to make these other fields optional and just give it the fullName and inlineHelpText?

End goal is to update help text on a few hundred to a few thousand fields in a managed package unless there is a better way?
Thanks!

**Comment by afawcett** [comment]
Yeah i have encountered that in the past i think. The solution is to read the field first, which does mean reading the CustomObject (as you cannot just read fields). Then maybe you can be more efficient reading all of an object in and updating it all back? There is i believe an example of this in the metadataserviceexamples.cls file?

**Comment by afawcett** [comment]
@dk-dev please comment further if you are still having issues here.
