### ISSUE TITLE
Shell i get package.xml file Through metadata browser?

### ISSUE THREAD

**Issue by Nareshj421** [financialforcedev/apex-mdapi#187]
![metada cap](https://user-images.githubusercontent.com/31504396/29958955-cfb1b156-8f12-11e7-8f6f-af2cad3b2720.PNG)

Here its showing popup message, but i want package.xml with multi selected components.

Any help would be appreciated.

**Comment by afawcett** [comment]
If you have experience in Sencha coding, you can change that code to generate the package.xml. Its not something i can do easily for you, my Sencha coding skills are quite rusty to say the least. Sorry.
