### ISSUE TITLE
AuraDefinitionBundle read call missing content

### ISSUE THREAD

**Issue by idanblich** [financialforcedev/apex-mdapi#195]
HI , 

Summary :
When doing Metadata read call on "AuraDefinitionBundle" some of the return fields should be in a base64 in the read response and contain the full content of the referenced files from the "AuraDefinitionBundle" .
[Doc](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_auradefinitionbundle.htm) and in this repository in [MetadataService.cls](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataService.cls#L714) 

The issue : 
After preforming Metadata read call, the actual strings are in base64 BUT only the first 256 chars of the original file

Repro : 

1. Installing  https://github.com/afawcett/lexapidemos  
2. Preform a read call for [UtilityBarAPIDemo.cmp](https://github.com/afawcett/lexapidemos/blob/master/src/aura/UtilityBarAPIDemo/UtilityBarAPIDemo.cmp)

response will look like : 
```
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://soap.sforce.com/2006/04/metadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Body>
        <readMetadataResponse>
            <result>
                <records xsi:type="AuraDefinitionBundle">
                    <fullName>UtilityBarAPIDemo</fullName>
                    <apiVersion>41.0</apiVersion>
                    <controllerContent>KHsKICAgIGluaXQ6IGZ1bmN0aW9uIChjbXAsIGV2ZW50LCBoZWxwZXIpIHsKCQl2YXIgdXRpbGl0eUFQSSA9IGNtcC5maW5kKCJ1dGlsaXR5YmFyIik7ICAgICAgICAKCSAgICBjbXAuc2V0KCd2Lm15Y29sdW1ucycsIFsKICAgICAgICAgICAgICAgIHtsYWJlbDogJ0lkJywgZmllbGROYW1lOiAnaWQnLCB0eXBlOiAndGV4dCd9LAogICAgICAgICAgICAgICAge2xhYmVsOiAnSXMgTG9hZGVkJywgZmllbGROYW1lOiAnaXNMb2FkZWQnLCB0eXBlOiAn</controllerContent>
                    <description>A Lightning Component Bundle</description>
                    <designContent>PGRlc2lnbjpjb21wb25lbnQgPgoJPGRlc2lnbjphdHRyaWJ1dGUgbmFtZT0iZGVtb01vZGUiIGxhYmVsPSJFbmFibGUgRGVtbyBNb2RlIiAvPgkKPC9kZXNpZ246Y29tcG9uZW50Pg==</designContent>
                    <markup>PGF1cmE6Y29tcG9uZW50IGltcGxlbWVudHM9ImZsZXhpcGFnZTphdmFpbGFibGVGb3JBbGxQYWdlVHlwZXMiPgogICAgPGF1cmE6YXR0cmlidXRlIG5hbWU9Im15ZGF0YSIgdHlwZT0iT2JqZWN0Ii8+CiAgICA8YXVyYTphdHRyaWJ1dGUgbmFtZT0ibXljb2x1bW5zIiB0eXBlPSJMaXN0Ii8+CiAgICA8YXVyYTphdHRyaWJ1dGUgbmFtZT0idXRpbGl0eUlkIiB0eXBlPSJTdHJpbmciLz4KICAgIDxhdXJhOmF0dHJpYnV0ZSBuYW1lPSJoZWlnaHRQWCIg</markup>
                    <styleContent>LlRISVMuYy1jb250YWluZXIgewogICAgYm9yZGVyOiAxcHggc29saWQgI2Q4ZGRlNjsKICAgIG1hcmdpbjogMTBweCAwIDIwcHggMDsKfQouVEhJUyAuaGVhZGVyLWNvbHVtbiB7CiAgICBwYWRkaW5nOiAwIDJyZW07Cn0KLlRISVMgLmZpZWxkLXRpdGxlIHsKICAgIGZvbnQtc2l6ZTogLjc1cmVtOwogICAgbGluZS1oZWlnaHQ6IDEuMjU7CiAgICBjb2xvcjogIzU0Njk4ZDsKICAgIG1hcmdpbi1ib3R0b206IC4yNXJlbTsKfQ==</styleContent>
                    <type>Component</type>
                </records>
            </result>
        </readMetadataResponse>
    </soapenv:Body>
</soapenv:Envelope>
```
the markup after decode the base64 field will as below (different from the actual markup only 256 chars) :
```
<aura:component implements="flexipage:availableForAllPageTypes">
    <aura:attribute name="mydata" type="Object"/>
    <aura:attribute name="mycolumns" type="List"/>
    <aura:attribute name="utilityId" type="String"/>
    <aura:attribute name="heightPX" 
```

**Comment by afawcett** [comment]
Wow that sounds like a bug, i know i did something like this in the MetadataServiceExamples.cls file, can you check that against your code. Also another tip is to run your code in anonymous apex then the debug logs will show the XML sent and received (btw i have no idea why this not shown in regular debug log conditions). This way we can determine if it was a server problem or an unmarshalling one.

**Comment by idanblich** [comment]
Well Zed we have a bug ..
After running the follow code in workbench :
```
MetadataServiceExamples.createLightningComponent();
MetadataServiceExamples.readLightningComponent();
```
This is the full response :
```
07:58:20.701 (824667765)|CALLOUT_RESPONSE|[11578]|<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://soap.sforce.com/2006/04/metadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><readMetadataResponse><result><records xsi:type="AuraDefinitionBundle"><fullName>HelloWorld</fullName><apiVersion>41.0</apiVersion><controllerContent>KHtteUFjdGlvbiA6IGZ1bmN0aW9uKGNvbXBvbmVudCkge2NvbXBvbmVudC5zZXQoJ3YudmFsMScsJ1ZhbHVlMScpO2NvbXBvbmVudC5zZXQoJ3YudmFsMicsJ1ZhbHVlMicpO319KQ==</controllerContent><description>DESCRIPTION</description><markup>PGF1cmE6Y29tcG9uZW50ID48YXVyYTphdHRyaWJ1dGUgbmFtZT0idmFsMSIgdHlwZT0iU3RyaW5nIiBkZWZhdWx0PSJWYWx1ZSIvPjxhdXJhOmF0dHJpYnV0ZSBuYW1lPSJ2YWwyIiB0eXBlPSJTdHJpbmciIC8+PGF1cmE6aGFuZGxlciBuYW1lPSJpbml0IiB2YWx1ZT0ieyF0aGlzfSIgYWN0aW9uPSJ7IWMubXlBY3Rpb259Ii8+PHVpOm91dHB1dFRleHQgdmFsdWU9IkhlbGxvIHdvcmxkISIvPjx1aTpvdXRwdXRUZXh0IHZhbHVlPSJ7IXYudmFsMX0i</markup><type>Component</type></records></result></readMetadataResponse></soapenv:Body></soapenv:Envelope>
```

the debug log show only the first 255 chars after the EncodingUtil.base64Decode of the markup:
```
07:58:20.701 (828997776)|USER_DEBUG|[1117]|DEBUG|<aura:component ><aura:attribute name="val1" type="String" default="Value"/><aura:attribute name="val2" type="String" /><aura:handler name="init" value="{!this}" action="{!c.myAction}"/><ui:outputText value="Hello world!"/><ui:outputText value="{!v.val1}"
```
where the actual markup is :
```
<aura:component ><aura:attribute name="val1" type="String" default="Value"/><aura:attribute name="val2" type="String" /><aura:handler name="init" value="{!this}" action="{!c.myAction}"/><ui:outputText value="Hello world!"/><ui:outputText value="{!v.val1}"/><ui:outputText value="{!v.val2}"/></aura:component>
```

@afawcett can you approach the Metadata PM/Team regarding this ?

**Comment by afawcett** [comment]
@idanblich its best to raise a case yourself on this, if you let me know the case number i can give some support. Best to raise a case with best repo steps possible, i usually use curl and give sample XML file with the request in. Ask the case engineering to grab the session ID the usual way, inspect via Chrome Debugger or something during a logged in session. This approach feels very basic, but avoids SF support getting distracted by the Apex wrapper library, for what is essentially a bug. One last thing you can try (maybe while testing your curl repo, is use the latest API version endpoint url).

**Comment by afawcett** [comment]
I'll close this for now, as its a underlaying platform bug and not the wrapper. But.. feel free to keep the updates flowing here, no problem. 👍
