### ISSUE TITLE
Retrieving Picklist Values using Metadata API Class

### ISSUE THREAD

**Issue by mishu67777** [financialforcedev/apex-mdapi#196]
Hi, i am try to read a custom object to parse all its parameters including Custom Fields.
In custom fields, when i try to read picklist values, it is showing null 

Code: 
Reading custom object.....
for(MetadataService.CustomField vr:  co.customfields){
  System.debug('value for Picklist'+ vr.picklist);  
}

Its shows null value in debug for picklist. 
Any help will be really appreciated.

**Comment by mishu67777** [comment]
Its same David
public String endpoint_x = URL.getSalesforceBaseUrl().toExternalForm() + '/services/Soap/m/38.0';

What version should i use to make it work properly.
Please guide.

**Comment by mishu67777** [comment]
I tried to change the API version from 38.0 to 39.0 and 40.0 and get the below error.

System.CalloutException: Web service callout failed: Unable to parse callout response. Apex type not found for element label
Error is in expression '{!DisplayDetails}' in component Class MetadataService.MetadataPort.readMetadata: line 11548, column 1

**Comment by dfruddffdc** [comment]
Check out the [Metadata API docs for CustomField](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/customfield.htm)
From API v38, CustomField.picklist is deprecated.
You need to read the CustomField.valueSet field instead.
