### ISSUE TITLE
System.CalloutException: IO Exception: Unauthorized endpoint, please check Setup->Security->Remote site settings. 

### ISSUE THREAD

**Issue by SPprasanna** [financialforcedev/apex-mdapi#201]
Dear Andrew,

I have started to learn the metadata API for one of our project requirements. I have installed your metadata api package and i tried to execute the createLongTextAreaField() as part of the MetadataServiceExamples through the execute anonymous option. And am getting the above error. I have added the URL under remote site settings but still am getting the error. Request your help in proceeding with this

Thanks

**Comment by afawcett** [comment]
Hi @SPprasanna, the rest of the error message gives you instructions on how to solve this problem. Basically you need to head over to the Setup menu and search for Remote Sites. Then add an entry using the URL given in the error message. This should get you going! 👍

**Comment by dfruddffdc** [comment]
Thanks @afawcett , closing!
