### ISSUE TITLE
Not able to retrieve some components

### ISSUE THREAD

**Issue by avaidya** [financialforcedev/apex-mdapi#202]
I want count of some components to show in the dashboard for that I have used MetadataService class but it's giving following issue:
-------------------
Visualforce Error
System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INVALID_TYPE: Cannot use: AssignmentRule in this version faultcode=sf:INVALID_TYPE faultactor= 
Class.MetadataService.MetadataPort.listMetadata: line 11621, column 1
Class.MetadataCountController.getSizeofComponents: line 14, column 1
Class.MetadataCountController.getMetadataCount: line 26, column 1
-----------------------

Example metadata types for which it's giving issue are ApprovalProcess, AssignmentRule etc.

Can you please let me know what is the issue? Also I checked supported version for ApprovalProcess is 28.0 and later and you used version 38.0 still it's giving this issue. Do I still need to take latest version than 38.0 if yes can you please give me the steps to generate the apex class from latest metadadata api?

Thank you,
Amit

**Comment by afawcett** [comment]
The listMetadata method takes a version parameter make sure you are passing the correct version. Also the steps to generate a new file are in the README file. 👍

**Comment by dfruddffdc** [comment]
Thanks @afawcett, looks like this issue is good to close.
