### ISSUE TITLE
Getting Error during creation of object through Metadataservice API

### ISSUE THREAD

**Issue by harshad22dani** [financialforcedev/apex-mdapi#206]
Hello,

I am trying to create a custom object, below is the code as you specified.

```java
MetadataService.MetadataPort service = createService();
MetadataService.CustomObject customObject = new MetadataService.CustomObject();
// customObject.fullName = 'Test__c';
customObject.label = 'Test';
customObject.pluralLabel = 'Tests';
customObject.nameField = new MetadataService.CustomField();
customObject.nameField.type_x = 'Text';
customObject.nameField.label = 'Test Record';
customObject.deploymentStatus = 'Deployed';
customObject.sharingModel = 'ReadWrite';

List<MetadataService.SaveResult> results =      
    service.createMetadata(
        new MetadataService.Metadata[] {customObject});

handleSaveResults(results[0]);
```
******I am getting error at second last line "Error: Compile Error: Initial expression is of incorrect type, expected: MetadataService.Metadata but was: MetadataService.CustomObject at line 21 column 17****	"**

What i am missing, not understanding.
Please help

Thanks in Advance

**Comment by dfruddffdc** [comment]
If you create the following class in your org, does it compile?

```java
public class apexMdapiIssue206
{
	static
	{
		MetadataService.MetadataPort service = null;
		MetadataService.CustomObject customObject = new MetadataService.CustomObject();
		service.createMetadata(new MetadataService.Metadata[] {customObject});
	}
}
```

This is a simplified version of your code, which compiles ok in my testing org. I'm not sure why your sample code isn't compiling, without seeing it in the full context. My guess is that there is another variable shadowing a variable name like service or customObject...

But hopefully this example will prove that the library is working as designed in your org, and help you to narrow down the problem in your class.

**Comment by harshad22dani** [comment]
Thanks David for your response!
I found the problem, actually generated APEX class was not properly generated through WSDL, so when i amended it. It worked.

Regards
Harshad Dani

**Comment by dfruddffdc** [comment]
Great to hear it, thanks for reporting back!

**Comment by Qurogo** [comment]
Hi harshad22dani, 

I know this was quite a while, but right now I'm having same issue and looking for possible ways to solve it, would it be possible for you to deeper explain how you managed to fix it, what do you meant by "generated APEX class was not properly generated through WSDL", also, if you have an example it would be great.

Best Regards

**Comment by Dipeea** [comment]
Hi, I am facing same error on below code:
    public static void createemailServicesAddress(String fullName, String url)
    {
            //Metadata Service
    MetadataService.MetadataPort service = new MetadataService.MetadataPort();
    service.SessionHeader = new MetadataService.SessionHeader_element();
    service.SessionHeader.sessionId = UserInfo.getSessionId();

    MetadataService.EmailServicesAddress emailaddr = new MetadataService.EmailServicesAddress();
    emailaddr.developerName = fullName;
    emailaddr.isActive = Boolean.valueOf('true');
    MetadataService.SaveResult[] results = service.createMetadata(new List<MetadataService.Metadata>{ emailaddr }
    );
        for (MetadataService.SaveResult result : results) {
      if (result.success) {
        //Success
        System.debug(result);
      } else {
        //Failed
        System.debug(result.errors[0].message);
      }

    }
    }

I am getting compilation error: Initial expression is of incorrect type, expected: MetadataService.Metadata but was: MetadataService.EmailServicesAddress
Could you please suggest on this?
