### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by mickyinba** [financialforcedev/apex-mdapi#209]
I have deployed this to my sandbox.
What is the process to completely remove this package?

**Comment by dfruddffdc** [comment]
Check out the [Salesforce docs on Deleting Files from an Organization](https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/daas_destructive_changes.htm).
> To delete components, use the same procedure as with deploying components, but also include a delete manifest file that’s named destructiveChanges.xml and list the components to delete in this manifest. The format of this manifest is the same as package.xml except that wildcards aren’t supported.

So you need to create a destructiveChanges.xml file with the names of all of the components in this repo. You can do this manually, or you can use something like the [df12-deployment-tools repo](https://github.com/financialforcedev/df12-deployment-tools/blob/master/lib/undeploy.xml) to build the file based on the contents of a local source folder.

Undeploy is not always straightforward. Salesforce attempt to enforce referential integrity by preventing deletion of components used elsewhere in your org. So you may need to delete/modify some of your own classes to remove references to this library. You may simply find it easier to refresh the sandbox.

Hope that helps!
