### ISSUE TITLE
Need help..Getting error while trying to deploy profile

### ISSUE THREAD

**Issue by snehaheda** [financialforcedev/apex-mdapi#22]
I am trying to deploy a profile using the api. I am getting an error 

profiles/Standard Platform Usercopy.profile (Line: null: Column:null) : duplicate value found: <unknown> duplicates value on record with id: <unknown>.

Any info or pointers would be helpful.

**Comment by kaushsa** [comment]
i am running into a similar issue. Getting weird error for profile meta-data. How were you able to fix this issue?

**Comment by afawcett** [comment]
I was not, not sure @snehaheda did either, i've had no follow up to me last couple of questions for more information.
