### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by barcealona** [financialforcedev/apex-mdapi#233]
Hello,

When I try to deploy the code here to my trailhead org, I get this error message:

"We can't authorize you because of an OAuth error. For more information, contact your Salesforce administrator.

1800 : There was a problem in setting up your remote access" 

Is anyone have an Idea why this happened?

**Comment by tgentet-obrien** [comment]
@barcealona I am having the same issue using another app, would you be happy sharing some data on your org? (I have a case open with SF).

Is your Org on one of the UM Servers? (https://status.salesforce.com/search/UM), this is happening to one of my clients who is on UM5! Which makes me believe there is an issue with how they are generating the instances.

**Comment by dfruddffdc** [comment]
I guess you are using the Deploy to Salesforce button in the README.

I think @afawcett has resolved the issue, which was to do with the connected app responsible for OAuth being purged by Salesforce housekeeping. More details here: https://github.com/afawcett/githubsfdeploy/issues/35

@tgentet-obrien perhaps it's a similar issue in your app?
