### ISSUE TITLE
Deployment fails with "Class MetadataService : Script too large"

### ISSUE THREAD

**Issue by rsoesemann** [financialforcedev/apex-mdapi#240]
The `MetadataService` class seems to have exceeded the 1 MB limit (at least on Windows systems with more "expensive" line endings.

Please see this detailed Stackexchange post https://salesforce.stackexchange.com/questions/244518

Can someone split down the class or think of any other solution?

**Comment by robdavis-cs** [comment]
👍

**Comment by nchursin** [comment]
Just talked to a former colleague and this issue cam to my mind. The solution us not to split as it means either facading a ton of things or breaking changes. The solution is to [add `.gitattributes` file](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings), that will prevent git messing around with line endings.

**Comment by tkauffman1** [comment]
This didn't work for me.
