### ISSUE TITLE
Create Custom Application using the API

### ISSUE THREAD

**Issue by aryamaia** [financialforcedev/apex-mdapi#246]
Hi,
I am trying to create a custom Application through the apex code by using the CustomApplication class of MetadataService.cls. But I am not able to create one. I was able o create the Custom Object. 
 Does it support to create a custom app?
Sample Snippet Code
List<MetadataService.Metadata> fields = new List<MetadataService.Metadata>();
MetadataService.CustomApplication  customapplication = new MetadataService.CustomApplication();
customapplication.navType='standard';
customapplication.formFactors=new List<String>{'Large'};
customapplication.label='ApexApp';
fields.add(customapplication);
MetadataService.SaveResult[] results = service.createMetadata(fields);

Kindly let me know regarding this.
Thank You

**Comment by BoonPlus** [comment]
Yes! It's doable. I've used this class to create custom apps within my package. Below is my code...

            MetadataService.MetadataPort service = createService();
            List<MetadataService.Metadata> MetadataClassic = new List<MetadataService.Metadata>();
                MetadataService.CustomApplication CustomApplicationClassic = new MetadataService.CustomApplication();
                CustomApplicationClassic.fullName = 'Easy_Pricing_Classic_mp';            
                if (nsPrefixEPOP != null) CustomApplicationClassic.defaultLandingTab = nsPrefixEPOP + '__Easy_Pricing_for_Opportunity_mp'; 
                else CustomApplicationClassic.defaultLandingTab = 'Easy_Pricing_for_Opportunity_mp';
                CustomApplicationClassic.description = 'Pricing Management Made Easy';
                CustomApplicationClassic.label = 'BoonPlus Easy Pricing';
                if (nsPrefixEPOP != null) CustomApplicationClassic.logo = nsPrefixEPOP + '__BoonPlus/'+nsPrefixEPOP+'__BoonPlus_Easy_Pricing_Logo.png';
                else CustomApplicationClassic.logo = 'BoonPlus/BoonPlus_Easy_Pricing_Logo.png';
                CustomApplicationClassic.tabs = new List<String>();
                if (nsPrefixEPOP != null) CustomApplicationClassic.tabs.add(nsPrefixEPOP + '__Pricing_Rule_mp__c');
                else CustomApplicationClassic.tabs.add('Pricing_Rule_mp__c');
                if (nsPrefixEPOP != null) CustomApplicationClassic.tabs.add(nsPrefixEPOP + '__Pricing_Formula_mp__c');
                else CustomApplicationClassic.tabs.add('Pricing_Formula_mp__c');
                if (nsPrefixEPOP != null) CustomApplicationClassic.tabs.add(nsPrefixEPOP + '__Easy_Pricing_for_Opportunity_mp');
                else CustomApplicationClassic.tabs.add('Easy_Pricing_for_Opportunity_mp');
                MetadataClassic.add(CustomApplicationClassic);
MetadataService.SaveResult[] resultsClassic = service.createMetadata(MetadataClassic);

**Comment by aryamaia** [comment]
> Yes! It's doable. I've used this class to create custom apps within my package. Below is my code...
> 
> ```
>         MetadataService.MetadataPort service = createService();
>         List<MetadataService.Metadata> MetadataClassic = new List<MetadataService.Metadata>();
>             MetadataService.CustomApplication CustomApplicationClassic = new MetadataService.CustomApplication();
>             CustomApplicationClassic.fullName = 'Easy_Pricing_Classic_mp';            
>             if (nsPrefixEPOP != null) CustomApplicationClassic.defaultLandingTab = nsPrefixEPOP + '__Easy_Pricing_for_Opportunity_mp'; 
>             else CustomApplicationClassic.defaultLandingTab = 'Easy_Pricing_for_Opportunity_mp';
>             CustomApplicationClassic.description = 'Pricing Management Made Easy';
>             CustomApplicationClassic.label = 'BoonPlus Easy Pricing';
>             if (nsPrefixEPOP != null) CustomApplicationClassic.logo = nsPrefixEPOP + '__BoonPlus/'+nsPrefixEPOP+'__BoonPlus_Easy_Pricing_Logo.png';
>             else CustomApplicationClassic.logo = 'BoonPlus/BoonPlus_Easy_Pricing_Logo.png';
>             CustomApplicationClassic.tabs = new List<String>();
>             if (nsPrefixEPOP != null) CustomApplicationClassic.tabs.add(nsPrefixEPOP + '__Pricing_Rule_mp__c');
>             else CustomApplicationClassic.tabs.add('Pricing_Rule_mp__c');
>             if (nsPrefixEPOP != null) CustomApplicationClassic.tabs.add(nsPrefixEPOP + '__Pricing_Formula_mp__c');
>             else CustomApplicationClassic.tabs.add('Pricing_Formula_mp__c');
>             if (nsPrefixEPOP != null) CustomApplicationClassic.tabs.add(nsPrefixEPOP + '__Easy_Pricing_for_Opportunity_mp');
>             else CustomApplicationClassic.tabs.add('Easy_Pricing_for_Opportunity_mp');
>             MetadataClassic.add(CustomApplicationClassic);
> ```
> 
> MetadataService.SaveResult[] resultsClassic = service.createMetadata(MetadataClassic);

**Comment by aryamaia** [comment]
Thank You Boon,
I was able to work it out and create a custom application. But one thing can you let me know, where I can set visibility of application to a user through apex code. I was able to create a custom application. But since visibility was not set in apex, I had to do it manually.
