### ISSUE TITLE
Receiving "null" for values when calling for "Flow"

### ISSUE THREAD

**Issue by knght4yshua** [financialforcedev/apex-mdapi#248]
When attempting to retrieve Flow-specific data via the Apex Metadata API each value in the key-value pairs is null. Here is the code:

`private static void getFlowMetadata(Double apiVersion, MetadataService.MetadataPort mdService){

    List<String> lFlowNames = new List<String>();   
    List<String> lFlowNamesGroupedInTensTemp = new List<String>();
    List<List<String>> lFlowNamesGroupedInTens = new List<List<String>>();
    List<MetadataService.ListMetadataQuery> queries = new List<MetadataService.ListMetadataQuery>();        
    MetadataService.ListMetadataQuery queryWorkflow = new MetadataService.ListMetadataQuery();
    queryWorkflow.type_x = 'Flow';
    queries.add(queryWorkflow);         
    MetadataService.FileProperties[] lFileProperties = mdService.listMetadata(queries, apiVersion);

    // Since  the readMetadata method in the Apex Metadata API only supports ten records per call,
    // group each fileProperty queried into sets of ten
    for(Integer i = 0; i < lFileProperties.size(); i++){
        lFlowNames.add(lFileProperties[i].fullName);
        lFlowNamesGroupedInTensTemp.add(lFileProperties[i].fullName);

        if((Math.mod(i, 10) == 0) || (Math.mod(i, 10) != 0 && lFileProperties.size() - i < 10)){
            lFlowNamesGroupedInTens.add(lFlowNamesGroupedInTensTemp);
            lFlowNamesGroupedInTensTemp = new List<String>();
        }
    }

        MetadataService.Flow flowResult = (MetadataService.Flow) mdService.readMetadata('Flow', new List<String>{'CGS_Sold_Process_Manager_Flow'}).getRecords()[0];

        System.debug('flowResult ------> '+flowResult);
}`

"flowResult" produces the following:

> Flow:[Metadata.fullName=null, actionCalls=null, actionCalls_type_info=(actionCalls, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), apexPluginCalls=null, apexPluginCalls_type_info=(apexPluginCalls, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), assignments=null, assignments_type_info=(assignments, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), choices=nu..."

All keys are coming across as expected/desired. But the values are null. In contrast, when I call the tooling API for the data, it retrieves it just fine. I've verified the API Name of the Flow in the UI several times, and even tried the Label instead just in case.  Nada.

What is going on with Flows and the Metadata API?

**Comment by knght4yshua** [comment]
I figured out the issue.  The "Flow" Metadata Type in the main MetadataService class was missing a declaration for the "status" Apex type.  To resolve the issue in your own org:

(1) Open the MetadataService class in Dev Console
(2) Scroll to line 3814 and add a new line below it with the following code:

public String status;

(3) Scroll down to the NEW line 3841 and add a new line below it with the following code:

private String[] status_type_info = new String[]{'status',SOAP_M_URI,null,'1','1','false'};

The code will now pull multiple flows as desired and expected.

**Comment by afawcett** [comment]
@kgalant awesome!
