### ISSUE TITLE
updateMetadata with listView & filterScope

### ISSUE THREAD

**Issue by blaketanon** [financialforcedev/apex-mdapi#25]
Hi Andrew,
I really like the work you've done here - I've been applying it to several different projects.  I have a need to programmatically modify the sharing on list views, i've been playing around with this but I haven't been able to achieve the results I'm looking for.  When I pass a list to the updateMetadata method, the pieces I have declared update but everything else is set to erased; such as the fields, filters, etc.   Second, I noticed that updating some lists I need to designate the listView.filterScope or an error returns "System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: '' is not a valid value for the enum 'FilterScope' faultcode=soapenv:Client faultactor=", which isn't a huge problem but I would have to set that value to 'Everyone' that may overwrite some lists settings.

In a perfect world I'd like to run this process:
1. Query all listViews created by a specific user/role
2. Change the sharing to a public group
3. Update

I've attached the code I've found to work best so far, and to simplify i'm only looking at a single list - ideally I would run it in bulk.  If you have any pointers please let me know, maybe i'm using this completely wrong.

'''

```
public void listViewShare(string lvName){
    MetadataService.ListView listView = new MetadataService.ListView();
    listView.fullName = 'contact.'+lvName;
    listView.filterScope = 'Everything';
    listView.sharedTo = new MetadataService.sharedTo();
    listView.sharedTo.groups = new list<String>{ 'Territory_Central' };

    List<MetadataService.UpdateMetadata> updateMetadataList = new List<MetadataService.UpdateMetadata>();   
    updateMetadataList.add(new MetadataService.UpdateMetadata());
    updateMetadataList[0].currentName = 'contact.'+lvName;
    updateMetadataList[0].metadata = listView;

    MetadataService.AsyncResult[] results = service.updateMetadata(updateMetadataList); 

}
```

'''

**Comment by abhishek200-ai** [comment]
@afawcett 

List<MetadataService.UpdateMetadata> 

Geeting error in this line the MetadataService.UpdateMetadata is not a valid type.
Already have MetadataService Class in my org.please help
