### ISSUE TITLE
Issue with Creating Global Picklist

### ISSUE THREAD

**Issue by srigottipati** [financialforcedev/apex-mdapi#263]
Hi,

I am executing below code in Dev Console.Code is executing without any error, but Global picklist is not getting created.

any suggestion?
`MetadataService.MetadataPort service = new MetadataService.MetadataPort();
service.SessionHeader = new MetadataService.SessionHeader_element();
service.SessionHeader.sessionId = UserInfo.getSessionId();

String valueSetName = 'test123';

MetadataService.GlobalValueSet globalValueSet = new MetadataService.GlobalValueSet();

MetadataService.CustomValue newItem = new MetadataService.CustomValue();
          newItem.fullName = 'value';
          newItem.label = 'label';
          newItem.isActive = true;
          newItem.default_x = true;

if(globalValueSet.customValue ==null){
globalValueSet.customValue = new List<MetadataService.CustomValue>();
}    

globalValueSet.customValue.add(newItem);

globalValueSet.masterLabel='test123';
globalValueSet.sorted=false;
globalValueSet.description='sd';
service.createMetadata(
                        new MetadataService.Metadata[]{
                                globalValueSet
                        });
`

and

errors =null and success =false from saveResult

**Comment by srigottipati** [comment]
tried with createMetadata option also.

**Comment by Bhaveshjainsfdc** [comment]
how were you able to fix this? I am facing the same issue the code is executing but backend metadata is not getting created

**Comment by srigottipati** [comment]
try adding below line in the code.

globalValueSet.fullName=valueSetName;

**Comment by Bhaveshjainsfdc** [comment]
worked for me :) I have written the below method for updating a global picklist value using the below code but I am getting the error: DEBUG|eror : CustomField not found (appreciate any suggestions/directions )

public static void updateGlobalPicklist(){
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        
        MetadataService.GlobalValueSet  customField8 = (MetadataService.GlobalValueSet) service.readMetadata('GlobalValueSet', new String[] { 'Country'}).getRecords()[0];
        
        for(MetadataService.CustomValue objCustomValue : customField8.customValue){
            
            if(objCustomValue.fullName == 'India'){
                objCustomValue.fullName = 'States';
                objCustomValue.label = 'States';
                //objCustomValue.isActive = true;
                //objCustomValue.default_x = true;
                
            }else{
                system.debug('country not found');
            }
        }
        List<MetadataService.SaveResult> lstResults5 = service.updateMetadata( new MetadataService.Metadata[] { customField8  });
        for (MetadataService.SaveResult objResult : lstResults5) {
            if (objResult.success) {
                System.debug('Successfully updated.......123131313123');
            }
            else {                       
                if(objResult.errors.size() > 0){
                    System.debug('eror : ' + objResult.errors[0].message);
                }
            }
        }
    }
