### ISSUE TITLE
System.JSONException: Duplicate field:---Error Due to Metadata base class fields

### ISSUE THREAD

**Issue by abhinavpokharna** [financialforcedev/apex-mdapi#29]
Deserilaization of Metadata subclasses causes error.
Ex: System.JSONException: Duplicate field: MetadataService.PermissionSet.fullName_type_info
  
Please remove these three fields, 'fullName_type_info', 'apex_schema_type_info', 'field_order_type_info' from Metadata Class.

**Comment by afawcett** [comment]
Finally fixed, sorry for the delay!
