### ISSUE TITLE
Enhancement : Insert Picklist fields with controlling field and controlling field values 

### ISSUE THREAD

**Issue by mohit-address** [financialforcedev/apex-mdapi#3]
It took me quite a time to figure picklist , controlling, dependent etc so . i though it would be helpful addition on your work 

Here is the example for Creating picklist field  , with controlling field , and controlling field values

<pre>
<code>
  public static void createPicklistField()
    {
        MetadataService.MetadataPort service = createService();     
        MetadataService.CustomField customField = new MetadataService.CustomField();
            customField.fullName = 'lead.dependent_picklist__c';
            customField.label = 'Dependent Picklist';
            customField.type_x = 'Picklist';
            
        
        metadataservice.Picklist pt = new metadataservice.Picklist(); // creat picklist metadata
            pt.sorted= false;
            pt.controllingField = 'Controlling_Picklist__c'; // Define controlling field only name . not object name, only if you are creating Dependent field , else dont include line : if field dependency doesnot exist , it will create new one
        
        metadataservice.PicklistValue one = new metadataservice.PicklistValue(); // create picklist values metadata
            one.fullName= 'Dependent 0';
            one.default_x=false ;
            one.controllingFieldValues = new list &lt;string&gt; {'Control Odd number'};  // assign controlling field values
           
        metadataservice.PicklistValue two = new metadataservice.PicklistValue();
            two.fullName= 'Dependent 1';
            two.default_x=false ;
            two.controllingFieldValues = new list &lt;string&gt; {'Control Odd number','Control Even number'}; // assign controlling field values
            
        pt.picklistValues = new list&lt;metadataservice.PicklistValue&gt;{one,two}; // assign picklist values
            customField.picklist = pt ;                                       // assign Picklist
        MetadataService.AsyncResult[] results = service.create (new List&lt;MetadataService.Metadata&gt; { customField });
      
    } 

</pre>

</code>

and here is the code to update picklist field 

<pre>
<code>
 

public static void UpdatePicklistField()
    {
         MetadataService.MetadataPort service = createService();
         MetadataService.CustomField customField = new MetadataService.CustomField(); 
            customField.fullName = 'lead.dependent_picklist__c';
            customField.label = 'Dependent Picklist';
            customField.type_x = 'Picklist'; 
            
        metadataservice.Picklist pt = new metadataservice.Picklist();
            pt.sorted= false;
            pt.controllingField= 'Controlling_Picklist__c'; //***** name of controlling field . if picklist has contrlloing field , this must be asssigned . else field dependency will be deleted
            
                metadataservice.PicklistValue first_dependent = new metadataservice.PicklistValue();
                 first_dependent.fullName= 'Dependent 2'; 
                 first_dependent.default_x=false ;
                 first_dependent.controllingFieldValues = new list &lt;string&gt;{'Control Even number'};  // list of names of controlling field Picklist value . dont put this line , if you dont want any controlling picklist value
           pt.picklistValues = new list&lt;metadataservice.PicklistValue&gt;{first_dependent};
         customField.picklist = pt ;
       
       
       MetadataService.UpdateMetadata ut = new MetadataService.UpdateMetadata();
            ut.currentName='lead.dependent_picklist__c';
            ut.metadata= customField;
       MetadataService.AsyncResult[] results = service.updateMetadata(new List&lt;MetadataService.updateMetadata&gt; {ut});
         
    }
</pre>

</code>

**Comment by Bhaveshjainsfdc** [comment]
hi @mohit-address @afawcett 
Since picklist is depreciated I used valueset to create dependent fields using metadata API can anyone help me if there is anything missing in the below I am getting a null pointer

public static void createDependentPicklistField(){
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        
       /* MetadataService.CustomField customField2 = new MetadataService.CustomField();
        customField2.fullName = 'lead.Controlling_Picklist__c';
        customField2.label = 'Controlling Picklist';
        customField2.type_x = 'Picklist';
        MetadataService.SaveResult[] results2 = service.createMetadata(new List<MetadataService.Metadata> { customField2 }); */
        
        MetadataService.CustomField customField = new MetadataService.CustomField();
        customField.fullName = 'lead.dependent_picklist__c';
        customField.label = 'Dependent Picklist';
        customField.type_x = 'Picklist';
        system.debug('L180'+customField);
        
        MetadataService.ValueSet valuest = new MetadataService.ValueSet();
        valuest.controllingField= 'Controlling_Picklist__c';
        system.debug('controlling field at L185 is'+valuest.controllingField);
        MetadataService.ValueSetValuesDefinition newValsetDef = new MetadataService.ValueSetValuesDefinition();
        newValsetDef.sorted = false;
		system.debug('L187'+newValsetDef); 
        
        MetadataService.CustomValue newItem = new MetadataService.CustomValue();
        newItem.fullName = 'Dependent 0';
        newItem.label = 'Dependent 0';
        newItem.isActive = true;
        newItem.default_x = true;
        system.debug('L194'+newItem); 
        
        MetadataService.ValueSettings valsetting = new MetadataService.ValueSettings();
        valsetting.controllingFieldValue = new list <string> {'Control Odd number'}; 
        system.debug('L198'+valsetting);
        
        newValsetDef.value.add(newItem);
        valuest.valueSetDefinition = newValsetDef;
        valuest.valueSettings.add(valsetting);
        
        //Adding second picklist
        MetadataService.CustomValue newItem2 = new MetadataService.CustomValue();
        newItem2.fullName = 'Dependent 1';
        newItem2.label = 'Dependent 1';
        newItem2.isActive = true;
        newItem2.default_x = false;
        
        MetadataService.ValueSettings valsetting1 = new MetadataService.ValueSettings();
        valsetting1.controllingFieldValue = new list <string> {'Control Odd number','Control Even number'}; 
        
        newValsetDef.value.add(newItem2);
        valuest.valueSetDefinition = newValsetDef;
        valuest.valueSettings.add(valsetting1);
        
        //MetadataService.AsyncResult[] results = service.createMetadata(new List<MetadataService.Metadata> { customField });
        MetadataService.SaveResult[] results1 = service.createMetadata(new List<MetadataService.Metadata> { customField });
        
        for (MetadataService.SaveResult objResult : results1) {
            if (objResult.success) {
                System.debug('Successfully updated.......123131313123');
            }
            else {                       
                if(objResult.errors.size() > 0){
                    System.debug('eror : ' + objResult.errors[0].message);
                }
            }
        }
    }
