### ISSUE TITLE
Request : need some help on record type , Picklist field Describe  call

### ISSUE THREAD

**Issue by mohit-address** [financialforcedev/apex-mdapi#4]
Hi , 
I was working on assigning Picklist values to record type (Updating Record Type )and i  discovered a huge issue 
May be you can help me out here

1 . Here is the code for creating a Record type 
     Object : Lead 
     New Record Type name : Second Record Type
     business Process= first lead process
    Picklist Field : dependent picklist
 Existing Picklist values in this Picklist - Dependent 0 ,  Dependent 1 , Dependent 2 , Dependent 3

```
Picklist values to be assigned in this record type :  Dependent 0, Dependent 1 , Dependent 2
```

<pre>
<code>
Public static void InserRecordtype()
    {
        MetadataService.MetadataPort service = createService(); 
        MetadataService.RecordType rt = new MetadataService.RecordType();
            rt.fullName='lead.second_Record_Type';
            rt.label='Second Record Type';
            rt.active= true;
            rt.businessProcess= 'first lead process';
        
        MetadataService.RecordTypePicklistValue mrt = new MetadataService.RecordTypePicklistValue ();
            mrt.picklist = 'dependent_picklist__c';
                metadataservice.PicklistValue two = new metadataservice.PicklistValue();
                    two.fullName= 'Dependent 1';
                    two.default_x=false ;
                metadataservice.PicklistValue three = new metadataservice.PicklistValue();
                    three.fullName= 'Dependent 0';
                    three.default_x=false ; 
                    
                metadataservice.PicklistValue four = new metadataservice.PicklistValue();
                    four.fullName= 'Dependent 2';
                    four.default_x=false ;       
                
          mrt.values = new list&lt;metadataservice.PicklistValue&gt; {two,three,four} ;
          
        rt.picklistValues = new list &lt;MetadataService.RecordTypePicklistValue&gt;{mrt};
        
      MetadataService.AsyncResult[] results = service.create (new List&lt;MetadataService.Metadata&gt; { rt });
    }

</code>
</pre>

---- works perfectly , new Record type created , and picklist values assigned for field ---------------

2 . Now . 
    if I want to add new values in Assigned Picklist Values  at above record type 
    New Picklist value to be added :  Dependent 3
so here is the code for updating record type 

<pre> <code>

Public static void UpdateRecordtype()
    {
        MetadataService.MetadataPort service = createService(); 
        MetadataService.RecordType rt = new MetadataService.RecordType();
        rt.fullName='lead.second_Record_Type';
        rt.label='Second Record Type';
        rt.active= true;
        rt.businessProcess= 'first lead process';
        
        MetadataService.RecordTypePicklistValue mrt = new MetadataService.RecordTypePicklistValue ();
        mrt.picklist = 'dependent_picklist__c';
            metadataservice.PicklistValue five = new metadataservice.PicklistValue();
                five.fullName= 'Dependent 3';
                five.default_x=false ;
           
          mrt.values = new list&lt;metadataservice.PicklistValue&gt; {five} ;
          
        rt.picklistValues = new list &lt;MetadataService.RecordTypePicklistValue&gt;{mrt};
        
        
        
         MetadataService.UpdateMetadata ut = new MetadataService.UpdateMetadata();
        ut.currentName='lead.second_Record_Type';
        ut.metadata= rt;
       MetadataService.AsyncResult[] results = service.updateMetadata(new List&lt;MetadataService.updateMetadata&gt; {ut});
    
    }

</code></pre>

3- Ideally in a perfect word : now assigned values should be : Dependent 0 ,  Dependent 1 , Dependent 2 , Dependent 3

.............................BUT ........................
--->  Now assigned value contain only : Dependent 3 (i.e it removes all existing values )

So my question is : is there any method to get existing assigned picklist  values for any record type 
in my case Dependent 0 ,  Dependent 1 , Dependent 2 . before inserting new values 
If i pass 
Object : lead 
Record type name : Second record Type 
Picklist Field name : dependent picklist

In Describe Metadata or any other method ???

or , any method by which we can keep the existing values and add new picklist values without removing old one ??

**Comment by Pavanaja3** [comment]
Hi,
I'm trying to find the solution for the above problem. i did it by reading metadata for record type - 
MetadataService.RecordType rt = (MetadataService.RecordType ) service.readMetadata('RecordType', new String[] { 'object.Record_type' }).getRecords()[0];
rt.picklistValues.add(mrt);

then tried updating it with this line - 
List<MetadataService.SaveResult> saveResult1 = service.updateMetadata(
                new MetadataService.Metadata[] { rt }); 

It says 'IO Exception: Read Time out'. Though it gives an exception, new picklist value got added to selected picklist list without removing old ones. I don't know, whether to continue with this approach b'coz it gives desired output, besides giving an exception.

**Comment by afawcett** [comment]
Yes the web service request itself will have completed, the error means Apex gave up waiting for it, as Salesforce governors kicked in, as per this, https://www.salesforce.com/us/developer/docs/apexcode/Content/apex_gov_limits.htm, its 120 seconds. You can try looking at this however, https://help.salesforce.com/apex/HTViewSolution?id=000206743&language=en_US

**Comment by Sudha613** [comment]
Hi, 

I am trying to update picklist values of 2 picklist fields on Product record types. Below is my code:

MetadataService.Metadata[] metadataToUpdate = new List<MetadataService.Metadata>();  
FOR(RecordType rt : [SELECT Id, Name, DeveloperName, isActive, sObjectType FROM RecordType WHERE sObjectType = 'Product2']){
        MetadataService.RecordType objRT = new MetadataService.RecordType();
        objRT.active = rt.IsActive;
        objRT.label = rt.Name;
        objRT.fullName = rt.DeveloperName;
        MetadataService.RecordTypePicklistValue rtplv1 = new MetadataService.RecordTypePicklistValue();
        rtplv1.picklist = 'Aircraft_1__c';
        rtplv1.values = plvList;
        MetadataService.RecordTypePicklistValue rtplv2 = new MetadataService.RecordTypePicklistValue();
        rtplv2.picklist = 'Aircraft_2__c';
        rtplv2.values = plvList;
        lstRtPlv = new List<MetadataService.RecordTypePicklistValue>{rtplv1,rtplv2};
        rt.picklistValues = lstRtPlv;
        metadataToUpdate.add(rt);   
    } 
    List<MetadataService.SaveResult> results1 = service.updateMetadata(metadataToUpdate);
    MetadataServiceExamples.handleSaveResults(results1[0]);

This has to happen in a trigger so I have kept this code in future method. But the apex job fails with following error: First error: Error occured processing component Product2.NetJets_Card_Product. duplicate value found: <unknown> duplicates value on record with id: <unknown> (DUPLICATE_VALUE).

What's wrong?

**Comment by afawcett** [comment]
Firstly its probably better if you open a new issue, as this doesn't appear related to this now closed issue. Can you also paste the code into the new issue using [code style](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) its much easier to read.
