### ISSUE TITLE
How to display Dynamically coming multiselectpicklist Values as checkboxs?

### ISSUE THREAD

**Issue by mahesh10811f0011** [financialforcedev/apex-mdapi#43]
Hi Andrew Fawcett,
                                   Using metadata api i created multiselectpicklist.This created multiselectpicklist field dynamically I displayed on visualforce page(I was displayed all fields dynamically without using fieldset in an visualforce page).How to display comming Multiselectpicklist field values as checkboxes Dynamically in an visualforce page?

please help me....................

**Comment by yuvrajdeveloper** [comment]
Hi Andrew,
I need to show display the pageblocksection based on multiselect picklist chosen. 
Say for the example, I have the multipicklist field in contact object, where the values are one, two, three.
Whenever i choose "One" Option corresponding page block must be showned.

```
<apex:page standardController="Contact" showHeader="false">
    <apex:pageBlock >
        <apex:pageBlockSection >
            <apex:inputField value="{!contact.Choose_Number__c}">
                <apex:actionSupport event="onchange" reRender="ppc" />
            </apex:inputField>
        </apex:pageBlockSection>
        <apex:pageBlockSection title="PPC Test" id="ppc" rendered="{!contact.Choose_Number__c == 'PPC'}">
        </apex:pageBlockSection>
    </apex:pageBlock>
    </apex:form>
</apex:page>
```
Could you help me to achieve this?

**Comment by afawcett** [comment]
@yuvrajdeveloper this is not the correct issue, nor the correct repository to be asking this type of general vf question. I have however in this instance, responded to your other issue, lets continue chatting on that one.
