### ISSUE TITLE
System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission

### ISSUE THREAD

**Issue by sfdcprs** [financialforcedev/apex-mdapi#44]
Hi Andrew,

I am facing below exception when I log in as non admins. It works well for Sysadmin.
System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission. 

Apex runs in system mode how does Metadata API taking the permission of the user. Can you please help me in understanding this.

Thank you in advance.

**Comment by sivasank4sfdc** [comment]
Hi Andrew,
Hope you are doing great!

I've the below scenario, please give me your inputs on this,

I'm updating the CustomLabels as System administrator profile using VF page UI and I need to allow "Salesforce Platform" license profile users to update the custom labels using VF page. I have given the access to VF page, controller class and MetadataService class, but when I load VF page getting error as "WebService returned a SOAP Fault: INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission faultcode=sf:INSUFFICIENT_ACCESS faultactor=".

Is there any option to allow Salesforce Platform profile's users to update the Customlabels? please advise.

In case if we don't have option then I wish to try this as per below approach,
please advise will it work for my needs.

As @sfdcprs I'll write apex rest API to get the customlabels using autotoke (System Admin credentials) and implement the logic to update the custom labels.

Thanks in advance,
Sivasankar

**Comment by afawcett** [comment]
Sorry, its a requirement of the Salesforce Metadata API to have this, as its a very powerful API. 

Yes you can use oAuth to have the admin authenticate that the code can use their access on behalf of the running user. But be very careful where you store this token. I would not recommend using the user/pass oAuth flow (as shown by @sfdcprs above) as you will need to store those some place for your code to read them which also presents a security risk of them being found. The web based oauth flow is unfortunately harder to implement and i don't have a clean example at hand. 

Here is another thought.... why don't you stage the changes to the labels in a custom object, then have a job / page the admin user can run that processes them every now and again? Its not as elegant and realtime i know, but is a separate of responsibilities.

**Comment by azzaouimamine** [comment]
Hello,
You can use Named Credentials to store the Admin Credentials. It is available with OAuth2.0.
https://help.salesforce.com/articleView?id=named_credentials_about.htm&type=5
Amine

**Comment by Sivaranjanikannan05** [comment]
There was an unexpected error in your org which is preventing this assessment check from completing: System.CalloutException: Read timed out.
Please help me out i am struggling with thus error.
