### ISSUE TITLE
Failed to add Custom Button to the Layout RelatedList

### ISSUE THREAD

**Issue by BoonPlus** [financialforcedev/apex-mdapi#45]
Hi Andrew,

I tried to add a Custom Button to the OpportunityLineItem related list on the Opportunity layout. Got the "message=Field: relatedLists, value:RelatedLineItemList appears more than once," error when I ran the code below, any ideas why? Please advise.

Best Regards,

Paul

```
public PageReference updateLayout(){
    try {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();      

        // Read the Layout      
        MetadataService.Layout OPMPlayout = 
        (MetadataService.Layout) service.readMetadata('Layout', 
        new String[] { 'Opportunity-Opportunity Layout' }).getRecords()[0];

        // Add the Custom Button to the Layout relatedLists
        if(OPMPlayout.relatedLists==null)
            OPMPlayout.relatedLists = new List<MetadataService.relatedListItem>();
        MetadataService.relatedListItem OPMPrelatedListItem = new MetadataService.relatedListItem();
        OPMPrelatedListItem.relatedList = 'RelatedLineItemList';            
        if(OPMPrelatedListItem.customButtons==null)
            OPMPrelatedListItem.customButtons = new List<String>();
        OPMPrelatedListItem.customButtons.add('Mass_Price');            
        OPMPlayout.relatedLists.add(OPMPrelatedListItem);   

        // Update the Layout
        MetadataService.SaveResult[] OPMPresults = service.updateMetadata(new List<MetadataService.Metadata> { OPMPlayout });
        system.debug('OPMPresults = ' + OPMPresults);           
    } catch (Exception e) {
        return null;
    }
    return null;                    
}  
```

16:07:10:898 USER_DEBUG [300]|DEBUG|OPMPresults = 
(SaveResult:[apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), 
errors=(Error:[apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), 
field_order_type_info=(fields, message, statusCode), 
fields=null, 
fields_type_info=(fields, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), 
message=Field: relatedLists, value:RelatedLineItemList appears more than once, 
message_type_info=(message, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false), 
statusCode=FIELD_INTEGRITY_EXCEPTION, 
statusCode_type_info=(statusCode, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false)]), 
errors_type_info=(errors, http://soap.sforce.com/2006/04/metadata, null, 0, -1, false), 
field_order_type_info=(errors, fullName, success), 
fullName=Opportunity-Opportunity Layout, 
fullName_type_info=(fullName, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false), 
success=false, success_type_info=(success, http://soap.sforce.com/2006/04/metadata, null, 1, 1, false)])

I could manually add my Custom Button to the Layout Related List, below is the xml after it's added ...

![image](https://cloud.githubusercontent.com/assets/5788897/3792111/57efccfc-1b66-11e4-9a8e-f405a70da4be.png)

**Comment by cnaccio** [comment]
@BoonPlus did you ever run into any issues with updating page layouts/related lists due to field visibility permissions; I'm getting a FIELD_INTEGRITY_EXCEPTION as you did here, but with a slightly different cause? Also on another note have you had any issues with deleting custom fields? I'm only asking you because I'm building functionality very similar to the tool you posted above. Any help would be much appreciated. Thanks in advance!

**Comment by BoonPlus** [comment]
@cnaccio The field level permissions can be granted via the metadata api, which should be done before the field is added to the page layout. I haven't tried the deletefield method yet so I can't comment on it.
