### ISSUE TITLE
Code to add a CustomPageWeblink

### ISSUE THREAD

**Issue by Conga-Jereriah** [financialforcedev/apex-mdapi#52]
public static void createCustomPageWeblink()
{
  MetadataService.MetadataPort service = createService();		
  MetadataService.CustomPageWebLink customPageWeblink = new MetadataService.CustomPageWebLink();
    
  //no object name here, no spaces, single "_" allowed        
  customPageWeblink.fullName = 'CustomPageWeblink_Name';
  customPageWeblink.availability = 'online';
  customPageWeblink.displayType = 'link';
  customPageWeblink.encodingKey = 'UTF-8';                        
  customPageWeblink.hasMenubar = false;
  customPageWeblink.hasScrollbars = false;
  customPageWeblink.hasToolbar = false;
  customPageWeblink.height = 600;
  customPageWeblink.isResizable = false;
  customPageWeblink.linkType = 'url';
  //friendly name that is displayed on SFDc pages
  customPageWeblink.masterLabel = 'Label';
  customPageWeblink.openType = 'newWindow';
  customPageWeblink.position = 'none';
  customPageWeblink.protected_x = false;
  customPageWeblink.showsLocation = false;
  customPageWeblink.showsStatus = false;
  customPageWeblink.url = 'http://www.google.com';
		
  List<MetadataService.SaveResult> results = 
  service.createMetadata(
      new MetadataService.Metadata[] { customPageWeblink });		
  handleSaveResults(results[0]);
		
  //Optional: get the ID of the newly created Weblink
  /*
  String weblinkId = '';
  List<Weblink> weblinkIdList = [SELECT Id from WebLink WHERE Name = 'CustomPageWeblink_Name' LIMIT 1];                    
  weblinkId = (String) weblinkIdList.get(0).get('Id'); 
  */
}

**Comment by afawcett** [comment]
Added [here](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataServiceExamples.cls#L1137).
