### ISSUE TITLE
Failing Test Class

### ISSUE THREAD

**Issue by Conga-Jereriah** [financialforcedev/apex-mdapi#53]
As of today (maybe yesterday) the MetaDataCreateJobTest class is failing. 

The failure location is in the MetaDataCreateJob class at the following lines of code:

```
public void finish(Database.batchableContext info)
{ 
    // Start new job for those not yet processed?
    if (new JobIterable(items).Iterator().hasNext())
```

line 101 ------>            run(sessionId, items, callback);  
        else // If all components processed if all now processed
            callback.deployComplete(items);
    }

```
public static void run(String sessionId, List<Item> items, IMetadataAsyncCallback callback)
{       
    // Batch scope of 1 for now, though this code could be enhanced to group by Metadata component type
    //   and issue max of 10 components per call to 'create' (as per Metadata API Documentation)
    Integer maxScopeSize = 1;

    // Start a job in 1 minutes time to process the given components, inform the callback of the Id
```

Line 124 ------>        callback.batchId( System.scheduleBatch( new MetadataCreateJob(sessionId, items, callback), 'Metadata Create', 1, maxScopeSize ) );  
    }

ERROR DETAILS:
Apex Test Result Detail

Time Started    10/7/2014 11:17 AM
Class   MetadataCreateJobTest
Method Name testCreateField
Pass/Fail   Fail
Error Message   System.AsyncException: The Apex job named "Metadata Create" is already scheduled for execution.
Stack Trace Class.MetadataCreateJob.run: line 124, column 1
Class.MetadataCreateJob.finish: line 101, column 1

**Comment by Conga-Jereriah** [comment]
Hey Andy,

Long time, no talk. I hope all is well. Question for you, is there a method
or something that can be written to check the status of a metadata update
call? I need to make sure my attempted weblink update has run it's course
before proceeding. It actually comes back to the fact that the version I
started using doesn't return an error when an update fails. For me, it's
when I try and force bad syntax into the URL field of a weblink. The
Try/Catch works on insert, but apparently no Exception is thrown for an
update.

Thanks in advance for the help.

Cheers,


~J

Jereriah "J" Manning | Application Developer

Conga | www.congamerge.com

+1 (303) 381-6307 p | +1 (303) 335-5987 m


CongaSphere <http://www.congasphere.com/> | Twitter
<https://twitter.com/CongaMerge> | Videos
<http://www.youtube.com/user/CongaMerge> | LinkedIn
<https://www.linkedin.com/company/conga>
Technical Support: www.congasphere.com

**Comment by afawcett** [comment]
Sure, take a look at the handleXXX methods here, https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataServiceExamples.cls#L1073

**Comment by Conga-Jereriah** [comment]
Oh nice. There's the piece I was missing.

Still haven't rolled this out officially, but it's (Safe Harbor) on the
near horizon.

Thanks again!!!!
~J



Jereriah "J" Manning | Application Developer

Conga | www.congamerge.com

+1 (303) 381-6307 p | +1 (303) 335-5987 m


CongaSphere <http://www.congasphere.com/> | Twitter
<https://twitter.com/CongaMerge> | Videos
<http://www.youtube.com/user/CongaMerge> | LinkedIn
<https://www.linkedin.com/company/conga>
Technical Support: www.congasphere.com

**Comment by afawcett** [comment]
Great, happy to help, good luck with the rollout! :+1:
