### ISSUE TITLE
Insufficient access; cannot execute Metadata operation with PAC enabled session id

### ISSUE THREAD

**Issue by seeflat** [financialforcedev/apex-mdapi#6]
I have been implementing a solution with you library (It is awesome thanks for all the work). I had my test working and creating visualforce pages successfully 2 days ago, now I am getting the exception message in the title.
I have tried googling this but could not find any information. Have you experienced this before?

**Comment by aggressiveasparagus** [comment]
Spectacular and profound detective work! The same problem reared its head with the Spring '15 release and your discussion here floated to the top of the Google search results. Thank you guys!
https://developer.salesforce.com/forums?id=906F0000000AyTgIAK

**Comment by psullivan4** [comment]
I'm still having this issue. 
I did the following:
- Confirmed Package has Unrestricted API access
- Uncheck Lock to Session ID in security. 

Are there other things I'm missing?

**Comment by afawcett** [comment]
Have you got any other Session Id restrictions enabled?

**Comment by afawcett** [comment]
@seeflat i'd like to close this one out, but if you want to pick this up again, please post back. 👍
