### ISSUE TITLE
How to retrieve Username, Profile name and home page component usng SOQL query..? Can any one help..?

### ISSUE THREAD

**Issue by KumarCpq** [financialforcedev/apex-mdapi#61]

**Comment by afawcett** [comment]
You should be able to use the [listMedata](http://www.salesforce.com/us/developer/docs/api_meta/Content/meta_listmetadata.htm) method with the HomePageLayout metadata component type. I just used [Salesforce Developer Workbench tool](https://workbench.developerforce.com/metadataDescribeAndList.php?type=HomePageLayout) (which uses the Metadata API) to confirm.

![screen shot 2015-01-24 at 12 11 20](https://cloud.githubusercontent.com/assets/1167760/5887331/e14f7162-a3c1-11e4-82fd-04b29d869472.png)
