### ISSUE TITLE
Can't update field level security

### ISSUE THREAD

**Issue by praty23** [financialforcedev/apex-mdapi#64]
Hi,

I am unable to set the field level security for a profile. 

I used the below mentioned method for a field testfls__c in the concap__c object - 

```

  public static void updateFieldLevelSecurity() 
    {
        MetadataService.MetadataPort service = createService();
        MetadataService.Profile admin = (MetadataService.Profile) service.readMetadata('Profile', new String[] { 'Admin' }).getRecords()[0];
        MetadataService.ProfileFieldLevelSecurity fieldSec = new MetadataService.ProfileFieldLevelSecurity();
        fieldSec.field='Concap__c.Testfls__c';
        fieldSec.editable=true;
        admin.fieldPermissions  = new MetadataService.ProfileFieldLevelSecurity[] {fieldSec} ;
        List<MetadataService.SaveResult> results =      
            service.updateMetadata(
                new MetadataService.Metadata[] { admin });              
        handleSaveResults(results[0]);      
    }
```

I was getting a Attempt to de-reference a null pointer exception in handleSaveResults method but the success in the callout response is coming as false.
Could you please look into the issue and also how do I figure out fullNames of all the custom profile in my org to make the code run for every profile and not just for admin.

(6341283265)|CALLOUT_RESPONSE|[8625]|<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://soap.sforce.com/2006/04/metadata">soapenv:Body<updateMetadataResponse><result><fullName>Admin</fullName><success>false</success></result></updateMetadataResponse>/soapenv:Body/soapenv:Envelope

Thanks in Advance!!!

**Comment by attelli** [comment]
Hi,

How can i identify whether a field can be given edit permission using metadata api.

For Example : For the fields "Partner Account" and "Customer Portal Account" of Account object we cannot give the edit permission through the salesforce profile UI, how can we identify these fields.

**Comment by afawcett** [comment]
If your question is to pre-check if a specific profile / permission will grant permission for a given field, you can use Apex directly with SOQL to query the Permission Set objects (these also apply for profiles). See the [docs](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_permissionset.htm) for these objects and which ones to query (scroll to the bottom for a schema diagram).

**Comment by bhashitjoshi** [comment]
Hello praty23 ,
I am trying to change FLS of field created from apex.
But i am not able to create service.readMetadata() and handleSave(), can you please provide the code for this functions
Thanx in advance.
