### ISSUE TITLE
access foldershare using metadata API

### ISSUE THREAD

**Issue by Reshma-jewrani** [financialforcedev/apex-mdapi#70]
I was trying to share a report using the Metadata,FolderShare class but I am geting an error.
 Can you help me with this?
 I saw a thread above with respect to this. Were you able to do this?
 I am trying it like this:
 MetadataService.ReportFolder rfa = (MetadataService.ReportFolder) service.readMetadata(‘ReportFolder’, new String[]{‘test’}).getRecords()[0];

MetadataService.FolderShare folderShareService = new MetadataService.FolderShare();
 folderShareService.accessLevel = ‘View';
 folderShareService.sharedTo = ‘AllInternalUsers';
 folderShareService.sharedToType = ‘Organization';
 rfa.folderShares.add(folderShareService);
 service.updateMetadata( new MetadataService.Metadata[] { rfa });

**Comment by afawcett** [comment]
Thanks, what error are you getting?

**Comment by Reshma-jewrani** [comment]
Unknown exception occurred while processing your request.
I will send you a screenshot im some time.

Sent from my Windows Phone
________________________________

**Comment by Reshma-jewrani** [comment]
Have a look at this screenshot: http://www.screencast.com/users/Reshma2003/folders/Default/media/35bc726b-c26a-4b09-af66-bc7ebf63f877

The code-base I am using is:

MetadataService.MetadataPort service = new MetadataService.MetadataPort();
service.SessionHeader = new MetadataService.SessionHeader_element();
service.SessionHeader.sessionId = UserInfo.getSessionId();

MetadataService.ReportFolder rfa = (MetadataService.ReportFolder) service.readMetadata('ReportFolder', new String[]{'test'}).getRecords()[0];
System.debug('rfa==='+ rfa);
System.debug('rfa.folderShares======'+ rfa.folderShares);

MetadataService.FolderShare folderShareService = new MetadataService.FolderShare();
folderShareService.accessLevel = 'View';
folderShareService.sharedTo = 'AllInternalUsers'; 
folderShareService.sharedToType = 'Organization';
rfa.folderShares.add(folderShareService);

List<MetadataService.SaveResult> results = service.updateMetadata( new MetadataService.Metadata[] { rfa });

**Comment by Reshma-jewrani** [comment]
You got a chance to look into this?

**Comment by afawcett** [comment]
It's hard to know what is going on here, as the exception your getting is an internal Salesforce one, i don't have access to decode these. Can you raise a Salesforce support case and ask them to give us the underlying error message? You may need to give them the actual SOAP XML request being sent to reproduce the error, to do this take a look at the Apex Debug log and you will find this, copy paste the XML and include as part of your case (would be good to reference here as well).

**Comment by ramkosals** [comment]
Hi afa

I am too getting error while using foldershares object

can you find where I am failed 
MetadataService.MetadataPort service = new MetadataService.MetadataPort();
List<MetadataService.ListMetadataQuery> queries = new List<MetadataService.ListMetadataQuery>();
service.SessionHeader = new MetadataService.SessionHeader_element();
service.SessionHeader.sessionId = UserInfo.getSessionId();

MetadataService.ListMetadataQuery queryDocumentFolder = new MetadataService.ListMetadataQuery();
queryDocumentFolder.type_x = 'DashboardFolder';
queries.add(queryDocumentFolder);       
MetadataService.FileProperties[] fileProperties = service.listMetadata(queries, 30);
List<String> folderNames = new List<String>();
for(MetadataService.FileProperties fileProperty : fileProperties)
    folderNames.add(fileProperty.fileName.replace('dashboards/', ''));

List<MetadataService.DashboardFolder> folder = 
    (List<MetadataService.DashboardFolder>) 
        service.readMetadata('DashboardFolder', folderNames).getRecords();

//system.debug('folder '+folder );


Above is the code 

I am getting following error


EXCEPTION: System.CalloutException: Web service callout failed: Unable to parse callout response. Apex type not found for element folderShares
STACKTRACE: Class.MetadataService.MetadataPort.readMetadata: line 9325, column 1
AnonymousBlock: line 14, column 1
AnonymousBlock: line 14, column 1
LINE: 9325 COLUMN: 1

**Comment by afawcett** [comment]
Salesforce have simplified the sharing metadata types in Spring'15. 

I'll try this again once i update the API to Spring'15, now that it has rolled out this weekend.

**Comment by afawcett** [comment]
Take a look at the readFolder example [here](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataServiceExamples.cls#L911) (for ReportFolder), which is now working!  The fix i made applies to other folder types, so you should find the DashboardFolder is also now working. Let me know if your still having a issues.
