### ISSUE TITLE
Retrieving VF page code using Metadata API

### ISSUE THREAD

**Issue by ganeshchedella** [financialforcedev/apex-mdapi#72]
trying to retrieve xml content of VF page using Metadata API. Can someone help me. I downloaded MetadataService.cls from github. Wondering which method to use.

Thank you in advance.

**Comment by afawcett** [comment]
You have two options, firstly, the easiest, you can use SOQL, just query the ApexPage object.

~~~~
System.debug([select Markup from ApexPage where Name = 'metadatabrowser'].Markup);
~~~~

Secondly if you want to use the Metadata API you can do this...

~~~~
MetadataService.MetadataPort service = MetadataServiceExamples.createService();     	    
    MetadataService.ApexPage apexPage = 
			(MetadataService.ApexPage) service.readMetadata('ApexPage', 
				new String[] { 'metadatabrowser' }).getRecords()[0];
System.debug(EncodingUtil.base64Decode(apexPage.content).toString());
~~~~
