### ISSUE TITLE
How to Integrate salesforce and Xero?

### ISSUE THREAD

**Issue by mahesh10811f0011** [financialforcedev/apex-mdapi#74]
Salesforce Integartion with Xero is posiisble or not?It's possible give me some details about salesforce integration with Xero

**Comment by afawcett** [comment]
This is not the correct forum to ask such a question, as this repo is only about the Salesforce Metadata API, as i said on my blog you can find that Zero has an REST based API, and of course Apex can consume REST API's, so you have the basics, after some more Googling I'm sure you can find some useful information and perhaps asking any further questions on Salesforce StackExchange.
