### ISSUE TITLE
Is there a way to exclude fields from a Page Layout?

### ISSUE THREAD

**Issue by BoonPlus** [financialforcedev/apex-mdapi#75]
There's a way to exclude buttons from a Page Layout (i.e. excludeButtons), is there a way to exclude fields from a Page Layout?

    public class Layout extends Metadata {
        public String type = 'Layout';
        public String fullName;
        public String[] customButtons;
        public MetadataService.CustomConsoleComponents customConsoleComponents;
        public Boolean emailDefault;
        public String[] excludeButtons;
        ...

**Comment by afawcett** [comment]
No sadly not, these feature is only there to exclude system defined buttons btw.

**Comment by BoonPlus** [comment]
I had thought that would be the case. Thanks for getting back to me.
