### ISSUE TITLE
Can't update field-level security within a for loop

### ISSUE THREAD

**Issue by david-berman** [financialforcedev/apex-mdapi#76]
Hi,

I can update the FLS for one field at a time using:
MetadataServiceExamples.updateFieldLevelSecurity( 'Admin', 'Test_Object__c',
'Test_Field__c');

I created version of the original class to which I can pass the object name and field name.

I use a loop to create a bunch of fields that I'm reading from another object (with field label, field api name, field type, length, etc) and as part of that loop I want to update the FLS.  The problem arises in the if(bContinue == true) block below.  There is no error message, but no updates occur (the fields are added correctly though).  

I hope you can help.  Thank you!
-David

String sObjectAPIName = 'Test_Object__c';

List<Object_Configuration__c> configs = new List<Object_Configuration__c>
([Select Object_Name__c, Field_Label__c, Field_API_Name__c, Field_Type__c, Field_Length__c, Field_Precision__c, Field_Help_Text__c from Object_Configuration__c
where Object_Name__c =: sObjectAPIName
]);

Map<ID, Object_Configuration__c> configMap = new Map<ID, Object_Configuration__c>
([Select Object_Name__c, Field_Label__c, Field_API_Name__c, Field_Type__c, Field_Length__c, Field_Precision__c, Field_Help_Text__c
from Object_Configuration__c]);

for(Object_Configuration__c ocs : configs)
{
try
{
Boolean bContinue = false;

if(configMap.get(ocs.Id).Field_Type__c == 'Boolean')
{
MetadataServiceExamples.createFieldTypeBoolean( configMap.get(ocs.Id).Object_Name__c,
configMap.get(ocs.Id).Field_Label__c,
configMap.get(ocs.Id).Field_API_Name__c,
configMap.get(ocs.Id).Field_Help_Text__c);
bContinue = true;
}
[...]
else{}

if(bContinue == true)
{
MetadataServiceExamples.updateFieldLevelSecurity( 'Admin', configMap.get(ocs.Id).Object_Name__c,
configMap.get(ocs.Id).Field_API_Name__c);
    
}
}
catch(Exception e)
{
if(e.getMessage().contains('DUPLICATE_DEVELOPER_NAME')) continue;
else system.debug('+++++++ OTHER ERROR: ' + e.getMessage());
}
}

**Comment by afawcett** [comment]
Sorry for the delay on this, can you check you have the latest MetadataServiceExamples class. The method your calling, updateFieldLevelSecurity, internally calls (or should call) handleSaveResults to parse the response and throw an exception if an error occurs. If that is the case, it maybe that the Metadata API itself is returning a success status incorrectly, which maybe a bug. In the debug logs you should also be able to see the actually HTTP request and responses in XML SOAP form, can you locate the actual response and see if it indeed shows any errors the handling code is not spotting perhaps?

**Comment by afawcett** [comment]
Also keep in mind that you can only make 100 HTTP callouts per Apex execution context.

**Comment by afawcett** [comment]
@david-berman let me know if my responses above don't help.
