### ISSUE TITLE
createService() Error

### ISSUE THREAD

**Issue by chris760** [financialforcedev/apex-mdapi#78]
Hi Andrew,

I just found your MetadataServices class today (the one here https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataService.cls). I copied the class, test class, and examples class in to my salesforce developer org (along with all the other classes just to be on the safe side) and created a remote site setting for https://na16.salesforce.com (the URL of my dev org). When I try to run any of your examples however (like the customObject example), I get the following error, “Method does not exist or incorrect signature: createService()”. 

What's weird is that I can't find the actual "createService()" method in the current MetadataServices class that you have posted on here (unless I'm totally missing something), so I think that might be what's causing the problem.

The code that I'm currently trying to execute in the salesforce developer console ExecuteAnonymous window is the following:

MetadataService.MetadataPort service = createService();
MetadataService.CustomObject customObject = new MetadataService.CustomObject();
customObject.fullName = 'Test__c';
customObject.label = 'Test';
customObject.pluralLabel = 'Tests';
customObject.nameField = new MetadataService.CustomField();
customObject.nameField.type_x = 'Text';
customObject.nameField.label = 'Test Record';
customObject.deploymentStatus = 'Deployed';
customObject.sharingModel = 'ReadWrite';
List<MetadataService.SaveResult> results = service.createMetadata( new MetadataService.Metadata[] { customObject }); handleSaveResults(results[0]);

Any ideas/suggestions would be much appreciated.

Thanks!

**Comment by RandyTrigg** [comment]
Hi there,

I'm also using MetadataService for the first time (in a sandbox).  I found definitions for createService and handleSaveResults in the examples class MetadataServiceExamples, so you can either copy them from there, or point to them if you've defined that class.

But now I get a timeout error from the WebServiceCallout.invoke method that is called whenever MetadataService computes results.  Could you let me know if you've gotten past that?

Thanks,

   - Randy

**Comment by RandyTrigg** [comment]
Never mind. I now see how to increase timeout_x from the createService method.  For details, see https://github.com/financialforcedev/apex-mdapi/issues/77.

**Comment by afawcett** [comment]
@chris760 When running code in annonymous mode, you need to full qualify the static methods you call by the class those methods belong in, in this case createService and handleXXXX methods reside in MetadataServiceExamples.cls. However the handleXXXX methods where private, so i've now updated them to public, so download a deploy a new MetadataServiceExamples class then the following will work...

		MetadataService.MetadataPort service = MetadataServiceExamples.createService();
		MetadataService.CustomObject customObject = new MetadataService.CustomObject();
		customObject.fullName = 'Test__c';
		customObject.label = 'Test';
		customObject.pluralLabel = 'Tests';
		customObject.nameField = new MetadataService.CustomField();
		customObject.nameField.type_x = 'Text';
		customObject.nameField.label = 'Test Record';
		customObject.deploymentStatus = 'Deployed';
		customObject.sharingModel = 'ReadWrite';
		List<MetadataService.SaveResult> results = 		
			service.createMetadata(
				new MetadataService.Metadata[] { customObject });		
		MetadataServiceExamples.handleSaveResults(results[0]);

**Comment by rgupta124** [comment]
Hi Can some one help me test class  for the MetadataServiceExamples .

**Comment by vivekgithub6** [comment]
Hi, Can any one help in writing the test class fro MetadataServiceExample class, I wrote but not  getting full code coverage.  A sample test class will help me out. Thanks in advance.

**Comment by ankit15patel** [comment]
Hi,
I'm Trying To create a Remote Site By Metadata Service. But It gives an error of 'Unauthorized endpoint'. The Remote site will by my ORG Base URL. 
Thanks in advance.
