### ISSUE TITLE
Updating an existing custom label and its translations

### ISSUE THREAD

**Issue by ima87** [financialforcedev/apex-mdapi#79]
Hi Andrew,

I was able to save new custom labels and translations by using MetadataService class and handleSaveResults and createService methods on MetadataServiceExamples class but was unable to read them back using readMetadata method. 

Will it be possible to read and update an existing custom label and its translation using MetadataService? If yes, could you please publish an example for that? 

Many Thanks.

**Comment by afawcett** [comment]
See this [example](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataServiceExamples.cls#L1117).
