### ISSUE TITLE
bulk retrieve with metadata api

### ISSUE THREAD

**Issue by maryembourhi** [financialforcedev/apex-mdapi#80]
i was wondering about how to do bulk retrieve with metadata api?
i have tried to make a package.xml with all the types (with a loop) but it always fails.

I have tried to do the following: 

 for(SelectOption item:MetaDataTypes){
      	 MetadataService.PackageTypeMembers packageType = new MetadataService.PackageTypeMembers();
		packageType.name = item.getValue();//chosenItems.get(name); //should be the one chosen in the current tab picklist
		packageType.members = new String[] { MetadataFolder, '*' };
        retrieveRequest.unpackaged.types.add(packageType);
}
      
     	AsyncResult = service.retrieve(retrieveRequest);
     
MetaDataTypes: is a list of all the metadata types Names in an environnement.

**Comment by afawcett** [comment]
Well not all types support wild cards, check the Metadata API Developers guide for a list of those that do. Also you don't say how it fails, are you seeing any errors, if so what are they?

**Comment by maryembourhi** [comment]
thank you, i have tried another way and it worked.

2015-03-20 8:33 GMT+00:00 Andrew Fawcett <notifications@github.com>:

**Comment by maryembourhi** [comment]
I have tried to loop through all the metadata instead of using a wild card

2015-03-20 9:14 GMT+00:00 Maryem Bourhi <m.bourhi@gmail.com>:

**Comment by afawcett** [comment]
Ok you may encounter some limits with large and complex orgs tbh, but good luck, and let me know if can help further. :+1:
