### ISSUE TITLE
upsertMetadata and createMetadata in a managed package not creating CustomFields

### ISSUE THREAD

**Issue by natalieturner** [financialforcedev/apex-mdapi#81]
This works perfectly in my development environment, but as soon as I package it into a managed package (despite adding the remote site settings), my fields are not creating and there is no error displaying.  I'm trying to copy a field from a custom object to the Salesforce Account object, and I'm not sure what is occurring differently in the managed package that works in the development area.  I've accounted (at least I think) for namespaces as well as remote sites.  Any ideas?

**Comment by afawcett** [comment]
There is some error handling code in the MetadataServiceExamples class for these two methods are you using that? If so, you should be able to see in the debug log the HTTP request and response made to the Metadata API, does that show any errors even if the Apex code receiving it does not report any?

**Comment by natalieturner** [comment]
It was a namespace issue as it turns out!  Thanks for the response - really appreciate it! :)

**Comment by afawcett** [comment]
Your welcome! :+1:
