### ISSUE TITLE
Issues with metadataFolder

### ISSUE THREAD

**Issue by maryembourhi** [financialforcedev/apex-mdapi#82]
i have tried to deploy this demo, but i have a problem with document, emailTemplates, report as they are in other folders,consequently i cannot retrieve them, i suppose the inputText Folder is related to this but i don't know how.

Could you please help me on this.

**Comment by afawcett** [comment]
Hi, which demo are you talking about?

**Comment by maryembourhi** [comment]
this one : https://github.com/financialforcedev/apex-mdapi

2015-03-27 14:52 GMT+00:00 Andrew Fawcett <notifications@github.com>:

**Comment by afawcett** [comment]
Thats just a link to this repository, are you talking about the Retrieve Demo? If so, yes, enter the 'Developer Name' of the folder in that field and select Document or Email Template from the drop down and it should list the things in that folder.

**Comment by maryembourhi** [comment]
ok i see, can i retrieve the content of things in that folder?

2015-03-27 16:35 GMT+00:00 Andrew Fawcett <notifications@github.com>:

**Comment by afawcett** [comment]
Yep you can.

**Comment by maryembourhi** [comment]
what i'am doing is retrieving metadata from an organization, with the
following


MetadataService.PackageTypeMembers packageType = new
MetadataService.PackageTypeMembers();

 packageType.name = chosenTypeItem; //for example:  myTrigger

 packageType.members = new String[] { Type };// for example:  apexTrigger

 retrieveRequest.unpackaged.types.add(packageType);


what i would like to is to retrieve emailTemplate/reports and Documents, to
do so i do this

queryLayout.type_x = MetaDataType;

 if(MetaDataType=='Document'){

 queryLayout.type_x = 'DocumentFolder';

 }


but this way i only get the names of the elements of the documentFolder,
and i would like to retrieve the contents too , but i have no idea how to
do so, could you please help me


I hope you understood my question. Thanks a lot for your quick response



2015-03-27 18:21 GMT+00:00 Andrew Fawcett <notifications@github.com>:

**Comment by afawcett** [comment]
What i usually do is use my favourite IDE, Force.com IDE or MavensMate and use its project contents UI to include the things i want, then inspect the package.xml file after. You can then mimic the package.xml structure in code via the MetadataService.Package to repeat what you want with the retrieve API.

**Comment by maryembourhi** [comment]
gd idea, thanks alot for your help

2015-03-30 14:19 GMT+00:00 Andrew Fawcett <notifications@github.com>:

**Comment by afawcett** [comment]
Welcome! :+1:
