### ISSUE TITLE
Can't retrieve Approval Processes!

### ISSUE THREAD

**Issue by SaraELA** [financialforcedev/apex-mdapi#83]
Hi, 
Thank you andrew, for stepping forward to help!

My use case is to retrieve Approval Processes from another organization. For this, I genarated my own MetadataAPI wsdl and MetadataService class for version 33. But still, I could not retrieve, or even list Approval Processes of any organization.

Could I request you to look into this since it's very urgent ?
Many Thanks!

**Comment by afawcett** [comment]
I'm afraid i cannot give an guarantees on when i can look into this, this is an open source community project and as such subject to the availability of those that contribute to it. I do have on my list a task to update the library to API 33 and in doing so will for sure try your use case. 

In the meantime is there any reason why you didn't try with the MetadataService.cls in this repository, this class has been enhanced to fix some issues the default one generated by the platform has, such as issues with the retrieveMetadata operation.

**Comment by afawcett** [comment]
[Here](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataServiceExamples.cls#L1128) is an example of reading an Approval Process, please make sure to use the latest MetadataServices.cls from this repo.

**Comment by SaraELA** [comment]
Thank you Andrew, I really do appreciate your help.

2015-04-08 16:53 GMT+00:00 Andrew Fawcett <notifications@github.com>:

> Closed #83 <https://github.com/financialforcedev/apex-mdapi/issues/83>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/financialforcedev/apex-mdapi/issues/83#event-276414100>
> .
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*
