### ISSUE TITLE
Issue with Standard Fields

### ISSUE THREAD

**Issue by SaraELA** [financialforcedev/apex-mdapi#85]
Hi Andrew, 

I was wondering about how to do retrieve and deploy standard Fields using Metadata API. I read in Metadata API documentation , that standard fields can be retrieved as a "CustomField" Type. However, for Metadata API type "CustomField", I only get custom fields.

Thank you.

**Comment by afawcett** [comment]
What code are you using?

**Comment by SaraELA** [comment]
Hi Andrew,

I'm using MetadataAPI wsdl and MetadataService class for *version 33. *


*//fills the list of metadataTypes and gives default value to the chosen meta*

public static List<SelectOption> initialisation(string sessionId){
        List<SelectOption> MetaDataTypes=new List<SelectOption>();
        MetadataService2.MetadataPort service = createService(sessionId);
        System.debug('initialisation retrieve utils');
        MetadataService2.DescribeMetadataResult describeResult =
service.describeMetadata(33);
          List<String>  metadataTypeNames = new List<String>();
    for(MetadataService2.DescribeMetadataObject metadataObject :
describeResult.metadataObjects)
    {      metadataTypeNames.add(metadataObject.xmlName);
            system.debug('xxxxxx'+metadataObject.xmlName);
      // Include child Metadata Types (such as CustomField,
ValidationRule etc..)
      if(metadataObject.childXmlNames!=null)
        for(String childXmlName : metadataObject.childXmlNames)
                if(childXmlName!=null){
            metadataTypeNames.add(childXmlName);
                    system.debug('cccccc'+ childXmlName);}
    }

    // Sort Metadata Types
    metadataTypeNames.sort();
    MetaDataTypes = new List<SelectOption>();
        for(String metadataTypeName : metadataTypeNames){

      MetaDataTypes.add(new SelectOption(metadataTypeName, metadataTypeName));
          }

return MetaDataTypes;
  }

*//list MetadataItems*

 public static List<ItemSelection> listMetadataItems(String
SessionId,String MetaDataType)
  {
    // List Metadata items for the selected Metadata Type
    List<ItemSelection> MetaDataItems = new List<ItemSelection>();

    MetadataService2.MetadataPort service = createService(SessionId);
    List<MetadataService2.ListMetadataQuery> queries = new
List<MetadataService2.ListMetadataQuery>();
    MetadataService2.ListMetadataQuery queryLayout = new
MetadataService2.ListMetadataQuery();

   queryLayout.type_x = MetaDataType;
             queries.add(queryLayout);}
    MetadataService2.FileProperties[] fileProperties =
service.listMetadata(queries, 33);

    // Sort
    List<String> fullNames = new List<String>();
    if(fileProperties!=null)
    {
      for(MetadataService2.FileProperties fileProperty : fileProperties)
        fullNames.add(fileProperty.fullName);
      fullNames.sort();
      for(String fullName : fullNames)
        MetaDataItems.add(new ItemSelection(new
SelectOption(fullName,EncodingUtil.urlDecode(fullName,
'UTF-8')),false));
    }
    return MetaDataItems;

  }

*Normally, for Metadata Type "CustomField", I suppose to get Standard
Fields as well (Metadata API documentation). *

I was also wondering if it's possible to *deploy* standard Objects and
*Fields* in other organizations.


Thank you.


2015-04-14 20:19 GMT+00:00 Andrew Fawcett <notifications@github.com>:

> What code are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/financialforcedev/apex-mdapi/issues/85#issuecomment-93048434>
> .
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*

**Comment by afawcett** [comment]
Why are you not using the MetadataService.cls from this repo?

**Comment by SaraELA** [comment]
Hi,

I'm using my own MetadataService.cls for version 33, in order to get new
version of *Metadata Types list*. However, I already tried to use
MetadataService.cls
from the repo, and *I still can't retrieve or deploy Standard Fields*.


Thank you.

2015-04-16 9:00 GMT+00:00 Andrew Fawcett <notifications@github.com>:

> Why are you not using the MetadataService.cls from this repo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/financialforcedev/apex-mdapi/issues/85#issuecomment-93683625>
> .
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*

**Comment by afawcett** [comment]
Ok can you include your updated code using the MetadataService.cls from the repo in a Gist or formatted as code in this issue so its easier for me to read. Also tell me clearly at what line (easier if you use a Gist link reference) your getting an error and what it is.

**Comment by SaraELA** [comment]
Hi Andrew,

Actually, I'm not getting any error. I'm using the same code from the repo,
but I still can't retrieve standard fields.



Thank you.

2015-04-19 10:30 GMT+00:00 Andrew Fawcett <notifications@github.com>:

> Ok can you include your updated code using the MetadataService.cls from
> the repo in a Gist or formatted as code in this issue so its easier for me
> to read. Also tell me clearly at what line (easier if you use a Gist link
> reference) your getting an error and what it is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/financialforcedev/apex-mdapi/issues/85#issuecomment-94259942>
> .
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*

**Comment by afawcett** [comment]
Have you tried looking at my FAQ blog (linked from README) and review the component names of standard object custom fields via the Developer Workbench tool?

**Comment by SaraELA** [comment]
Yes, I did. My problem doesn't concern custom fields of standard objects,
it's actually about standard fields.

2015-05-05 13:11 GMT+00:00 Andrew Fawcett <notifications@github.com>:

> Have you tried looking at my FAQ blog (linked from README) and review the
> component names of standard object custom fields via the Developer
> Workbench tool?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/financialforcedev/apex-mdapi/issues/85#issuecomment-99074308>
> .
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*

**Comment by afawcett** [comment]
Oh i see.... Sorry!

Looks like this might be a gap, see here...

https://developer.salesforce.com/forums?id=906F00000009CWNIA2

Also here....

http://www.salesforce.com/us/developer/docs/api_meta/Content/customfield.htm

"Only standard fields that you can customize are supported, that is, standard fields to which you can add help text or enable history tracking or Chatter feed tracking. Other standard fields aren't supported, including system fields (such as CreatedById or LastModifiedDate) and autonumber fields. All standard picklist fields are supported except for Lead.CampaignMemberStatus, Opportunity.ForecastCategoryName, and Order.Status."

**Comment by SaraELA** [comment]
I can't retrieve standard fields that can be  customized.

2015-05-05 13:24 GMT+00:00 Andrew Fawcett <notifications@github.com>:

> Oh i see.... Sorry!
>
> Looks like this might be a gap, see here...
>
> https://developer.salesforce.com/forums?id=906F00000009CWNIA2
>
> Also here....
>
>
> http://www.salesforce.com/us/developer/docs/api_meta/Content/customfield.htm
>
> "Only standard fields that you can customize are supported, that is,
> standard fields to which you can add help text or enable history tracking
> or Chatter feed tracking. Other standard fields aren't supported, including
> system fields (such as CreatedById or LastModifiedDate) and autonumber
> fields. All standard picklist fields are supported except for
> Lead.CampaignMemberStatus, Opportunity.ForecastCategoryName, and
> Order.Status."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/financialforcedev/apex-mdapi/issues/85#issuecomment-99076714>
> .
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*

**Comment by SaraELA** [comment]
Normally, those standard fields that are supported, suppose to be retrieved
with custom fields

2015-05-05 13:28 GMT+00:00 ELALAOUI SARA <sara.elalaoui92@gmail.com>:

> I can't retrieve standard fields that can be  customized.
>
> 2015-05-05 13:24 GMT+00:00 Andrew Fawcett <notifications@github.com>:
>
>> Oh i see.... Sorry!
>>
>> Looks like this might be a gap, see here...
>>
>> https://developer.salesforce.com/forums?id=906F00000009CWNIA2
>>
>> Also here....
>>
>>
>> http://www.salesforce.com/us/developer/docs/api_meta/Content/customfield.htm
>>
>> "Only standard fields that you can customize are supported, that is,
>> standard fields to which you can add help text or enable history tracking
>> or Chatter feed tracking. Other standard fields aren't supported, including
>> system fields (such as CreatedById or LastModifiedDate) and autonumber
>> fields. All standard picklist fields are supported except for
>> Lead.CampaignMemberStatus, Opportunity.ForecastCategoryName, and
>> Order.Status."
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/financialforcedev/apex-mdapi/issues/85#issuecomment-99076714>
>> .
>>
>
>
>
> --
> *Sara ELALAOUI *
>
>
> *Élève Ingénieur en Génie Informatique École Nationale des Sciences
> Appliquées de Safi**Université Cadi Ayad - Maroc*
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*

**Comment by afawcett** [comment]
In the MetadataServiceExamples.updatePicklist method it retrieves a custom field on the Lead standard object like so, are you saying this doesn't work for you?


	    // Read Custom Field
	    MetadataService.CustomField customField = 
			(MetadataService.CustomField) service.readMetadata('CustomField', 
				new String[] { 'Lead.picklist__c' }).getRecords()[0];

**Comment by SaraELA** [comment]
No. The problem is :  In the
MetadataRetrieveController.retrieveMetadataItem method it retrieves only
custom Fields when MetadataType="CustomField". Normally, it suppose to
retrieve supported standard fields,such as Account.Industry, as well.


Thanks.

2015-05-17 11:30 GMT+00:00 Andrew Fawcett <notifications@github.com>:

> In the MetadataServiceExamples.updatePicklist method it retrieves a custom
> field on the Lead standard object like so, are you saying this doesn't work
> for you?
>
>     // Read Custom Field
>     MetadataService.CustomField customField =
>         (MetadataService.CustomField) service.readMetadata('CustomField',
>             new String[] { 'Lead.picklist__c' }).getRecords()[0];
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/financialforcedev/apex-mdapi/issues/85#issuecomment-102785864>
> .
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*

**Comment by SaraELA** [comment]
but it doesn't.

2015-05-18 15:20 GMT+00:00 ELALAOUI SARA <sara.elalaoui92@gmail.com>:

> No. The problem is :  In the
> MetadataRetrieveController.retrieveMetadataItem method it retrieves only
> custom Fields when MetadataType="CustomField". Normally, it suppose to
> retrieve supported standard fields,such as Account.Industry, as well.
>
>
> Thanks.
>
> 2015-05-17 11:30 GMT+00:00 Andrew Fawcett <notifications@github.com>:
>
>> In the MetadataServiceExamples.updatePicklist method it retrieves a
>> custom field on the Lead standard object like so, are you saying this
>> doesn't work for you?
>>
>>     // Read Custom Field
>>     MetadataService.CustomField customField =
>>         (MetadataService.CustomField) service.readMetadata('CustomField',
>>             new String[] { 'Lead.picklist__c' }).getRecords()[0];
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/financialforcedev/apex-mdapi/issues/85#issuecomment-102785864>
>> .
>>
>
>
>
> --
> *Sara ELALAOUI *
>
>
> *Élève Ingénieur en Génie Informatique École Nationale des Sciences
> Appliquées de Safi**Université Cadi Ayad - Maroc*
>



-- 
*Sara ELALAOUI *


*Élève Ingénieur en Génie Informatique École Nationale des Sciences
Appliquées de Safi**Université Cadi Ayad - Maroc*

**Comment by afawcett** [comment]
Ok i see, so your using the sample MetadataRetrieveController class and page. Can you give me the steps to reproduce your problem with screenshots i think this will help me better understand.

**Comment by afawcett** [comment]
Let me know if you still want me to follow up with you on this.

**Comment by 5KHUSHBOO** [comment]
@SaraELA  hi, I'm facing the same issues, I'm trying to update the field values of a standard picklist field, but it is only working for custom fields
did you find any solution, please reply
