### ISSUE TITLE
Error on delete List View

### ISSUE THREAD

**Issue by maximorojr** [financialforcedev/apex-mdapi#86]
I'm trying to delete List Views  and I'm getting the following error.
It's seem to be like my List Views isn't available for deleteMetadata, I've checked the full name through workbench, standard Salesforce UI, listMetaData() and the name is right. I'm able to create, I'm not able delete.

Error occured processing component CustomObject__c.MyListView. In field: members - no ListView named CustomObject__c.MyListView found (INVALID_CROSS_REFERENCE_KEY).

I'm trying to do that through a partner organization with managed package. I'm following the guidelines, and I think there is a permission needed to be granted that I didn't catch yet, or it's something related to the managed package, because from my developer organization the same code works perfect.

There is my code(The same as we can see at MetaDataServiceExamples):
```
MetadataService.MetadataPort service = MetaDataJob.createService();     
List<MetadataService.DeleteResult> results =        
        service.deleteMetadata(
            'ListView', new String[] { 'CustomObject__c.MyListView' });
MetaDataJob.handleDeleteResults(results[0]);
```

**Comment by maximorojr** [comment]
I've tried to delete CustomObject, StaticResource and the error is the same "some fullName not found". The same happens when I try to update some MetaData.

**Comment by afawcett** [comment]
I am wondering if your running into this [restriction](http://www.salesforce.com/us/developer/docs/api_meta/Content/meta_listview.htm)...

"List views with the Visible only to me Restrict Visibility option are not accessible in Metadata API. Each of these list views is associated with a particular user."

**Comment by afawcett** [comment]
As regards creating and deleting CustomObject and Static Resource, can you try the ones in the MetadataServiceExample.cls and let me know if these also fail in your org?

**Comment by maximorojr** [comment]
About the restriction, I've checked it, I'm creating exactly like the examples with "Everything" as filter scope.

I've tried using the MetadataServiceExample.cls, the results are below, I'm able to create any metadata and I'm not able to delete.

PS: I've installed my app on a tests org and the delete is working perfectly. It seems to be a problem with the organization that we use to maintain the app development. 

![createobjectcreatefieldsuccess](https://cloud.githubusercontent.com/assets/2715827/7411945/a033e206-ef13-11e4-95c5-92e3e14e6011.png)
![deletefieldfail](https://cloud.githubusercontent.com/assets/2715827/7411947/a03a9fb0-ef13-11e4-8a8a-f668399a0dc4.png)
![upsertobjectfail](https://cloud.githubusercontent.com/assets/2715827/7411946/a037de56-ef13-11e4-9035-b26c0ad299ba.png)

**Comment by afawcett** [comment]
Ah this is because you are in a namespaced org, you will need to quite often apply pl01 namespace prefix in places. Best thing to do is as per my FAQ blog post (see README file) is use Developer Console to understand the correct Fullnames to use.

**Comment by maximorojr** [comment]
You got it! I was missing to set the namespace, I was trying to put the namespace only on the listview name, and we've to put the namespace before the custom object api name too. Thanks!
