### ISSUE TITLE
No variable "fullName" in ListView class

### ISSUE THREAD

**Issue by tanumaydas** [financialforcedev/apex-mdapi#87]
Hi there i was following your guide to create a list view. Unfortunately on line 669
 (listView.fullName = 'Test__c.MyListView';) it produces an ERROR that says there is no variable fullname in listview. Actually i inspected the class and found out that there is actually no variable "fullname" in the ListView Class.

Can you please help in this issue

**Comment by afawcett** [comment]
If you use the [MetadataService.cls](https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataService.cls#L7324) from this repository there is.
