### ISSUE TITLE
Unable to update recordtype picklist values

### ISSUE THREAD

**Issue by Sudha613** [financialforcedev/apex-mdapi#90]
Hi,

I am trying to update picklist values of 2 picklist fields on Product record types. Below is my code:
```
MetadataService.Metadata[] metadataToUpdate = new List<MetadataService.Metadata>();
List<MetadataService.RecordTypePicklistValue> lstRtPlv = new List<MetadataService.RecordTypePicklistValue>();
FOR(RecordType rt : [SELECT Id, Name, DeveloperName, isActive, sObjectType FROM RecordType WHERE sObjectType = 'Product2']){

	MetadataService.RecordType objRT = new MetadataService.RecordType();
	objRT.active = rt.IsActive;
	objRT.label = rt.Name;
	objRT.fullName = rt.DeveloperName;
	
	MetadataService.RecordTypePicklistValue rtplv1 = new MetadataService.RecordTypePicklistValue();
	rtplv1.picklist = 'Aircraft_1__c';
	rtplv1.values = plvList;
	
	MetadataService.RecordTypePicklistValue rtplv2 = new MetadataService.RecordTypePicklistValue();
	rtplv2.picklist = 'Aircraft_2__c';
	rtplv2.values = plvList;
	
	lstRtPlv = new List{rtplv1,rtplv2};
	rt.picklistValues = lstRtPlv;
	metadataToUpdate.add(rt);
} 
List results1 = service.updateMetadata(metadataToUpdate);
MetadataServiceExamples.handleSaveResults(results1[0]);

```
This has to happen in a trigger so I have kept this code in future method. If I insert any value with + sign in it, the apex job fails with following error: 
```
First error: Error occured processing component Product2.NetJets_Card_Product. duplicate value found: duplicates value on record with id: (DUPLICATE_VALUE).
```

Also, if the picklist field already contains values like 'Citation - Encore', 'Citation Excel + ', etc.  with special characters, I encounter same error. 

Note : The values get added to picklist fields successfully, but the above exception is thrown when trying to update record type picklist values.

What is wrong?

**Comment by Sudha613** [comment]
No reply?

**Comment by afawcett** [comment]
Sorry @Sudha613 i tend to mostly support this in my personal time, which can be impacted by work commitments at times, and its been a busy week!  I'm afraid i don't have a good explanation for what might be causing this on this occasion. Remmber that this repo and its code simply wraps the Salesforce Metadata API which they support. What i would recommend is capturing from the debug log the SOAP request and SOAP response and sending this to Salesforce via a Support case so they can reproduce it. Indeed reviewing yourself the SOAP request constructed by this code might in itself reveal some further insight. Sorry i cannot help more on this occasion.
