### ISSUE TITLE
Can't get fields list metadata of an article type

### ISSUE THREAD

**Issue by Nivg** [financialforcedev/apex-mdapi#92]
Hi, 

I was trying to get fields list metadata of an article type (ArticleTypeName__kav object), since I can't get it from the Schema.getGlobalDescribe().

That what I was trying:
```java
MetadataService.MetadataPort service = createService();
MetadataService.CustomObject customObject = (MetadataService.CustomObject) service.readMetadata('CustomObject', new String[] { 'MyArticeTest__kav' }).getRecords()[0];
for(MetadataService.CustomField field : customObject.fields)
{
    System.debug('Field Name: ' + field.fullName);
}
```
But I get ```null``` for the ```customObject```.

Note that when I'm getting all of the Custom objects using the following:
```java
List<MetadataService.ListMetadataQuery> queries = new List<MetadataService.ListMetadataQuery>();    
MetadataService.ListMetadataQuery query = new MetadataService.ListMetadataQuery();
query.type_x = 'CustomObject';
queries.add(query);
MetadataService.FileProperties[] fileProperties = service.listMetadata(queries, METADATA_API_VERSION);
```
I do get my ```MyArticeTest__kav```.

Thanks

**Comment by afawcett** [comment]
Sorry, i'm not familiar with the __kav extension, what kind of CUstom Object is this?

**Comment by Nivg** [comment]
It's under the knowledge base data model: [Salesforce Knowledge Objects](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_erd_knowledge.htm)

If you ever used the Partner WSDL API it is listed like any other custom object in the metadata including fields metadata as well. Because of that and since it is listed under your MetadataService-CustomObject, I assumed it's fields metadata will be available as well.

**Comment by afawcett** [comment]
Hmmm this looks like a system generated object, i suspect its not supported by the Metadata API. According to the docs, describeSObject is support, https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_knowledgearticleversion.htm. So i guess this means you need to use that from the Partner WSDL API as you say.
