### ISSUE TITLE
Updating profile field level security resets other field permissions 

### ISSUE THREAD

**Issue by mintotsai** [financialforcedev/apex-mdapi#99]
After updating the Admin profile field level security for an Activity custom field to editable true (or visibility true),  the other Admin field level security for custom fields on the same object Activity gets set to editable false, when prior to update they were true.

Here's the example code:
```
MetadataService.MetadataPort service = new MetadataService.MetadataPort();
service.SessionHeader = new MetadataService.SessionHeader_element();
service.SessionHeader.sessionId = UserInfo.getSessionId();

MetadataService.Profile admin = new MetadataService.Profile();
admin.fullName = 'Admin';
admin.custom = false;

MetadataService.ProfileFieldLevelSecurity fieldSec = new MetadataService.ProfileFieldLevelSecurity();
fieldSec.field='Activity.GCal_Recur_Id__c';
fieldSec.editable=true;
fieldSec.readable=true;
admin.fieldPermissions  = new MetadataService.ProfileFieldLevelSecurity[] {fieldSec} ;
List<MetadataService.SaveResult> results =
     service.updateMetadata( new MetadataService.Metadata[] { admin });
```

Am I doing something incorrectly here?

**Comment by afawcett** [comment]
Updating profiles is still a bit of mystery to me behaviour wise tbh. Sometimes it seems to support partial updates, other times, in your case it seems thats not the case. So my only suggestion here is to try to retrieve the profile before doing the update.

**Comment by afawcett** [comment]
I would honestly recommend you consider adopting Permission Sets, you can create and manipulate these in native DML, and even assign them to users in DML. No Metadata API required and you achieve the same goal.

**Comment by mintotsai** [comment]
Thanks, @afawcett. I went with Permission Sets to solve this.

**Comment by danepet** [comment]
@afawcett  / @mintotsai Using Permission Sets - there are a few caveats of using DML. If a field+object combo is over 40 characters Salesforce will not allow you to update it.

**Comment by afawcett** [comment]
Wow @danepet thanks for sharing! That does sound like a bug though. Have you raised it with support?

**Comment by danepet** [comment]
@afawcett  It appears that it's tied to this idea that has been brought up and has garnered quite a few votes: 
https://success.salesforce.com/ideaView?id=08730000000Y2HMAA0https://success.salesforce.com/ideaView?id=08730000000Y2HMAA0.

I would assume that if this limit increased then it would be across the board and hit Field Permissions as well. 

I am going to raise this as a separate issue to support as well, as the limit would have to be (Max Namespace char size * 2) + Object Max Name Size + Field Max Name Size to hit all use cases that I can think of.

**Comment by afawcett** [comment]
Thanks @danepet for sharing your update!

**Comment by mintotsai** [comment]
Leaving this here for future readers. For the original issue, when updating profile field level security for Activity custom fields, if updating one field at a time, this will unset field permissions for other custom fields. Seems to only happen for Activity custom fields.

When this happens, the standard Activity fields (Who, What, & Description) will get unset as well.

To update without this happening, you need to update all the custom fields and the 3 standard Activity fields (Who, What, & Description) at the same time, in batch.

**Comment by afawcett** [comment]
THanks @mintotsai for sharing!

**Comment by Sheing** [comment]
@mintotsai That was very helpful and good to know even after 3 years!
